import React,{useMemo}from'react';
import{AlertTriangle,ArrowRight,CheckCircle2,Clock3,FileCheck2,Mail,PackageCheck,Target,TrendingUp,Zap}from'lucide-react';
import{daysLeft,isWorkClosed,money}from'../domain/workspace.js';

const deadlineText=days=>days<0?`просрочено ${Math.abs(days)} дн.`:days===0?'сегодня':days===1?'завтра':`${days} дн.`;

export function DashboardView({works,onOpenWork,settings={}}){
 const activeWorks=useMemo(()=>works.filter(work=>!isWorkClosed(work)),[works]);
 const stats=useMemo(()=>{const allPositions=activeWorks.flatMap(work=>work.activePositions.map(position=>({...position,work}))),overdue=activeWorks.filter(work=>daysLeft(work.deadline)<0).length,deadlinesToday=activeWorks.filter(work=>daysLeft(work.deadline)===0).length,tomorrow=activeWorks.filter(work=>daysLeft(work.deadline)===1).length,waitingTkp=allPositions.filter(position=>position.offers.length&&!position.offers.some(offer=>offer.hasTkp)).length,noSupplier=allPositions.filter(position=>!position.offers.some(offer=>offer.supplierId)).length,readyForQuote=allPositions.filter(position=>position.nextStep==='Готово к КП').length,blocked=allPositions.filter(position=>position.warnings.length).length,potentialNetProfit=activeWorks.reduce((sum,work)=>sum+Number(work.totals.netProfit||0),0);return{overdue,deadlinesToday,tomorrow,waitingTkp,noSupplier,readyForQuote,blocked,potentialNetProfit,allPositions}},[activeWorks]);
 const allActions=useMemo(()=>{const items=[];activeWorks.forEach(work=>work.activePositions.forEach(position=>{if(position.nextStep==='Готово')return;const days=daysLeft(work.deadline);let priority=3;if(days<0)priority=0;else if(days===0)priority=1;else if(days===1||position.warnings.length>2)priority=2;items.push({id:`${work.id}-${position.id}`,work,position,priority,title:position.nextStep,subtitle:`${work.customer} · позиция №${position.rowNo} · ${position.name}`,deadline:days})}));return items.sort((a,b)=>a.priority-b.priority||a.deadline-b.deadline)},[activeWorks]);
 const visibleActions=allActions.slice(0,8),hotWork=activeWorks.slice().sort((a,b)=>daysLeft(a.deadline)-daysLeft(b.deadline)||b.blockers-a.blockers)[0],currency=settings.currency||'RUB';
 return <main className="dashboard-page"><section className="dashboard-hero"><div><span>Центр управления</span><h1>Требуют внимания {allActions.length} действий</h1><p>Показаны активные тендеры и незакрытые позиции. Закрытые работы исключены из очереди.</p></div>{hotWork&&<button onClick={()=>onOpenWork(hotWork.id)}><Zap/>Начать с {hotWork.customer}<ArrowRight/></button>}</section>
 <section className="dashboard-signals"><article className="signal-card critical"><AlertTriangle/><div><span>Просрочено</span><b>{stats.overdue}</b></div></article><article className="signal-card critical"><Clock3/><div><span>Дедлайны сегодня</span><b>{stats.deadlinesToday}</b></div></article><article className="signal-card warning"><Mail/><div><span>ТКП не получено</span><b>{stats.waitingTkp}</b></div></article><article className="signal-card success"><FileCheck2/><div><span>Готово к КП</span><b>{stats.readyForQuote}</b></div></article><article className="signal-card info"><TrendingUp/><div><span>Ожидаемая чистая прибыль</span><b>{money(stats.potentialNetProfit,currency)}</b></div></article></section>
 <section className="dashboard-grid"><div className="dashboard-main-card"><div className="dashboard-section-head"><div><span>Автопилот менеджера</span><h2>Очередь действий</h2></div><em>{stats.blocked} позиций требуют внимания · показано {visibleActions.length} из {allActions.length}</em></div><div className="action-queue">{visibleActions.map((item,index)=><button key={item.id} onClick={()=>onOpenWork(item.work.id)} className={`queue-item priority-${item.priority}`}><span className="queue-number">{index+1}</span><div><b>{item.title}</b><p>{item.subtitle}</p></div><small>{deadlineText(item.deadline)}</small><ArrowRight/></button>)}{!visibleActions.length&&<div className="documents-empty"><CheckCircle2/><b>Нет срочных действий</b><span>Все активные позиции обработаны.</span></div>}</div></div>
 <aside className="dashboard-side"><section><div className="mini-title"><Target/>Состояние отдела</div><div className="health-line"><span>Активные тендеры</span><b>{activeWorks.length}</b></div><div className="health-line"><span>Просрочено</span><b>{stats.overdue}</b></div><div className="health-line"><span>Завтра</span><b>{stats.tomorrow}</b></div><div className="health-line"><span>Проблемные позиции</span><b>{stats.blocked}</b></div></section><section><div className="mini-title"><PackageCheck/>Ближайшие тендеры</div>{activeWorks.slice().sort((a,b)=>daysLeft(a.deadline)-daysLeft(b.deadline)).slice(0,4).map(work=><button className="deadline-row" key={work.id} onClick={()=>onOpenWork(work.id)}><div><b>{work.customer}</b><span>{work.title}</span></div><em>{deadlineText(daysLeft(work.deadline))}</em></button>)}</section><section className="dashboard-ready"><CheckCircle2/><div><b>{stats.readyForQuote} позиций готовы</b><span>Можно переходить к формированию коммерческих предложений.</span></div></section></aside></section></main>;
}
