import React,{useMemo,useState}from'react';
import{AlertTriangle,ArrowRight,BriefcaseBusiness,CheckCircle2,Clock3,FileCheck2,Flame,Mail,PackageSearch,Target,TimerReset,TrendingUp,UserRound,Zap}from'lucide-react';
import{daysLeft,money}from'../domain/workspace.js';
import{buildManagerDesk}from'../domain/managerDesk.js';

const deadlineText=days=>days<0?`просрочено ${Math.abs(days)} дн.`:days===0?'сегодня':days===1?'завтра':days===999?'без срока':`${days} дн.`;
const priorityLabel={critical:'Критично',high:'Высокий',medium:'Средний',low:'Планово'};

export function DashboardView({works,onOpenWork,settings={},data,currentUser}){
 const canSeeTeam=currentUser?.role==='admin'||currentUser?.role==='head';
 const[scope,setScope]=useState(canSeeTeam?'all':'mine');
 const desk=useMemo(()=>buildManagerDesk({works,events:data?.events||[],currentUser,scope}),[works,data?.events,currentUser,scope]);
 const{stats,actions,focus,mostProfitable,workload}=desk,currency=settings.currency||'RUB',visibleActions=actions.slice(0,10);
 const hours=Math.floor(stats.estimatedMinutes/60),minutes=stats.estimatedMinutes%60;
 return <main className="dashboard-page manager-desk">
  <section className="dashboard-hero manager-hero"><div><span>Рабочий стол менеджера</span><h1>{currentUser?.name||'Менеджер'}, сегодня {actions.length} действий</h1><p>{stats.overdue?`${stats.overdue} просроченных тендера требуют немедленного внимания.`:'Просроченных тендеров нет.'} Расчетная нагрузка — {hours?`${hours} ч `:''}{minutes} мин.</p></div><div className="manager-hero-actions">{canSeeTeam&&<div className="scope-switch"><button className={scope==='mine'?'active':''} onClick={()=>setScope('mine')}>Мои</button><button className={scope==='all'?'active':''} onClick={()=>setScope('all')}>Отдел</button></div>}{focus&&<button className="focus-button" onClick={()=>onOpenWork(focus.workId)}><Zap/>Начать с главного<ArrowRight/></button>}</div></section>
  <section className="manager-focus-grid">
   <article className="focus-card primary-focus">{focus?<><div className="focus-icon"><Flame/></div><div><span>Следующее лучшее действие</span><h2>{focus.title}</h2><p>{focus.subtitle}</p><div className="focus-meta"><b>{priorityLabel[focus.priority]}</b><em>{deadlineText(focus.deadlineDays)}</em><small>≈ {focus.estimate} мин.</small></div></div><button onClick={()=>onOpenWork(focus.workId)}>Открыть<ArrowRight/></button></>:<><CheckCircle2/><div><h2>Очередь разобрана</h2><p>Для выбранного режима нет активных действий.</p></div></>}</article>
   <article className="focus-card profit-focus"><TrendingUp/><div><span>Самая большая чистая прибыль</span><h2>{mostProfitable?money(mostProfitable.totals.netProfit,currency):'—'}</h2><p>{mostProfitable?`${mostProfitable.customer} · ${mostProfitable.title}`:'Нет активных тендеров'}</p></div>{mostProfitable&&<button onClick={()=>onOpenWork(mostProfitable.id)}><ArrowRight/></button>}</article>
  </section>
  <section className="dashboard-signals manager-signals"><article className="signal-card critical"><AlertTriangle/><div><span>Просрочено</span><b>{stats.overdue}</b></div></article><article className="signal-card critical"><Clock3/><div><span>Срок сегодня</span><b>{stats.today}</b></div></article><article className="signal-card warning"><PackageSearch/><div><span>Нет поставщика</span><b>{stats.noSupplier}</b></div></article><article className="signal-card warning"><Mail/><div><span>Ждём ТКП</span><b>{stats.waitingTkp}</b></div></article><article className="signal-card success"><FileCheck2/><div><span>Готово к КП</span><b>{stats.readyForQuote}</b></div></article><article className="signal-card info"><UserRound/><div><span>Клиент ждёт ответа</span><b>{stats.clientWaiting}</b></div></article></section>
  <section className="dashboard-grid manager-grid"><div className="dashboard-main-card"><div className="dashboard-section-head"><div><span>Автопилот</span><h2>Очередь рабочего дня</h2></div><em>показано {visibleActions.length} из {actions.length}</em></div><div className="action-queue">{visibleActions.map((item,index)=><button key={item.id} onClick={()=>onOpenWork(item.workId)} className={`queue-item priority-${item.priority}`}><span className="queue-number">{index+1}</span><div><b>{item.title}</b><p>{item.subtitle}</p><div className="queue-tags"><span>{priorityLabel[item.priority]}</span><span>≈ {item.estimate} мин.</span>{item.profit>0&&<span>{money(item.profit,currency)}</span>}</div></div><small>{deadlineText(item.deadlineDays)}</small><ArrowRight/></button>)}{!visibleActions.length&&<div className="documents-empty"><CheckCircle2/><b>Нет срочных действий</b><span>Все активные позиции обработаны.</span></div>}</div></div>
   <aside className="dashboard-side manager-side"><section><div className="mini-title"><Target/>Моя нагрузка</div><div className="health-line"><span>Активные тендеры</span><b>{stats.activeWorks}</b></div><div className="health-line"><span>Действия</span><b>{actions.length}</b></div><div className="health-line"><span>Расчетное время</span><b>{hours?`${hours}ч `:''}{minutes}м</b></div><div className="health-line"><span>Низкая маржа</span><b>{stats.lowMargin}</b></div><div className="health-line"><span>Чистая прибыль</span><b>{money(stats.netProfit,currency)}</b></div></section>
    {canSeeTeam&&scope==='all'&&<section><div className="mini-title"><BriefcaseBusiness/>Нагрузка отдела</div>{workload.slice(0,6).map(item=><div className="manager-load" key={item.manager}><div><b>{item.manager}</b><span>{item.works} тенд. · {item.overdue} проср.</span></div><em>{item.actions}</em></div>)}</section>}
    <section><div className="mini-title"><TimerReset/>Ближайшие тендеры</div>{desk.works.slice().sort((a,b)=>daysLeft(a.deadline)-daysLeft(b.deadline)).slice(0,5).map(work=><button className="deadline-row" key={work.id} onClick={()=>onOpenWork(work.id)}><div><b>{work.customer}</b><span>{work.title}</span></div><em>{deadlineText(daysLeft(work.deadline))}</em></button>)}</section>
   </aside>
  </section>
 </main>;
}
