import React,{useMemo,useState}from'react';
import{Banknote,Calculator,ChevronRight,CircleDollarSign,Landmark,Percent,Save,Settings2,ShieldCheck,TrendingUp,Users}from'lucide-react';
import{money,pct}from'../domain/workspace.js';
import{calculateCompanyFinance,FINANCE_SETTING_FIELDS,financeDefaults}from'../domain/directorFinance.js';

export function DirectorFinanceCenter({data,setData,works,onOpenWork,currentUser}){
 const currency=data.settings?.currency||'RUB',[draft,setDraft]=useState({...financeDefaults,...data.settings}),[saved,setSaved]=useState(''),company=useMemo(()=>calculateCompanyFinance(works,draft),[works,draft]);
 const patch=(key,value)=>setDraft(current=>({...current,[key]:Number(value||0)}));
 const save=()=>{const old=data.settings||{},changed=FINANCE_SETTING_FIELDS.filter(field=>Number(old[field.key]??financeDefaults[field.key])!==Number(draft[field.key])).map(field=>`${field.label}: ${old[field.key]??financeDefaults[field.key]} → ${draft[field.key]}`);setData(current=>({...current,settings:{...current.settings,...draft},events:[{id:globalThis.crypto?.randomUUID?.()||String(Date.now()),type:'finance-settings',title:'Директор изменил финансовую модель',detail:changed.join('; ')||'Без изменений',author:currentUser?.name||'Директор',actorId:currentUser?.id||null,entityType:'settings',entityId:'finance',source:'director',createdAt:new Date().toISOString()},...(current.events||[])]}));setSaved('Финансовая модель опубликована и применяется к расчетам');setTimeout(()=>setSaved(''),2500)};
 return <main className="director-finance-page">
  <header className="director-finance-head"><div><span>Доступ директора · финансовая модель</span><h1>Финансовый центр</h1><p>Единые правила для всех сделок. Менеджеры вводят факты, система применяет опубликованные нормативы автоматически.</p></div><button className="primary" onClick={save}><Save/>Опубликовать настройки</button></header>
  {saved&&<div className="finance-saved"><ShieldCheck/>{saved}</div>}
  <section className="finance-kpis"><article><Banknote/><div><span>Выручка в сделках</span><b>{money(company.revenue,currency)}</b></div></article><article><TrendingUp/><div><span>Валовая прибыль</span><b>{money(company.grossProfit,currency)}</b></div></article><article><CircleDollarSign/><div><span>Чистая прибыль</span><b>{money(company.netBeforeDividends,currency)}</b><small>маржа {pct(company.margin)}</small></div></article><article><Users/><div><span>Премии</span><b>{money(company.managerBonus+company.participantBonus,currency)}</b></div></article><article><Landmark/><div><span>Налоги и банки</span><b>{money(company.tax+company.creditCost+company.bankFees+company.guarantees,currency)}</b></div></article><article><Calculator/><div><span>Дивиденды</span><b>{money(company.dividends,currency)}</b><small>остаток {money(company.retainedProfit,currency)}</small></div></article></section>
  <div className="director-finance-layout">
   <section className="finance-rules"><div className="finance-card-head"><div><span>Правила компании</span><h2>Нормативы и ставки</h2></div><Settings2/></div><div className="finance-rule-grid">{FINANCE_SETTING_FIELDS.map(field=><label key={field.key}><span>{field.group}</span><b>{field.label}</b><div><input type="number" min="0" max="100" step="0.1" value={draft[field.key]??0} onChange={event=>patch(field.key,event.target.value)}/><em>{field.unit}</em></div></label>)}</div><div className="finance-access"><ShieldCheck/><div><b>Права менеджера</b><span>Менеджер вводит закупку, продажу, сроки, расходы и участников. Формулы, ставки, налоги, кредиты и дивиденды меняет только директор.</span></div><label><input type="checkbox" checked={draft.managerCanSeeNetProfit!==false} onChange={event=>setDraft({...draft,managerCanSeeNetProfit:event.target.checked})}/>Показывать чистую прибыль менеджеру</label><label><input type="checkbox" checked={draft.managerCanEnterParticipantBonus!==false} onChange={event=>setDraft({...draft,managerCanEnterParticipantBonus:event.target.checked})}/>Разрешить ввод премии участнику сделки</label></div></section>
   <section className="finance-breakdown"><div className="finance-card-head"><div><span>Распределение результата</span><h2>Экономика компании</h2></div><Percent/></div>{[['Валовая прибыль',company.grossProfit],['Стоимость кредита',-company.creditCost],['Банковские комиссии',-company.bankFees],['Гарантии',-company.guarantees],['Резерв риска',-company.riskReserve],['Накладные расходы',-company.overhead],['Налоги',-company.tax],['Премии менеджерам',-company.managerBonus],['Премии участникам',-company.participantBonus],['Чистая прибыль',company.netBeforeDividends],['Дивиденды',-company.dividends],['Нераспределенная прибыль',company.retainedProfit]].map(([label,value],index)=><div className={`finance-line ${index>=9?'total':''}`} key={label}><span>{label}</span><b className={value<0?'negative':''}>{value<0?'− ':''}{money(Math.abs(value),currency)}</b></div>)}</section>
  </div>
  <section className="finance-deals"><div className="finance-card-head"><div><span>Применение правил</span><h2>Экономика каждой сделки</h2></div><Calculator/></div><div className="finance-deal-table"><div className="finance-deal-row head"><span>Проект</span><span>Выручка</span><span>Валовая прибыль</span><span>Кредит/банки</span><span>Налоги</span><span>Премии</span><span>Чистая прибыль</span><span>Маржа</span><span/></div>{company.deals.map(({work,finance})=><button className="finance-deal-row" key={work.id} onClick={()=>onOpenWork(work.id)}><span><b>{work.customer}</b><small>{work.code} · {work.title}</small></span><span>{money(finance.revenue,currency)}</span><span>{money(finance.grossProfit,currency)}</span><span>{money(finance.creditCost+finance.bankFees+finance.guarantees,currency)}</span><span>{money(finance.tax,currency)}</span><span>{money(finance.totalBonus,currency)}</span><span><b>{money(finance.netProfit,currency)}</b></span><span>{pct(finance.margin)}</span><span><ChevronRight/></span></button>)}</div></section>
 </main>
}