import React,{useMemo,useState}from'react';
import{Banknote,Calculator,ChevronRight,CircleDollarSign,Landmark,Percent,RotateCcw,Save,Settings2,ShieldCheck,TrendingUp,Users}from'lucide-react';
import{money,pct}from'../domain/workspace.js';
import{calculateCompanyFinance,FINANCE_SETTING_FIELDS,financeDefaults}from'../domain/directorFinance.js';

export function DirectorFinanceCenter({data,setData,works,onOpenWork,currentUser}){
 const currency=data.settings?.currency||'RUB',[draft,setDraft]=useState({...financeDefaults,...data.settings}),[saved,setSaved]=useState(''),company=useMemo(()=>calculateCompanyFinance(works,draft),[works,draft]);
 const changedFields=FINANCE_SETTING_FIELDS.filter(field=>Number(data.settings?.[field.key]??financeDefaults[field.key])!==Number(draft[field.key])) ,accessChanged=(data.settings?.managerCanSeeNetProfit!==false)!==(draft.managerCanSeeNetProfit!==false)||(data.settings?.managerCanEnterParticipantBonus!==false)!==(draft.managerCanEnterParticipantBonus!==false),dirty=changedFields.length>0||accessChanged;
 const patch=(key,value)=>setDraft(current=>({...current,[key]:Math.max(0,Math.min(100,Number(value||0)))}));
 const reset=()=>{setDraft({...financeDefaults,...data.settings});setSaved('Изменения отменены')};
 const save=()=>{if(!dirty)return;const old=data.settings||{},changed=changedFields.map(field=>`${field.label}: ${old[field.key]??financeDefaults[field.key]} → ${draft[field.key]}`);if(accessChanged)changed.push('Изменены права отображения для менеджера');setData(current=>({...current,settings:{...current.settings,...draft},events:[{id:globalThis.crypto?.randomUUID?.()||String(Date.now()),type:'finance-settings',title:'Директор изменил финансовую модель',detail:changed.join('; '),author:currentUser?.name||'Директор',actorId:currentUser?.id||null,entityType:'settings',entityId:'finance',source:'director',createdAt:new Date().toISOString()},...(current.events||[])]}));setSaved('Настройки опубликованы и применяются к расчетам');setTimeout(()=>setSaved(''),2500)};
 return <main className="director-finance-page">
  <header className="director-finance-head"><div><span>Доступ директора · финансовая модель</span><h1>Финансовый центр</h1><p>Настройте единые правила компании. Показатели ниже пересчитываются как предварительный просмотр до публикации.</p></div><div className="finance-publish-actions">{dirty&&<button onClick={reset}><RotateCcw/>Отменить изменения</button>}<button className="primary" disabled={!dirty} onClick={save}><Save/>{dirty?`Опубликовать (${changedFields.length+(accessChanged?1:0)})`:'Настройки опубликованы'}</button></div></header>
  {dirty&&<div className="finance-preview-note"><Settings2/><div><b>Предварительный просмотр</b><span>Расчеты на экране уже учитывают новые значения, но менеджеры получат их только после публикации.</span></div></div>}
  {saved&&<div className="finance-saved"><ShieldCheck/>{saved}</div>}
  <section className="finance-kpis"><article><Banknote/><div><span>Выручка в сделках</span><b>{money(company.revenue,currency)}</b></div></article><article><TrendingUp/><div><span>Валовая прибыль</span><b>{money(company.grossProfit,currency)}</b></div></article><article><CircleDollarSign/><div><span>Чистая прибыль</span><b>{money(company.netBeforeDividends,currency)}</b><small>маржа {pct(company.margin)}</small></div></article><article><Users/><div><span>Премии</span><b>{money(company.managerBonus+company.participantBonus,currency)}</b></div></article><article><Landmark/><div><span>Налоги и банки</span><b>{money(company.tax+company.creditCost+company.bankFees+company.guarantees,currency)}</b></div></article><article><Calculator/><div><span>Дивиденды</span><b>{money(company.dividends,currency)}</b><small>остаток {money(company.retainedProfit,currency)}</small></div></article></section>
  <div className="director-finance-layout">
   <section className="finance-rules"><div className="finance-card-head"><div><span>Правила компании</span><h2>Нормативы и ставки</h2></div><Settings2/></div><div className="finance-rule-grid">{FINANCE_SETTING_FIELDS.map(field=><label className={changedFields.some(item=>item.key===field.key)?'changed':''} key={field.key}><span>{field.group}</span><b>{field.label}</b><div><input aria-label={field.label} type="number" min="0" max="100" step="0.1" value={draft[field.key]??0} onChange={event=>patch(field.key,event.target.value)}/><em>{field.unit}</em></div></label>)}</div><div className="finance-access"><ShieldCheck/><div><b>Что видит менеджер</b><span>Менеджер вводит факты сделки. Ставки, налоги, кредиты, резервы и дивиденды меняет только директор.</span></div><label><input type="checkbox" checked={draft.managerCanSeeNetProfit!==false} onChange={event=>setDraft(current=>({...current,managerCanSeeNetProfit:event.target.checked}))}/>Показывать менеджеру чистую прибыль</label><label><input type="checkbox" checked={draft.managerCanEnterParticipantBonus!==false} onChange={event=>setDraft(current=>({...current,managerCanEnterParticipantBonus:event.target.checked}))}/>Разрешить менеджеру ввод премии участника</label></div></section>
   <section className="finance-breakdown"><div className="finance-card-head"><div><span>Распределение результата</span><h2>Экономика компании</h2></div><Percent/></div>{[['Валовая прибыль',company.grossProfit],['Стоимость кредита',-company.creditCost],['Банковские комиссии',-company.bankFees],['Гарантии',-company.guarantees],['Резерв риска',-company.riskReserve],['Накладные расходы',-company.overhead],['Налоги',-company.tax],['Премии менеджерам',-company.managerBonus],['Премии участникам',-company.participantBonus],['Чистая прибыль',company.netBeforeDividends],['Дивиденды',-company.dividends],['Нераспределенная прибыль',company.retainedProfit]].map(([label,value],index)=><div className={`finance-line ${index>=9?'total':''}`} key={label}><span>{label}</span><b className={value<0?'negative':''}>{value<0?'− ':''}{money(Math.abs(value),currency)}</b></div>)}</section>
  </div>
  <section className="finance-deals"><div className="finance-card-head"><div><span>Применение правил</span><h2>Экономика каждой сделки</h2></div><Calculator/></div><div className="finance-deal-table"><div className="finance-deal-row head"><span>Сделка</span><span>Выручка</span><span>Валовая прибыль</span><span>Кредит/банки</span><span>Налоги</span><span>Премии</span><span>Чистая прибыль</span><span>Маржа</span><span/></div>{company.deals.map(({work,finance})=><button className="finance-deal-row" key={work.id} onClick={()=>onOpenWork(work.id)}><span><b>{work.customer}</b><small>{work.code} · {work.title}</small></span><span>{money(finance.revenue,currency)}</span><span>{money(finance.grossProfit,currency)}</span><span>{money(finance.creditCost+finance.bankFees+finance.guarantees,currency)}</span><span>{money(finance.tax,currency)}</span><span>{money(finance.totalBonus,currency)}</span><span><b>{money(finance.netProfit,currency)}</b></span><span>{pct(finance.margin)}</span><span><ChevronRight/></span></button>)}{!company.deals.length&&<div className="finance-empty">Сделок для расчета пока нет.</div>}</div></section>
 </main>;
}
