import React,{useMemo,useState}from'react';
import{AlertTriangle,ArrowRight,BarChart3,BriefcaseBusiness,Building2,CircleDollarSign,Search,Target,TrendingUp,Users}from'lucide-react';
import{money}from'../domain/workspace.js';
import{buildDirectorAnalytics}from'../domain/directorAnalytics.js';

const pct=value=>`${Number(value||0).toFixed(1)}%`;
const width=(value,max)=>`${max?Math.max(4,Math.round(value/max*100)):0}%`;

export function DirectorView({data,works,onOpenWork}){
 const[tab,setTab]=useState('overview'),[query,setQuery]=useState(''),analytics=useMemo(()=>buildDirectorAnalytics({data,works}),[data,works]),currency=data.settings?.currency||'RUB',maxPipeline=Math.max(1,...analytics.pipeline.map(item=>item.amount));
 const filteredRisks=analytics.risks.filter(item=>`${item.customer} ${item.title} ${item.code} ${item.manager}`.toLowerCase().includes(query.toLowerCase()));
 return <main className="director-page">
  <header className="director-head"><div><span>Director access · Business Control</span><h1>Компания в режиме реального времени</h1><p>Поиск возможностей, активные проекты, деньги, риски и эффективность команды — с проваливанием до первичных данных.</p></div><div className="director-live"><i/>Данные обновляются из действий сотрудников</div></header>
  <section className="director-kpis">
   <article><Target/><div><span>Возможности</span><b>{money(analytics.summary.opportunityAmount,currency)}</b><small>{analytics.summary.found} найдено · {analytics.summary.searchConversion}% взято</small></div></article>
   <article><BriefcaseBusiness/><div><span>Деньги в работе</span><b>{money(analytics.summary.activeRevenue,currency)}</b><small>{analytics.summary.activeWorks} активных проектов</small></div></article>
   <article><CircleDollarSign/><div><span>Ожидаемая чистая прибыль</span><b>{money(analytics.summary.netProfit,currency)}</b><small>взвешенный прогноз {money(analytics.summary.weightedProfit,currency)}</small></div></article>
   <article><TrendingUp/><div><span>Конверсия побед</span><b>{pct(analytics.summary.winRate)}</b><small>{analytics.summary.won} выиграно · {analytics.summary.lost} проиграно</small></div></article>
   <article className={analytics.summary.overdue?'danger-card':''}><AlertTriangle/><div><span>Критические просрочки</span><b>{analytics.summary.overdue}</b><small>{analytics.risks.length} проектов требуют внимания</small></div></article>
  </section>
  <div className="director-tabs"><button className={tab==='overview'?'active':''} onClick={()=>setTab('overview')}>Обзор бизнеса</button><button className={tab==='team'?'active':''} onClick={()=>setTab('team')}>Команда</button><button className={tab==='sources'?'active':''} onClick={()=>setTab('sources')}>Площадки</button><button className={tab==='risks'?'active':''} onClick={()=>setTab('risks')}>Риски <span>{analytics.risks.length}</span></button></div>
  {tab==='overview'&&<div className="director-overview">
   <section className="director-card pipeline-card"><div className="director-card-head"><div><span>Сквозная воронка</span><h2>От найденной возможности до исполнения</h2></div><BarChart3/></div><div className="business-pipeline">{analytics.pipeline.map(item=><button key={item.label}><div><b>{item.label}</b><span>{item.count} объектов</span></div><div className="pipeline-track"><i style={{width:width(item.amount,maxPipeline)}}/></div><strong>{money(item.amount,currency)}</strong></button>)}</div></section>
   <section className="director-card forecast-card"><div className="director-card-head"><div><span>Прогноз</span><h2>Что компания может получить</h2></div><TrendingUp/></div><div className="forecast-grid"><div><span>Текущая выручка в работе</span><b>{money(analytics.summary.activeRevenue,currency)}</b></div><div><span>Взвешенная выручка</span><b>{money(analytics.summary.weightedRevenue,currency)}</b></div><div><span>Валовая прибыль</span><b>{money(analytics.summary.grossProfit,currency)}</b></div><div><span>Чистая прибыль</span><b>{money(analytics.summary.netProfit,currency)}</b></div></div></section>
   <section className="director-card refusal-card"><div className="director-card-head"><div><span>Потерянные возможности</span><h2>Почему менеджеры отказываются</h2></div><Target/></div>{analytics.refusalReasons.length?analytics.refusalReasons.map(item=><div className="refusal-row" key={item.reason}><span>{item.reason}</span><b>{item.count}</b></div>):<p>Отказов пока нет.</p>}</section>
   <section className="director-card critical-card"><div className="director-card-head"><div><span>Требует решения директора</span><h2>Самые опасные проекты</h2></div><AlertTriangle/></div>{analytics.risks.slice(0,5).map(item=><button key={item.id} onClick={()=>onOpenWork(item.id)}><div><b>{item.customer}</b><span>{item.code} · {item.manager}</span></div><em>{item.reason}</em><strong>{money(item.netProfit,currency)} <ArrowRight/></strong></button>)}{!analytics.risks.length&&<p>Критических рисков нет.</p>}</section>
  </div>}
  {tab==='team'&&<section className="director-card wide-card"><div className="director-card-head"><div><span>Эффективность сотрудников</span><h2>От поиска до прибыли</h2></div><Users/></div><div className="director-table"><div className="director-row director-row-head"><span>Сотрудник</span><span>Найдено</span><span>Взято</span><span>Конверсия</span><span>Проектов</span><span>Риски</span><span>Выручка</span><span>Чистая прибыль</span></div>{analytics.managers.map(item=><div className="director-row" key={item.name}><span><b>{item.name}</b></span><span>{item.found}</span><span>{item.accepted}</span><span>{pct(item.conversion)}</span><span>{item.active}</span><span className={item.risks?'bad':''}>{item.risks}</span><span>{money(item.revenue,currency)}</span><span><b>{money(item.netProfit,currency)}</b></span></div>)}</div></section>}
  {tab==='sources'&&<section className="director-card wide-card"><div className="director-card-head"><div><span>Эффективность источников</span><h2>Какие площадки приносят деньги</h2></div><Building2/></div><div className="director-table platform-table"><div className="director-row director-row-head"><span>Площадка</span><span>Проверок</span><span>Просмотрено</span><span>Найдено</span><span>Взято</span><span>Конверсия</span><span>Выручка</span><span>Прибыль</span></div>{analytics.platforms.map(item=><div className="director-row" key={item.id}><span><b>{item.name}</b></span><span>{item.checks}</span><span>{item.reviewed}</span><span>{item.found}</span><span>{item.accepted}</span><span>{pct(item.conversion)}</span><span>{money(item.revenue,currency)}</span><span><b>{money(item.profit,currency)}</b></span></div>)}</div></section>}
  {tab==='risks'&&<section className="director-card wide-card"><div className="risk-toolbar"><div><span>Оперативный контроль</span><h2>Проекты, где компания теряет время или деньги</h2></div><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Заказчик, проект или менеджер"/></label></div><div className="director-table risk-table"><div className="director-row director-row-head"><span>Проект</span><span>Менеджер</span><span>Дедлайн</span><span>Проблема</span><span>Чистая прибыль</span><span></span></div>{filteredRisks.map(item=><button className="director-row" key={item.id} onClick={()=>onOpenWork(item.id)}><span><b>{item.customer}</b><small>{item.code} · {item.title}</small></span><span>{item.manager}</span><span className={item.days<0?'bad':''}>{item.deadline||'—'}</span><span>{item.reason}</span><span><b>{money(item.netProfit,currency)}</b></span><span><ArrowRight/></span></button>)}</div></section>}
 </main>;
}
