import React,{useMemo,useRef,useState}from'react';
import{AlertTriangle,Download,File,FileCheck2,FileSpreadsheet,FileText,Image,Paperclip,Search,Trash2,UploadCloud}from'lucide-react';
import{deleteServerFile,downloadServerFile,uploadServerFiles}from'../api/client.js';
import{uid}from'../domain/workspace.js';
import{addDocumentsCommand,deleteDocumentCommand}from'../domain/commands.js';
import{downloadStoredAttachment,persistAttachmentEntries,removeStoredAttachment}from'../domain/attachmentStore.js';
import'./documents.css';

const TYPES=['ТЗ','Спецификация','ТКП','Опросный лист','Паспорт','Сертификат','КП','Договор','Счет','Отгрузочные документы','Прочее'];
const requirementsFor=state=>{const result=['ТЗ','Спецификация'];if(['КП готовится','КП отправлено','Переговоры','Договор','Производство','Отгрузка','Закрыто успешно'].includes(state))result.push('КП');if(['Договор','Производство','Отгрузка','Закрыто успешно'].includes(state))result.push('Договор');if(['Производство','Отгрузка','Закрыто успешно'].includes(state))result.push('Счет');return result};
const formatSize=size=>{if(!size)return'—';if(size<1024)return`${size} Б`;if(size<1048576)return`${(size/1024).toFixed(1)} КБ`;return`${(size/1048576).toFixed(1)} МБ`};
const iconFor=name=>{const ext=(name.split('.').pop()||'').toLowerCase();if(['xlsx','xls','csv'].includes(ext))return<FileSpreadsheet/>;if(['png','jpg','jpeg','webp'].includes(ext))return<Image/>;if(['pdf','doc','docx','txt'].includes(ext))return<FileText/>;return<File/>};

export function DocumentsView({work,data,setData,currentUser}){
 const readOnly=currentUser?.role==='director',serverManaged=data.meta?.serverManaged===true;
 const inputRef=useRef(null),[query,setQuery]=useState(''),[type,setType]=useState('Все типы'),[target,setTarget]=useState('work'),[selectedType,setSelectedType]=useState('ТЗ'),[required,setRequired]=useState(false),[dragging,setDragging]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const docs=(data.documents||[]).filter(document=>document.workId===work.id),requiredTypes=requirementsFor(work.state),missingRequired=requiredTypes.filter(item=>!docs.some(document=>document.type===item));
 const filtered=useMemo(()=>docs.filter(document=>{const hay=`${document.name} ${document.type}`.toLowerCase();return(!query||hay.includes(query.toLowerCase()))&&(type==='Все типы'||document.type===type)}),[docs,query,type]);
 const addFiles=async files=>{if(readOnly||busy)return;const list=[...files];if(!list.length)return;setBusy(true);setError('');try{let stored;if(serverManaged){const response=await uploadServerFiles(list,'work',work.id);stored=(response.files||[]).map(file=>({name:file.original_name,size:Number(file.size_bytes||0),type:file.mime_type||'',serverFileId:file.id,storedOnServer:true,addedAt:file.created_at}))}else stored=await persistAttachmentEntries(list);const positionId=target==='work'?null:target,additions=stored.map(file=>({id:uid(),workId:work.id,positionId,type:selectedType,name:file.name,size:file.size,mime:file.type||'',uploadedAt:file.addedAt||new Date().toISOString(),required:required||requiredTypes.includes(selectedType),storageKey:file.storageKey||'',storedLocally:file.storedLocally,serverFileId:file.serverFileId||'',storedOnServer:file.storedOnServer===true,source:'deal-upload'}));setData(current=>addDocumentsCommand(current,work.id,additions,currentUser));const failed=stored.filter(item=>!serverManaged&&!item.storedLocally).length;setError(failed?`${failed} файл(а) добавлены как карточки, но не сохранились локально.`:'')}catch(exception){setError(exception?.message||'Не удалось добавить документы')}finally{setBusy(false);if(inputRef.current)inputRef.current.value=''}};
 const download=async document=>{try{if(document.serverFileId)await downloadServerFile(document.serverFileId,document.name);else await downloadStoredAttachment(document);setError('')}catch(exception){setError(exception?.message||'Не удалось открыть файл')}};
 const remove=async document=>{if(readOnly||!window.confirm(`Удалить документ «${document.name}» из сделки?`))return;try{if(document.source!=='tender-capture'){if(document.serverFileId)await deleteServerFile(document.serverFileId);else await removeStoredAttachment(document)}setData(current=>deleteDocumentCommand(current,document.id,currentUser));setError(document.source==='tender-capture'?'Карточка удалена из сделки. Исходный файл тендера сохранён.':'')}catch(exception){setError(exception?.message||'Не удалось удалить документ. Карточка сохранена.')}};
 return <section className="documents-view">
  {error&&<div className="inline-error">{error}</div>}
  {readOnly&&<div className="readonly-note">Режим директора: документы доступны для просмотра и скачивания. Загрузку и удаление выполняет менеджер сделки.</div>}
  <div className="documents-summary"><div><span>Документы</span><b>{docs.length}</b></div><div><span>Обязательных не хватает</span><b className={missingRequired.length?'bad':'good'}>{missingRequired.length}</b></div><div><span>{serverManaged?'На сервере':'Хранятся локально'}</span><b>{docs.filter(document=>document.serverFileId||document.storageKey&&document.storedLocally!==false).length}</b></div></div>
  {missingRequired.length>0&&<div className="documents-alert"><AlertTriangle/><div><b>Для этапа «{work.state}» не хватает документов</b><p>{missingRequired.join(', ')}</p></div></div>}
  {!readOnly&&<><div className="documents-controls"><label><span>Тип</span><select value={selectedType} onChange={event=>setSelectedType(event.target.value)}>{TYPES.map(item=><option key={item}>{item}</option>)}</select></label><label><span>Привязка</span><select value={target} onChange={event=>setTarget(event.target.value)}><option value="work">Вся сделка</option>{work.positions.map(position=><option key={position.id} value={position.id}>Позиция №{position.rowNo}: {position.name}</option>)}</select></label><label className="required-check"><input type="checkbox" checked={required} onChange={event=>setRequired(event.target.checked)}/><span>Обязательный дополнительно</span></label></div><div className={`drop-zone ${dragging?'dragging':''} ${busy?'busy':''}`} onDragOver={event=>{event.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={event=>{event.preventDefault();setDragging(false);addFiles(event.dataTransfer.files)}} onClick={()=>!busy&&inputRef.current?.click()}><UploadCloud/><b>{busy?'Загружаю файлы…':'Перетащите документы сюда'}</b><span>или нажмите для выбора файлов</span><small>{serverManaged?'Файлы сохраняются на сервере и доступны сотрудникам компании.':'Файлы хранятся локально в браузере на этом Windows-компьютере.'}</small><input ref={inputRef} type="file" multiple hidden onChange={event=>addFiles(event.target.files)}/></div></>}
  <div className="document-toolbar"><label className="document-search"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Поиск по названию"/></label><select value={type} onChange={event=>setType(event.target.value)}><option>Все типы</option>{TYPES.map(item=><option key={item}>{item}</option>)}</select></div>
  <div className="documents-list">{filtered.length?filtered.map(document=>{const position=work.positions.find(item=>item.id===document.positionId),available=!!document.serverFileId||!!document.storageKey&&document.storedLocally!==false;return <article className="document-card" key={document.id}><div className="document-icon">{iconFor(document.name)}</div><div className="document-main"><div className="document-title"><b>{document.name}</b>{document.required&&<span><FileCheck2/>обязательный</span>}{document.source==='tender-capture'&&<span className="source-badge">из тендера</span>}</div><p>{document.type} · {formatSize(document.size)} · {new Date(document.uploadedAt).toLocaleString('ru-RU')}</p><small>{position?`Позиция №${position.rowNo}: ${position.name}`:document.serverFileId?'Вся сделка · серверное хранилище':available?'Вся сделка · файл доступен на этом компьютере':'Вся сделка · доступна только карточка файла'}</small></div><div className="document-actions">{available&&<button className="document-download" title="Скачать файл" onClick={()=>download(document)}><Download/></button>}{!readOnly&&<button className="document-delete" title="Удалить документ" onClick={()=>remove(document)}><Trash2/></button>}</div></article>}):<div className="documents-empty"><Paperclip/><b>Документы не найдены</b><span>{readOnly?'В сделке пока нет документов.':'Добавьте первый файл или измените фильтр.'}</span></div>}</div>
 </section>;
}
