import React,{useMemo,useState}from'react';
import{AlertTriangle,ArrowRight,CheckCircle2,Clock3,MapPin,Plus,Trash2,Truck}from'lucide-react';
import{daysLeft,todayPlus}from'../domain/workspace.js';
import{createShipment,deleteShipment,SHIPMENT_STATUSES,updateShipment}from'../domain/logistics.js';
import'./logistics.css';

const deliveryText=value=>{const days=daysLeft(value);if(days===999)return'Срок не указан';if(days<0)return`Просрочено ${Math.abs(days)} дн.`;if(days===0)return'Сегодня';if(days===1)return'Завтра';return`Через ${days} дн.`};
const statusClass=status=>status==='Доставлена'?'delivered':status==='Проблема'?'problem':status==='В пути'?'transit':'planned';

export function LogisticsView({work,data,setData,currentUser,onSelectPosition}){
 const readOnly=currentUser?.role==='director',shipments=useMemo(()=>(data.shipments||[]).filter(item=>item.workId===work.id).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))),[data.shipments,work.id]),readyBatches=work.positions.flatMap(position=>(position.batches||[]).filter(batch=>batch.status==='Готово'&&!(data.shipments||[]).some(item=>item.batchId===batch.id)).map(batch=>({position,batch})));
 const[batchId,setBatchId]=useState(''),[carrier,setCarrier]=useState(''),[vehicle,setVehicle]=useState(''),[tracking,setTracking]=useState(''),[destination,setDestination]=useState(''),[shipDate,setShipDate]=useState(new Date().toISOString().slice(0,10)),[plannedDeliveryDate,setPlannedDeliveryDate]=useState(todayPlus(7)),[note,setNote]=useState(''),[message,setMessage]=useState('');
 const inTransit=shipments.filter(item=>item.status==='В пути').length,delivered=shipments.filter(item=>item.status==='Доставлена').length,problems=shipments.filter(item=>item.status==='Проблема').length,overdue=shipments.filter(item=>item.status!=='Доставлена'&&daysLeft(item.plannedDeliveryDate)<0).length;
 const create=()=>{if(readOnly)return;try{let shipment;setData(current=>{const result=createShipment(current,{batchId,carrier,vehicle,tracking,destination,shipDate,plannedDeliveryDate,note},currentUser);shipment=result.shipment;return result.state});setBatchId('');setCarrier('');setVehicle('');setTracking('');setDestination('');setShipDate(new Date().toISOString().slice(0,10));setPlannedDeliveryDate(todayPlus(7));setNote('');setMessage(`Отправка создана: ${shipment?.carrier||''}`)}catch(error){setMessage(error?.message||'Не удалось создать отправку')}};
 const update=(shipment,changes)=>{if(readOnly)return;try{setData(current=>updateShipment(current,shipment.id,changes,currentUser));setMessage('Доставка обновлена')}catch(error){setMessage(error?.message||'Не удалось обновить доставку')}};
 const remove=shipment=>{if(readOnly||!window.confirm('Отменить отправку и вернуть партию в статус «Готово»?'))return;try{setData(current=>deleteShipment(current,shipment.id,currentUser));setMessage('Отправка отменена')}catch(error){setMessage(error?.message||'Не удалось отменить отправку')}};
 return <section className="logistics-view">
  {readOnly&&<div className="readonly-note">Режим директора: доставка доступна для контроля. Отправки и статусы изменяет менеджер.</div>}
  {message&&<div className="logistics-message">{message}</div>}
  <section className="logistics-summary"><article><Truck/><div><span>Готово к отгрузке</span><b>{readyBatches.length}</b></div></article><article><Clock3/><div><span>В пути</span><b>{inTransit}</b></div></article><article><CheckCircle2/><div><span>Доставлено</span><b>{delivered}</b></div></article><article className={problems||overdue?'danger':''}><AlertTriangle/><div><span>Проблемы / просрочки</span><b>{problems+overdue}</b></div></article></section>
  {!readOnly&&<section className="logistics-create"><header><div><span>Новая отправка</span><h2>Передать готовую партию в доставку</h2><p>После создания партия будет отмечена как отгруженная, а сделка перейдёт под контроль доставки.</p></div><Truck/></header><div className="logistics-form"><label className="shipment-batch"><span>Готовая партия</span><select value={batchId} onChange={event=>setBatchId(event.target.value)}><option value="">Выберите партию</option>{readyBatches.map(({position,batch})=><option key={batch.id} value={batch.id}>№{position.rowNo} · {position.name} · {batch.qty} {position.unit}</option>)}</select></label><label><span>Перевозчик / способ</span><input value={carrier} onChange={event=>setCarrier(event.target.value)} placeholder="Деловые линии / собственная машина"/></label><label><span>Машина</span><input value={vehicle} onChange={event=>setVehicle(event.target.value)} placeholder="А123ВС 77"/></label><label><span>Трек-номер</span><input value={tracking} onChange={event=>setTracking(event.target.value)} placeholder="Необязательно"/></label><label><span>Дата отгрузки</span><input type="date" value={shipDate} onChange={event=>setShipDate(event.target.value)}/></label><label><span>План доставки</span><input type="date" value={plannedDeliveryDate} onChange={event=>setPlannedDeliveryDate(event.target.value)}/></label><label className="shipment-destination"><span>Куда доставить</span><input value={destination} onChange={event=>setDestination(event.target.value)} placeholder="Адрес или склад заказчика"/></label><label className="shipment-note"><span>Комментарий</span><input value={note} onChange={event=>setNote(event.target.value)} placeholder="Контакт получателя, окно приёмки"/></label><button className="primary" disabled={!batchId||!carrier} onClick={create}><Plus/>Создать отправку</button></div></section>}
  <section className="logistics-register"><header><div><span>Контроль доставки</span><h2>Отправки по сделке</h2></div><b>{shipments.length}</b></header>{shipments.length?<div className="shipment-list">{shipments.map(shipment=>{const position=work.positions.find(item=>item.id===shipment.positionId),overdueRow=shipment.status!=='Доставлена'&&daysLeft(shipment.plannedDeliveryDate)<0;return <article key={shipment.id} className={`${statusClass(shipment.status)} ${overdueRow?'overdue':''}`}><div className="shipment-route"><div className="shipment-icon"><Truck/></div><div><span>{shipment.status}</span><h3>{position?`№${position.rowNo} · ${position.name}`:'Позиция'}</h3><p>{shipment.qty} {position?.unit||''} · {shipment.carrier}</p></div></div><div className="shipment-details"><div><MapPin/><span>{shipment.destination||'Адрес не указан'}</span></div><div><Clock3/><span className={overdueRow?'bad':''}>{deliveryText(shipment.plannedDeliveryDate)}</span></div><small>{shipment.tracking||shipment.vehicle||'Трек и машина не указаны'}</small></div><div className="shipment-control">{readOnly?<b className={`shipment-status ${statusClass(shipment.status)}`}>{shipment.status}</b>:<select className={`shipment-status ${statusClass(shipment.status)}`} value={shipment.status} onChange={event=>update(shipment,{status:event.target.value})}>{SHIPMENT_STATUSES.map(item=><option key={item}>{item}</option>)}</select>}{!readOnly&&<input type="date" title="Фактическая дата доставки" value={shipment.actualDeliveryDate||''} onChange={event=>update(shipment,{actualDeliveryDate:event.target.value,status:event.target.value?'Доставлена':shipment.status})}/>}<div><button title="Открыть позицию" onClick={()=>onSelectPosition?.(shipment.positionId)}><ArrowRight/></button>{!readOnly&&shipment.status!=='Доставлена'&&<button title="Отменить отправку" onClick={()=>remove(shipment)}><Trash2/></button>}</div></div></article>})}</div>:<div className="logistics-empty"><Truck/><b>Отправок пока нет</b><span>{readyBatches.length?'Выберите готовую партию и создайте отправку.':'Сначала отметьте производственную партию как готовую.'}</span></div>}</section>
 </section>;
}
