import React,{useMemo,useState}from'react';
import{ExternalLink,Plus,Search,Trash2}from'lucide-react';
import{uid}from'../domain/workspace.js';
import{acceptOpportunity,deleteOpportunities,OPPORTUNITY_STATUSES}from'../domain/opportunities.js';

const n=v=>Math.max(0,Number(v||0));
const blankLine=()=>({id:uid(),name:'',description:'',quantity:1,supplier1:'',supplier1Location:'',leadTime1:'',supplier2:'',supplier2Location:'',leadTime2:'',purchaseUnit:0,saleUnit:0,transportIncluded:0,transportSeparate:0,transportQty:1});
const blankTender=user=>({id:uid(),externalId:'',customer:'',title:'',sourceUrl:'',platformId:'',owner:user?.name||'',status:'Новая',createdAt:new Date().toISOString(),deadline:'',processBy:'',requestType:'Тендер',plannedSuppliers:'',proposalSentAt:'',customerPaymentTerms:'',deliveryTerm:'',contractDate:'',notes:'',tenderLines:[],captureMethod:'manual',captureIncomplete:true,attachments:[],createdBy:user?.id||null});
const calc=line=>{const qty=n(line.quantity),purchase=n(line.purchaseUnit)*qty+n(line.transportIncluded)+n(line.transportSeparate)*Math.max(1,n(line.transportQty)),sale=n(line.saleUnit)*qty,profit=sale-purchase;return{purchase,sale,profit,markup:purchase?profit/purchase*100:0}};

export function ManagerTenderWorkspace({data,setData,currentUser,onOpenWork}){
 const[query,setQuery]=useState(''),[status,setStatus]=useState('Все'),[selectedId,setSelectedId]=useState(()=>data.opportunities?.[0]?.id||''),[error,setError]=useState('');
 const rows=useMemo(()=>(data.opportunities||[]).filter(item=>(status==='Все'||item.status===status)&&`${item.customer} ${item.title} ${item.externalId} ${item.sourceUrl}`.toLowerCase().includes(query.toLowerCase())),[data.opportunities,query,status]);
 const selected=(data.opportunities||[]).find(item=>item.id===selectedId)||rows[0]||null;
 const save=(id,patch)=>{setData(current=>({...current,opportunities:(current.opportunities||[]).map(item=>item.id===id?{...item,...patch,captureIncomplete:!(patch.customer??item.customer)||!(patch.title??item.title)||!(patch.deadline??item.deadline),updatedAt:new Date().toISOString(),updatedBy:currentUser?.id||null}:item)}));setError('')};
 const addTender=()=>{const item=blankTender(currentUser);setData(current=>({...current,opportunities:[item,...(current.opportunities||[])]}));setSelectedId(item.id)};
 const removeTender=item=>{if(item.workId)return setError('Заявка уже связана со сделкой.');if(!window.confirm('Удалить эту заявку?'))return;try{setData(current=>deleteOpportunities(current,[item.id],currentUser));setSelectedId('');setError('')}catch(e){setError(e?.message||'Не удалось удалить')}};
 const addLine=()=>save(selected.id,{tenderLines:[...(selected.tenderLines||[]),blankLine()]});
 const updateLine=(id,key,value)=>save(selected.id,{tenderLines:(selected.tenderLines||[]).map(line=>line.id===id?{...line,[key]:['quantity','purchaseUnit','saleUnit','transportIncluded','transportSeparate','transportQty'].includes(key)?n(value):value}:line)});
 const removeLine=id=>save(selected.id,{tenderLines:(selected.tenderLines||[]).filter(line=>line.id!==id)});
 const convert=()=>{if(!selected.customer||!selected.title||!selected.deadline)return setError('Заполните заказчика, предмет и срок подачи.');try{let work;setData(current=>{const r=acceptOpportunity(current,selected.id,currentUser);work=r.work;return r.state});if(work)onOpenWork(work.id,'overview')}catch(e){setError(e?.message||'Не удалось создать сделку')}};
 const totals=(selected?.tenderLines||[]).reduce((s,line)=>{const c=calc(line);return{purchase:s.purchase+c.purchase,sale:s.sale+c.sale,profit:s.profit+c.profit}},{purchase:0,sale:0,profit:0});
 return <main className="manager-request-shell">
  <aside className="manager-request-list">
   <header><div><h1>Заявки</h1><span>{rows.length}</span></div><button onClick={addTender}><Plus/>Новая</button></header>
   <label className="request-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск"/></label>
   <select className="request-filter" value={status} onChange={e=>setStatus(e.target.value)}><option>Все</option>{OPPORTUNITY_STATUSES.map(v=><option key={v}>{v}</option>)}</select>
   <div className="request-cards">{rows.map(item=><button key={item.id} className={selected?.id===item.id?'active':''} onClick={()=>setSelectedId(item.id)}><strong>{item.customer||'Новая заявка'}</strong><span>{item.title||'Предмет не указан'}</span><small>{item.externalId||'Без номера'} · {item.deadline||'Без срока'}</small><em>{item.status||'Новая'}</em></button>)}{!rows.length&&<p>Заявок нет</p>}</div>
  </aside>
  <section className="manager-request-card">
   {!selected?<div className="request-empty"><h2>Создайте первую заявку</h2><button onClick={addTender}><Plus/>Новая заявка</button></div>:<>
    <header className="request-card-head"><div><h2>{selected.customer||'Новая заявка'}</h2><p>{selected.title||'Заполняйте данные по ходу поиска тендера'}</p></div><div>{selected.sourceUrl&&<a href={selected.sourceUrl} target="_blank" rel="noreferrer"><ExternalLink/>Открыть</a>}{selected.workId?<button onClick={()=>onOpenWork(selected.workId)}>Сделка</button>:<button className="primary" onClick={convert}>В работу</button>}<button className="danger" onClick={()=>removeTender(selected)} disabled={!!selected.workId}><Trash2/></button></div></header>
    {error&&<div className="request-error">{error}<button onClick={()=>setError('')}>×</button></div>}
    <section className="request-fields">
     <label>Заявка №<input value={selected.externalId||''} onChange={e=>save(selected.id,{externalId:e.target.value})}/></label><label>Дата<input type="date" value={String(selected.createdAt||'').slice(0,10)} onChange={e=>save(selected.id,{createdAt:e.target.value})}/></label><label>Обработать до<input type="date" value={selected.processBy||''} onChange={e=>save(selected.id,{processBy:e.target.value})}/></label><label>Срок подачи<input type="date" value={selected.deadline||''} onChange={e=>save(selected.id,{deadline:e.target.value})}/></label>
     <label className="span2">Заказчик<input value={selected.customer||''} onChange={e=>save(selected.id,{customer:e.target.value})}/></label><label className="span2">Предмет закупки<input value={selected.title||''} onChange={e=>save(selected.id,{title:e.target.value})}/></label>
     <label>Менеджер<input value={selected.owner||''} onChange={e=>save(selected.id,{owner:e.target.value})}/></label><label>Характер заявки<select value={selected.requestType||'Тендер'} onChange={e=>save(selected.id,{requestType:e.target.value})}><option>Тендер</option><option>Текущая потребность</option><option>Запрос цены</option><option>Другое</option></select></label><label>Статус<select value={selected.status||'Новая'} onChange={e=>save(selected.id,{status:e.target.value})}>{OPPORTUNITY_STATUSES.filter(v=>v!=='Взята в работу'||selected.workId).map(v=><option key={v}>{v}</option>)}</select></label><label>Площадка<select value={selected.platformId||''} onChange={e=>save(selected.id,{platformId:e.target.value})}><option value="">Не указана</option>{(data.platforms||[]).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
     <label className="span4">Ссылка<input value={selected.sourceUrl||''} onChange={e=>save(selected.id,{sourceUrl:e.target.value})} placeholder="https://"/></label><label className="span2">Поставщики (план)<input value={selected.plannedSuppliers||''} onChange={e=>save(selected.id,{plannedSuppliers:e.target.value})}/></label><label>Дата отправки ТКП<input type="date" value={selected.proposalSentAt||''} onChange={e=>save(selected.id,{proposalSentAt:e.target.value})}/></label><label>Дата договора<input type="date" value={selected.contractDate||''} onChange={e=>save(selected.id,{contractDate:e.target.value})}/></label>
     <label className="span2">Условия оплаты заказчика<input value={selected.customerPaymentTerms||''} onChange={e=>save(selected.id,{customerPaymentTerms:e.target.value})}/></label><label className="span2">Срок поставки на объект<input value={selected.deliveryTerm||''} onChange={e=>save(selected.id,{deliveryTerm:e.target.value})}/></label><label className="span4">Комментарий<textarea value={selected.notes||''} onChange={e=>save(selected.id,{notes:e.target.value})}/></label>
    </section>
    <section className="request-lines"><header><div><h3>Позиции</h3><span>Закупка, продажа, транспорт, прибыль</span></div><button onClick={addLine}><Plus/>Добавить позицию</button></header><div className="request-lines-scroll"><table><thead><tr><th>№</th><th>Наименование / описание</th><th>Кол-во</th><th>Поставщик №1 / место</th><th>Срок №1</th><th>Поставщик №2 / место</th><th>Срок №2</th><th>Закупка</th><th>Продажа</th><th>Транспорт входит</th><th>Транспорт отдельно</th><th>Прибыль</th><th>Наценка</th><th></th></tr></thead><tbody>{(selected.tenderLines||[]).map((line,i)=>{const c=calc(line);return <tr key={line.id}><td>{i+1}</td><td><input value={line.name||''} onChange={e=>updateLine(line.id,'name',e.target.value)} placeholder="Наименование"/><textarea value={line.description||''} onChange={e=>updateLine(line.id,'description',e.target.value)} placeholder="Краткое описание товара"/></td><td><input type="number" value={line.quantity||0} onChange={e=>updateLine(line.id,'quantity',e.target.value)}/></td><td><input value={line.supplier1||''} onChange={e=>updateLine(line.id,'supplier1',e.target.value)} placeholder="Поставщик"/><input value={line.supplier1Location||''} onChange={e=>updateLine(line.id,'supplier1Location',e.target.value)} placeholder="Город / км"/></td><td><input value={line.leadTime1||''} onChange={e=>updateLine(line.id,'leadTime1',e.target.value)}/></td><td><input value={line.supplier2||''} onChange={e=>updateLine(line.id,'supplier2',e.target.value)} placeholder="Поставщик"/><input value={line.supplier2Location||''} onChange={e=>updateLine(line.id,'supplier2Location',e.target.value)} placeholder="Город / км"/></td><td><input value={line.leadTime2||''} onChange={e=>updateLine(line.id,'leadTime2',e.target.value)}/></td><td><input type="number" value={line.purchaseUnit||0} onChange={e=>updateLine(line.id,'purchaseUnit',e.target.value)}/></td><td><input type="number" value={line.saleUnit||0} onChange={e=>updateLine(line.id,'saleUnit',e.target.value)}/></td><td><input type="number" value={line.transportIncluded||0} onChange={e=>updateLine(line.id,'transportIncluded',e.target.value)}/></td><td><input type="number" value={line.transportSeparate||0} onChange={e=>updateLine(line.id,'transportSeparate',e.target.value)}/></td><td><b>{Math.round(c.profit).toLocaleString('ru-RU')}</b></td><td><b>{c.markup.toFixed(1)}%</b></td><td><button onClick={()=>removeLine(line.id)}><Trash2/></button></td></tr>})}</tbody></table>{!(selected.tenderLines||[]).length&&<p className="request-lines-empty">Добавьте первую позицию</p>}</div><footer><span>Закупка <b>{Math.round(totals.purchase).toLocaleString('ru-RU')}</b></span><span>Продажа <b>{Math.round(totals.sale).toLocaleString('ru-RU')}</b></span><span>Прибыль <b>{Math.round(totals.profit).toLocaleString('ru-RU')}</b></span></footer></section>
   </>}
  </section>
 </main>;
}