import React,{useMemo,useState}from'react';
import{ArrowLeft,ExternalLink,Plus,Search,Trash2}from'lucide-react';
import{uid}from'../domain/workspace.js';
import{acceptOpportunity,deleteOpportunities,OPPORTUNITY_STATUSES}from'../domain/opportunities.js';

const blankLine=()=>({id:uid(),name:'',description:'',quantity:1,supplier1:'',supplier1Location:'',leadTime1:'',supplier2:'',supplier2Location:'',leadTime2:'',purchaseUnit:0,saleUnit:0,transportIncluded:0,transportSeparate:0,transportQty:0,comment:''});
const blankTender=actor=>({id:uid(),externalId:'',customer:'',title:'',sourceUrl:'',platformId:'',owner:actor?.name||'',status:'Новая',createdAt:new Date().toISOString(),deadline:'',processBy:'',requestType:'Тендер',plannedSuppliers:'',proposalSentAt:'',customerPaymentTerms:'',deliveryTerm:'',contractDate:'',notes:'',estimatedAmount:0,tenderLines:[],captureMethod:'manual',captureIncomplete:true,attachments:[],createdBy:actor?.id||null});
const number=value=>Math.max(0,Number(value||0));
const lineTotals=line=>{const qty=number(line.quantity),purchase=number(line.purchaseUnit)*qty+number(line.transportIncluded)+number(line.transportSeparate)*Math.max(1,number(line.transportQty)||1),sale=number(line.saleUnit)*qty,profit=sale-purchase;return{purchase,sale,profit,profitAfterTax:profit*2/3,markup:purchase?profit/purchase*100:0}};

export function ManagerTenderWorkspace({data,setData,currentUser,onOpenWork}){
 const[query,setQuery]=useState(''),[statusFilter,setStatusFilter]=useState('Все'),[selectedId,setSelectedId]=useState(''),[error,setError]=useState('');
 const tenders=useMemo(()=>(data.opportunities||[]).filter(item=>(statusFilter==='Все'||item.status===statusFilter)&&`${item.customer} ${item.title} ${item.externalId} ${item.sourceUrl}`.toLowerCase().includes(query.toLowerCase())),[data.opportunities,query,statusFilter]);
 const selected=(data.opportunities||[]).find(item=>item.id===selectedId)||null;
 const platformMap=useMemo(()=>new Map((data.platforms||[]).map(item=>[item.id,item])),[data.platforms]);
 const save=(id,patch)=>{setData(current=>({...current,opportunities:(current.opportunities||[]).map(item=>item.id===id?{...item,...patch,captureIncomplete:!(patch.customer??item.customer)||!(patch.title??item.title)||!(patch.deadline??item.deadline),updatedAt:new Date().toISOString(),updatedBy:currentUser?.id||null}:item)}));setError('')};
 const addTender=()=>{const tender=blankTender(currentUser);setData(current=>({...current,opportunities:[tender,...(current.opportunities||[])]}));setSelectedId(tender.id)};
 const removeTender=item=>{if(item.workId){setError('Этот тендер уже связан со сделкой и не может быть удалён отдельно.');return}if(!window.confirm(`Удалить тендер «${item.customer||item.title||'без названия'}»?`))return;try{setData(current=>deleteOpportunities(current,[item.id],currentUser));setSelectedId('');setError('')}catch(exception){setError(exception?.message||'Не удалось удалить тендер')}};
 const updateLine=(lineId,field,value)=>save(selected.id,{tenderLines:(selected.tenderLines||[]).map(line=>line.id===lineId?{...line,[field]:['quantity','purchaseUnit','saleUnit','transportIncluded','transportSeparate','transportQty'].includes(field)?number(value):value}:line)});
 const addLine=()=>save(selected.id,{tenderLines:[...(selected.tenderLines||[]),blankLine()]});
 const removeLine=lineId=>save(selected.id,{tenderLines:(selected.tenderLines||[]).filter(line=>line.id!==lineId)});
 const convert=()=>{if(!selected.customer||!selected.title||!selected.deadline){setError('Для перевода в работу заполните заказчика, предмет закупки и срок подачи.');return}try{let work;setData(current=>{const result=acceptOpportunity(current,selected.id,currentUser);work=result.work;return result.state});if(work)onOpenWork(work.id,'overview')}catch(exception){setError(exception?.message||'Не удалось создать сделку')}};
 const totals=(selected?.tenderLines||[]).reduce((sum,line)=>{const value=lineTotals(line);return{purchase:sum.purchase+value.purchase,sale:sum.sale+value.sale,profit:sum.profit+value.profit}}, {purchase:0,sale:0,profit:0});
 if(!selected)return <main className="tender-simple-page">
  <header className="tender-simple-head"><div><h1>Тендеры</h1><p>Добавляйте карточки по ходу поиска и заполняйте их вручную.</p></div><button className="primary" onClick={addTender}><Plus/>Новый тендер</button></header>
  {error&&<div className="tender-simple-error">{error}<button onClick={()=>setError('')}>×</button></div>}
  <section className="tender-simple-toolbar"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Заказчик, предмет, номер или ссылка"/></label><select value={statusFilter} onChange={event=>setStatusFilter(event.target.value)}><option>Все</option>{OPPORTUNITY_STATUSES.map(item=><option key={item}>{item}</option>)}</select><span>{tenders.length} карточек</span></section>
  <section className="tender-simple-list"><div className="tender-simple-row header"><span>Дата</span><span>Заказчик</span><span>Предмет</span><span>№ закупки</span><span>Срок</span><span>Статус</span><span></span></div>{tenders.map(item=><button className="tender-simple-row" key={item.id} onClick={()=>setSelectedId(item.id)}><span>{String(item.createdAt||'').slice(0,10)||'—'}</span><strong>{item.customer||'Заказчик не указан'}</strong><span>{item.title||'Предмет не указан'}</span><span>{item.externalId||'—'}</span><span>{item.deadline||'—'}</span><em>{item.status||'Новая'}</em><span>Открыть</span></button>)}{!tenders.length&&<div className="tender-simple-empty">Карточек пока нет. Нажмите «Новый тендер».</div>}</section>
 </main>;
 return <main className="tender-card-page">
  <header className="tender-card-head"><button className="back" onClick={()=>setSelectedId('')}><ArrowLeft/>К списку</button><div><h1>{selected.customer||'Новая карточка тендера'}</h1><p>{selected.title||'Заполните предмет закупки'}</p></div><div className="tender-card-actions">{selected.sourceUrl&&<a href={selected.sourceUrl} target="_blank" rel="noreferrer"><ExternalLink/>Оригинал</a>}{selected.workId?<button onClick={()=>onOpenWork(selected.workId)}>Открыть сделку</button>:<button className="primary" onClick={convert}>Взять в работу</button>}<button className="danger" onClick={()=>removeTender(selected)} disabled={!!selected.workId}><Trash2/></button></div></header>
  {error&&<div className="tender-simple-error">{error}<button onClick={()=>setError('')}>×</button></div>}
  <section className="tender-form-grid">
   <label>№ заявки / закупки<input value={selected.externalId||''} onChange={event=>save(selected.id,{externalId:event.target.value})}/></label>
   <label>Дата<input type="date" value={String(selected.createdAt||'').slice(0,10)} onChange={event=>save(selected.id,{createdAt:event.target.value})}/></label>
   <label>Обработать до<input type="date" value={selected.processBy||''} onChange={event=>save(selected.id,{processBy:event.target.value})}/></label>
   <label>Срок подачи<input type="date" value={selected.deadline||''} onChange={event=>save(selected.id,{deadline:event.target.value})}/></label>
   <label className="wide">Заказчик<input value={selected.customer||''} onChange={event=>save(selected.id,{customer:event.target.value})}/></label>
   <label className="wide">Предмет закупки<input value={selected.title||''} onChange={event=>save(selected.id,{title:event.target.value})}/></label>
   <label>Менеджер<input value={selected.owner||currentUser?.name||''} onChange={event=>save(selected.id,{owner:event.target.value})}/></label>
   <label>Характер заявки<select value={selected.requestType||'Тендер'} onChange={event=>save(selected.id,{requestType:event.target.value})}><option>Тендер</option><option>Текущая потребность</option><option>Запрос цены</option><option>Другое</option></select></label>
   <label>Статус<select value={selected.status||'Новая'} onChange={event=>save(selected.id,{status:event.target.value})}>{OPPORTUNITY_STATUSES.filter(item=>item!=='Взята в работу'||selected.workId).map(item=><option key={item}>{item}</option>)}</select></label>
   <label>Площадка<select value={selected.platformId||''} onChange={event=>save(selected.id,{platformId:event.target.value})}><option value="">Не указана</option>{(data.platforms||[]).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>
   <label className="full">Ссылка<input value={selected.sourceUrl||''} onChange={event=>save(selected.id,{sourceUrl:event.target.value})} placeholder="https://"/></label>
   <label className="wide">Поставщики — план<input value={selected.plannedSuppliers||''} onChange={event=>save(selected.id,{plannedSuppliers:event.target.value})} placeholder="Кому отправить запрос ТКП"/></label>
   <label>Дата отправки ТКП<input type="date" value={selected.proposalSentAt||''} onChange={event=>save(selected.id,{proposalSentAt:event.target.value})}/></label>
   <label className="wide">Условия оплаты заказчика<input value={selected.customerPaymentTerms||''} onChange={event=>save(selected.id,{customerPaymentTerms:event.target.value})}/></label>
   <label className="wide">Срок поставки на объект<input value={selected.deliveryTerm||''} onChange={event=>save(selected.id,{deliveryTerm:event.target.value})}/></label>
   <label>Дата договора<input type="date" value={selected.contractDate||''} onChange={event=>save(selected.id,{contractDate:event.target.value})}/></label>
   <label className="full">Комментарий<textarea value={selected.notes||''} onChange={event=>save(selected.id,{notes:event.target.value})}/></label>
  </section>
  <section className="tender-lines-block"><header><div><h2>Позиции</h2><p>Поля взяты из ваших рабочих Excel: товар, поставщики, сроки, закупка, продажа и транспорт.</p></div><button onClick={addLine}><Plus/>Добавить позицию</button></header>
   <div className="tender-lines-wrap"><table className="tender-lines"><thead><tr><th>№</th><th>Наименование и описание</th><th>Кол-во</th><th>Поставщик №1 / местоположение</th><th>Срок №1</th><th>Поставщик №2 / местоположение</th><th>Срок №2</th><th>Закупка за ед.</th><th>Продажа за ед.</th><th>Транспорт входит</th><th>Транспорт отдельно</th><th>Прибыль</th><th>Наценка</th><th></th></tr></thead><tbody>{(selected.tenderLines||[]).map((line,index)=>{const value=lineTotals(line);return <tr key={line.id}><td>{index+1}</td><td><input value={line.name||''} onChange={event=>updateLine(line.id,'name',event.target.value)} placeholder="Наименование"/><textarea value={line.description||''} onChange={event=>updateLine(line.id,'description',event.target.value)} placeholder="Характеристики, материал, давление, комплектация"/></td><td><input type="number" min="0" value={line.quantity||0} onChange={event=>updateLine(line.id,'quantity',event.target.value)}/></td><td><input value={line.supplier1||''} onChange={event=>updateLine(line.id,'supplier1',event.target.value)} placeholder="Поставщик"/><input value={line.supplier1Location||''} onChange={event=>updateLine(line.id,'supplier1Location',event.target.value)} placeholder="Город / расстояние"/></td><td><input value={line.leadTime1||''} onChange={event=>updateLine(line.id,'leadTime1',event.target.value)}/></td><td><input value={line.supplier2||''} onChange={event=>updateLine(line.id,'supplier2',event.target.value)} placeholder="Поставщик"/><input value={line.supplier2Location||''} onChange={event=>updateLine(line.id,'supplier2Location',event.target.value)} placeholder="Город / расстояние"/></td><td><input value={line.leadTime2||''} onChange={event=>updateLine(line.id,'leadTime2',event.target.value)}/></td><td><input type="number" min="0" value={line.purchaseUnit||0} onChange={event=>updateLine(line.id,'purchaseUnit',event.target.value)}/></td><td><input type="number" min="0" value={line.saleUnit||0} onChange={event=>updateLine(line.id,'saleUnit',event.target.value)}/></td><td><input type="number" min="0" value={line.transportIncluded||0} onChange={event=>updateLine(line.id,'transportIncluded',event.target.value)}/></td><td><input type="number" min="0" value={line.transportSeparate||0} onChange={event=>updateLine(line.id,'transportSeparate',event.target.value)}/></td><td><b>{Math.round(value.profit).toLocaleString('ru-RU')}</b></td><td><b>{value.markup.toFixed(1)}%</b></td><td><button onClick={()=>removeLine(line.id)}><Trash2/></button></td></tr>})}</tbody></table>{!(selected.tenderLines||[]).length&&<div className="tender-lines-empty">Позиции ещё не добавлены.</div>}</div>
   <footer><span>Закупка: <b>{Math.round(totals.purchase).toLocaleString('ru-RU')}</b></span><span>Продажа: <b>{Math.round(totals.sale).toLocaleString('ru-RU')}</b></span><span>Прибыль: <b>{Math.round(totals.profit).toLocaleString('ru-RU')}</b></span></footer>
  </section>
 </main>;
}
