import React,{useMemo,useState}from'react';
import{ArrowRight,Check,Clock3,ExternalLink,Filter,Plus,Search,Target,TrendingUp,X}from'lucide-react';
import{money}from'../domain/workspace.js';
import{REJECTION_REASONS,acceptOpportunity,createOpportunity,markPlatformChecked,opportunityAnalytics,rejectOpportunity,updateOpportunityQualification}from'../domain/opportunities.js';

const answerLabel=value=>value===true?'Да':value===false?'Нет':'—';
const statusClass=status=>status==='Взята в работу'?'accepted':status==='Отказ'?'rejected':status==='На оценке'?'review':'new';
const dateText=value=>value?new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'никогда';

export function OpportunityEngine({data,setData,currentUser,onOpenWork}){
 const[view,setView]=useState('route'),[selectedId,setSelectedId]=useState(data.opportunities?.[0]?.id||null),[query,setQuery]=useState(''),[status,setStatus]=useState('Все'),[showNew,setShowNew]=useState(false),[error,setError]=useState(''),[draft,setDraft]=useState({platformId:data.platforms?.[0]?.id||'',customer:'',title:'',externalId:'',estimatedAmount:'',deadline:'',owner:currentUser?.name||'',notes:''}),[rejectReason,setRejectReason]=useState(''),[rejectNote,setRejectNote]=useState('');
 const analytics=useMemo(()=>opportunityAnalytics(data),[data]),platformMap=useMemo(()=>new Map((data.platforms||[]).map(item=>[item.id,item])),[data.platforms]);
 const list=(data.opportunities||[]).filter(item=>(status==='Все'||item.status===status)&&`${item.customer} ${item.title} ${item.externalId} ${platformMap.get(item.platformId)?.name||''}`.toLowerCase().includes(query.toLowerCase()));
 const selected=(data.opportunities||[]).find(item=>item.id===selectedId)||list[0]||null;
 const run=operation=>{try{setData(current=>operation(current));setError('')}catch(exception){setError(exception?.message||'Не удалось выполнить действие')}};
 const add=()=>{try{let created;setData(current=>{const result=createOpportunity(current,draft,currentUser);created=result.opportunity;return result.state});setSelectedId(created.id);setShowNew(false);setView('opportunities');setDraft({platformId:data.platforms?.[0]?.id||'',customer:'',title:'',externalId:'',estimatedAmount:'',deadline:'',owner:currentUser?.name||'',notes:''});setError('')}catch(exception){setError(exception?.message||'Не удалось создать возможность')}};
 const qualify=(field,value)=>selected&&run(current=>updateOpportunityQualification(current,selected.id,{[field]:value},currentUser));
 const accept=()=>{if(!selected)return;try{let work;setData(current=>{const result=acceptOpportunity(current,selected.id,currentUser);work=result.work;return result.state});if(work)onOpenWork(work.id)}catch(exception){setError(exception?.message||'Не удалось взять возможность в работу')}};
 const reject=()=>{if(!selected)return;run(current=>rejectOpportunity(current,selected.id,rejectReason,rejectNote,currentUser));setRejectReason('');setRejectNote('')};
 return <main className="opportunity-page">
  <header className="opportunity-head"><div><span>Release 3 · полный цикл тендерных продаж</span><h1>Возможности</h1><p>Поиск площадок, экспресс-анализ и перевод перспективных закупок в проекты.</p></div><button className="primary" onClick={()=>setShowNew(true)}><Plus/>Новая возможность</button></header>
  {error&&<div className="inline-error">{error}</div>}
  <section className="opportunity-kpis"><article><Target/><div><span>Площадки сегодня</span><b>{analytics.checkedPlatforms}/{analytics.totalPlatforms}</b></div></article><article><Search/><div><span>Найдено</span><b>{analytics.total}</b></div></article><article><Clock3/><div><span>На оценке</span><b>{analytics.active}</b></div></article><article><Check/><div><span>Взято в работу</span><b>{analytics.accepted}</b></div></article><article><TrendingUp/><div><span>Конверсия</span><b>{analytics.conversion.toFixed(1)}%</b></div></article></section>
  <div className="opportunity-tabs"><button className={view==='route'?'active':''} onClick={()=>setView('route')}>Маршрут площадок</button><button className={view==='opportunities'?'active':''} onClick={()=>setView('opportunities')}>Найденные возможности <span>{analytics.total}</span></button><button className={view==='analytics'?'active':''} onClick={()=>setView('analytics')}>Аналитика поиска</button></div>
  {view==='route'&&<section className="platform-grid">{(data.platforms||[]).map(platform=><article key={platform.id} className={`platform-card ${platform.checkedToday?'done':''}`}><div className="platform-top"><div><span>{platform.frequency}</span><h3>{platform.name}</h3></div><b>{platform.newCount||0} новых</b></div><dl><div><dt>Ответственный</dt><dd>{platform.owner||'Не назначен'}</dd></div><div><dt>Последняя проверка</dt><dd>{dateText(platform.lastCheckedAt)}</dd></div><div><dt>Статус</dt><dd>{platform.status}</dd></div></dl><div className="platform-actions">{platform.url&&<a href={platform.url} target="_blank" rel="noreferrer">Открыть площадку <ExternalLink/></a>}<button disabled={platform.checkedToday} onClick={()=>run(current=>markPlatformChecked(current,platform.id,currentUser))}>{platform.checkedToday?<><Check/>Проверено</>:<>Отметить проверенной</>}</button></div></article>)}</section>}
  {view==='opportunities'&&<section className="opportunity-workspace"><div className="opportunity-register"><div className="opportunity-tools"><label><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Заказчик, закупка, номер или площадка"/></label><select value={status} onChange={event=>setStatus(event.target.value)}><option>Все</option><option>Новая</option><option>На оценке</option><option>Взята в работу</option><option>Отказ</option></select><Filter/></div><div className="opportunity-table"><div className="opp-row opp-header"><span>Заказчик / закупка</span><span>Площадка</span><span>Сумма</span><span>Дедлайн</span><span>Ответственный</span><span>Статус</span></div>{list.map(item=><button key={item.id} className={`opp-row ${selected?.id===item.id?'selected':''}`} onClick={()=>setSelectedId(item.id)}><span><b>{item.customer}</b><small>{item.title}{item.externalId?` · ${item.externalId}`:''}</small></span><span>{platformMap.get(item.platformId)?.name||'—'}</span><span>{money(item.estimatedAmount,data.settings?.currency||'RUB')}</span><span>{item.deadline||'—'}</span><span>{item.owner||'—'}</span><span><em className={`opp-status ${statusClass(item.status)}`}>{item.status}</em></span></button>)}{!list.length&&<div className="opportunity-empty">Ничего не найдено</div>}</div></div>
   <aside className="qualification-panel">{selected?<><div className="qualification-head"><span>Экспресс-анализ</span><h2>{selected.customer}</h2><p>{selected.title}</p></div><div className="qualification-summary"><div><span>Площадка</span><b>{platformMap.get(selected.platformId)?.name||'—'}</b></div><div><span>Сумма</span><b>{money(selected.estimatedAmount,data.settings?.currency||'RUB')}</b></div><div><span>Дедлайн</span><b>{selected.deadline||'—'}</b></div></div>{['profileFit','manufacturerAvailable','timeFeasible','commercialInterest'].map((field,index)=>{const labels=['Наш профиль','Есть производитель','Успеваем по сроку','Коммерчески интересно'];return <div className="qualification-question" key={field}><div><b>{labels[index]}</b><span>{answerLabel(selected[field])}</span></div><div><button className={selected[field]===true?'active yes':''} onClick={()=>qualify(field,true)}>Да</button><button className={selected[field]===false?'active no':''} onClick={()=>qualify(field,false)}>Нет</button></div></div>})}<label className="qualification-notes">Комментарий<textarea value={selected.notes||''} onChange={event=>qualify('notes',event.target.value)}/></label>{!['Взята в работу','Отказ'].includes(selected.status)&&<><button className="accept-opportunity" onClick={accept}><Check/>Взять в работу <ArrowRight/></button><div className="reject-box"><select value={rejectReason} onChange={event=>setRejectReason(event.target.value)}><option value="">Причина отказа</option>{REJECTION_REASONS.map(item=><option key={item}>{item}</option>)}</select><input value={rejectNote} onChange={event=>setRejectNote(event.target.value)} placeholder="Комментарий к отказу"/><button onClick={reject}><X/>Отказаться</button></div></>}{selected.status==='Взята в работу'&&<button className="linked-work" onClick={()=>onOpenWork(selected.workId)}>Открыть созданный проект <ArrowRight/></button>}{selected.status==='Отказ'&&<div className="rejected-note"><b>{selected.rejectionReason}</b><span>{selected.rejectionNote}</span></div>}</>:<div className="qualification-empty">Выберите возможность</div>}</aside>
  </section>}
  {view==='analytics'&&<section className="opportunity-analytics"><article><h3>Воронка поиска</h3><div className="funnel-line"><span>Найдено</span><b>{analytics.total}</b></div><div className="funnel-line"><span>На оценке</span><b>{analytics.inReview}</b></div><div className="funnel-line"><span>Взято в работу</span><b>{analytics.accepted}</b></div><div className="funnel-line"><span>Отказано</span><b>{analytics.rejected}</b></div></article><article><h3>Причины отказов</h3>{Object.entries(analytics.reasons).sort((a,b)=>b[1]-a[1]).map(([reason,count])=><div className="funnel-line" key={reason}><span>{reason}</span><b>{count}</b></div>)}{!analytics.rejected&&<p>Отказов пока нет.</p>}</article><article><h3>Эффективность площадок</h3>{(data.platforms||[]).map(platform=>{const items=(data.opportunities||[]).filter(item=>item.platformId===platform.id),accepted=items.filter(item=>item.status==='Взята в работу').length;return <div className="platform-performance" key={platform.id}><div><b>{platform.name}</b><span>{items.length} найдено · {accepted} взято</span></div><em>{items.length?Math.round(accepted/items.length*100):0}%</em></div>})}</article></section>}
  {showNew&&<div className="opportunity-modal-backdrop"><section className="opportunity-modal"><div><span>Новая находка</span><h2>Добавить возможность</h2></div><label>Площадка<select value={draft.platformId} onChange={event=>setDraft({...draft,platformId:event.target.value})}>{(data.platforms||[]).map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Заказчик<input value={draft.customer} onChange={event=>setDraft({...draft,customer:event.target.value})}/></label><label>Предмет закупки<input value={draft.title} onChange={event=>setDraft({...draft,title:event.target.value})}/></label><div className="modal-grid"><label>Номер на площадке<input value={draft.externalId} onChange={event=>setDraft({...draft,externalId:event.target.value})}/></label><label>Ориентировочная сумма<input type="number" min="0" value={draft.estimatedAmount} onChange={event=>setDraft({...draft,estimatedAmount:event.target.value})}/></label><label>Дедлайн<input type="date" value={draft.deadline} onChange={event=>setDraft({...draft,deadline:event.target.value})}/></label><label>Ответственный<input value={draft.owner} onChange={event=>setDraft({...draft,owner:event.target.value})}/></label></div><label>Комментарий<textarea value={draft.notes} onChange={event=>setDraft({...draft,notes:event.target.value})}/></label><div className="modal-actions"><button onClick={()=>setShowNew(false)}>Отмена</button><button className="primary" onClick={add}>Добавить</button></div></section></div>}
 </main>;
}
