import React,{useMemo,useState}from'react';
import{Check,Clipboard,Clock3,ExternalLink,History,Play,Plus,Search,ShieldCheck,Target,TrendingUp}from'lucide-react';
import{beginPlatformCheck,completePlatformCheck,opportunityAnalytics,rejectOpportunity,acceptOpportunity,updateOpportunityQualification}from'../domain/opportunities.js';
import{OpportunitySpreadsheet}from'./OpportunitySpreadsheet.jsx';
import{OpportunityDecisionPanel}from'./OpportunityDecisionPanel.jsx';

const dateText=value=>value?new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'никогда';

export function OpportunityEngine({data,setData,currentUser,onOpenWork,onAddTender}){
 const readOnly=currentUser?.role==='director',latest=data.opportunities?.[0];
 const[view,setView]=useState(latest?.captureMethod==='manual'?'opportunities':'route'),[selectedId,setSelectedId]=useState(latest?.id||null),[checkingId,setCheckingId]=useState(null),[error,setError]=useState(''),[checkDraft,setCheckDraft]=useState({reviewedCount:'',foundCount:'',notes:''});
 const analytics=useMemo(()=>opportunityAnalytics(data),[data]),platformMap=useMemo(()=>new Map((data.platforms||[]).map(item=>[item.id,item])),[data.platforms]);
 const selected=(data.opportunities||[]).find(item=>item.id===selectedId)||null;
 const run=operation=>{if(readOnly)return;try{setData(current=>operation(current));setError('')}catch(exception){setError(exception?.message||'Не удалось выполнить действие')}};
 const startCheck=platform=>{if(readOnly)return;run(current=>beginPlatformCheck(current,platform.id,currentUser));setCheckingId(platform.id);setCheckDraft({reviewedCount:'',foundCount:'',notes:''})};
 const finishCheck=()=>{if(readOnly||!checkingId)return;run(current=>completePlatformCheck(current,checkingId,checkDraft,currentUser));setCheckingId(null);setCheckDraft({reviewedCount:'',foundCount:'',notes:''})};
 const qualify=(field,value)=>selected&&!readOnly&&run(current=>updateOpportunityQualification(current,selected.id,{[field]:value},currentUser));
 const accept=()=>{if(readOnly||!selected)return;try{let work;setData(current=>{const result=acceptOpportunity(current,selected.id,currentUser);work=result.work;return result.state});if(work)onOpenWork(work.id)}catch(exception){setError(exception?.message||'Не удалось взять тендер в работу')}};
 const reject=(reason,note)=>selected&&!readOnly&&run(current=>rejectOpportunity(current,selected.id,reason,note,currentUser));
 const recentChecks=(data.platformChecks||[]).slice(0,8);
 return <main className="opportunity-page">
  <header className="opportunity-head"><div><span>{readOnly?'Контроль директора':'Рабочее место менеджера'} · тендеры</span><h1>{readOnly?'Тендеры и площадки':'Найденные тендеры'}</h1><p>{readOnly?'Просмотр найденных закупок и решений менеджеров.':'Добавьте тендер вручную, быстро дополните карточку и примите решение об участии.'}</p></div>{!readOnly&&<button className="primary" onClick={onAddTender}><Clipboard/>Добавить тендер</button>}</header>
  {readOnly&&<div className="readonly-note"><ShieldCheck/> Директор видит результаты поиска и может открыть созданную сделку. Изменения вносит менеджер.</div>}
  {error&&<div className="inline-error">{error}</div>}
  <section className="opportunity-kpis"><article><Target/><div><span>Площадки сегодня</span><b>{analytics.checkedPlatforms}/{analytics.totalPlatforms}</b></div></article><article><Search/><div><span>Просмотрено закупок</span><b>{analytics.reviewedToday}</b></div></article><article><Plus/><div><span>Найдено сегодня</span><b>{analytics.foundToday}</b></div></article><article><Clock3/><div><span>На оценке</span><b>{analytics.active}</b></div></article><article><TrendingUp/><div><span>Конверсия</span><b>{analytics.conversion.toFixed(1)}%</b></div></article></section>
  <div className="opportunity-tabs"><button className={view==='opportunities'?'active':''} onClick={()=>setView('opportunities')}>Таблица тендеров <span>{analytics.total}</span></button><button className={view==='route'?'active':''} onClick={()=>setView('route')}>Площадки</button><button className={view==='analytics'?'active':''} onClick={()=>setView('analytics')}>Аналитика</button></div>
  {view==='opportunities'&&<section className="opportunity-workspace spreadsheet-mode"><OpportunitySpreadsheet data={data} setData={setData} currentUser={currentUser} selectedId={selectedId} setSelectedId={setSelectedId} onOpenWork={onOpenWork} readOnly={readOnly}/><OpportunityDecisionPanel selected={selected} platform={selected?platformMap.get(selected.platformId):null} data={data} onQualify={qualify} onAccept={accept} onReject={reject} onOpenWork={onOpenWork} readOnly={readOnly}/></section>}
  {view==='route'&&<><section className="route-progress"><div><span>Прогресс ручной проверки</span><b>{analytics.checkedPlatforms} из {analytics.totalPlatforms} площадок</b></div><div className="route-progress-bar"><i style={{width:`${analytics.totalPlatforms?analytics.checkedPlatforms/analytics.totalPlatforms*100:0}%`}}/></div><em>{analytics.reviewedToday} закупок просмотрено · {analytics.foundToday} найдено</em></section><section className="platform-grid">{(data.platforms||[]).map(platform=><article key={platform.id} className={`platform-card ${platform.checkedToday?'done':''} ${platform.status==='Проверяется'?'checking':''}`}><div className="platform-top"><div><span>{platform.frequency}</span><h3>{platform.name}</h3></div><b>{platform.newCount||0} новых</b></div><dl><div><dt>Ответственный</dt><dd>{platform.owner||'Не назначен'}</dd></div><div><dt>Последняя проверка</dt><dd>{dateText(platform.lastCheckedAt)}</dd></div><div><dt>Статус</dt><dd>{platform.status}</dd></div></dl><div className="platform-actions">{platform.url&&<a href={platform.url} target="_blank" rel="noreferrer">Открыть площадку <ExternalLink/></a>}{!readOnly&&(platform.checkedToday?<button disabled><Check/>Проверено</button>:platform.status==='Проверяется'?<button onClick={()=>setCheckingId(platform.id)}><Clock3/>Завершить</button>:<button onClick={()=>startCheck(platform)}><Play/>Начать проверку</button>)}</div></article>)}</section><section className="check-history"><div className="check-history-head"><History/><div><span>Журнал маршрута</span><h3>Последние проверки площадок</h3></div></div>{recentChecks.length?<div className="check-history-list">{recentChecks.map(item=><div key={item.id}><div><b>{platformMap.get(item.platformId)?.name||'Площадка'}</b><span>{item.actorName} · {dateText(item.completedAt)}</span></div><em>{item.reviewedCount} просмотрено</em><strong>{item.foundCount} найдено</strong></div>)}</div>:<p>Проверки еще не зафиксированы.</p>}</section></>}
  {view==='analytics'&&<section className="opportunity-analytics"><article><h3>Воронка поиска</h3><div className="funnel-line"><span>Найдено</span><b>{analytics.total}</b></div><div className="funnel-line"><span>На оценке</span><b>{analytics.inReview}</b></div><div className="funnel-line"><span>Взято в работу</span><b>{analytics.accepted}</b></div><div className="funnel-line"><span>Отказано</span><b>{analytics.rejected}</b></div></article><article><h3>Причины отказов</h3>{Object.entries(analytics.reasons).sort((a,b)=>b[1]-a[1]).map(([reason,count])=><div className="funnel-line" key={reason}><span>{reason}</span><b>{count}</b></div>)}{!analytics.rejected&&<p>Отказов пока нет.</p>}</article><article><h3>Эффективность площадок</h3>{(data.platforms||[]).map(platform=>{const items=(data.opportunities||[]).filter(item=>item.platformId===platform.id),accepted=items.filter(item=>item.status==='Взята в работу').length;return <div className="platform-performance" key={platform.id}><div><b>{platform.name}</b><span>{items.length} найдено · {accepted} взято</span></div><em>{items.length?Math.round(accepted/items.length*100):0}%</em></div>})}</article></section>}
  {!readOnly&&checkingId&&<div className="opportunity-modal-backdrop"><section className="opportunity-modal check-modal"><div><span>Завершение проверки</span><h2>{platformMap.get(checkingId)?.name}</h2></div><div className="modal-grid"><label>Просмотрено закупок<input type="number" min="0" value={checkDraft.reviewedCount} onChange={event=>setCheckDraft({...checkDraft,reviewedCount:event.target.value})}/></label><label>Найдено тендеров<input type="number" min="0" value={checkDraft.foundCount} onChange={event=>setCheckDraft({...checkDraft,foundCount:event.target.value})}/></label></div><label>Комментарий<textarea value={checkDraft.notes} onChange={event=>setCheckDraft({...checkDraft,notes:event.target.value})} placeholder="Что важно передать коллегам"/></label><div className="modal-actions"><button onClick={()=>setCheckingId(null)}>Отмена</button><button className="primary" onClick={finishCheck}>Зафиксировать проверку</button></div></section></div>}
 </main>;
}
