import React,{useMemo,useState}from'react';
import{AlertTriangle,Banknote,CheckCircle2,Clock3,FileText,Plus,Printer,Trash2,WalletCards}from'lucide-react';
import{money,todayPlus}from'../domain/workspace.js';
import{createInvoice,deleteInvoice,paymentTotals,recordInvoicePayment,updateInvoice}from'../domain/payments.js';
import'./payments.css';

const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const printInvoice=(invoice,work,currency)=>{const windowRef=window.open('','_blank','width=900,height=760');if(!windowRef)return;windowRef.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Счёт ${escapeHtml(invoice.number)}</title><style>body{font:14px/1.5 Segoe UI,Arial,sans-serif;color:#172b3d;margin:38px}.top{display:flex;justify-content:space-between;border-bottom:2px solid #176ea9;padding-bottom:18px}.brand{font-size:24px;font-weight:900;color:#176ea9}h1{margin:0;font-size:24px}.box{margin-top:24px;border:1px solid #ccd8e2;padding:18px}.amount{text-align:right;font-size:24px;font-weight:900;margin-top:24px}.foot{margin-top:40px;border-top:1px solid #d5dee6;padding-top:12px;color:#6f8193}@media print{body{margin:18mm}}</style></head><body><div class="top"><div><div class="brand">ПРОМАППАРАТ</div><div>Промышленная арматура и КИПиА</div></div><div><h1>Счёт №${escapeHtml(invoice.number)}</h1><div>от ${new Date(invoice.issueDate).toLocaleDateString('ru-RU')}</div></div></div><div class="box"><b>Плательщик:</b> ${escapeHtml(work.customer)}<br/><b>Основание:</b> ${escapeHtml(work.title)}<br/><b>Оплатить до:</b> ${new Date(invoice.dueDate).toLocaleDateString('ru-RU')}</div><div class="amount">К оплате: ${money(invoice.amount,currency)}</div>${invoice.note?`<p><b>Примечание:</b> ${escapeHtml(invoice.note)}</p>`:''}<div class="foot">ПО «Промаппарат» · документ сформирован в PromApparat Workspace</div><script>window.onload=()=>window.print()</script></body></html>`);windowRef.document.close()};

export function PaymentView({work,data,setData,currentUser}){
 const readOnly=currentUser?.role==='director',currency=data.settings?.currency||'RUB',totals=paymentTotals(data,work.id),saleTotal=Number(work.totals?.saleTotal||0),remainingToBill=Math.max(0,saleTotal-totals.billed),nextNumber=`${work.code}-${totals.invoices.length+1}`;
 const[number,setNumber]=useState(nextNumber),[amount,setAmount]=useState(remainingToBill||saleTotal||''),[issueDate,setIssueDate]=useState(new Date().toISOString().slice(0,10)),[dueDate,setDueDate]=useState(todayPlus(14)),[note,setNote]=useState(''),[paymentDrafts,setPaymentDrafts]=useState({}),[message,setMessage]=useState('');
 const sorted=useMemo(()=>[...totals.invoices].sort((a,b)=>String(b.issueDate).localeCompare(String(a.issueDate))),[totals.invoices]);
 const create=()=>{if(readOnly)return;try{let invoice;setData(current=>{const result=createInvoice(current,work.id,{number,amount,issueDate,dueDate,note},currentUser);invoice=result.invoice;return result.state});setNumber(`${work.code}-${totals.invoices.length+2}`);setAmount(Math.max(0,remainingToBill-Number(amount||0))||'');setIssueDate(new Date().toISOString().slice(0,10));setDueDate(todayPlus(14));setNote('');setMessage(`Счёт №${invoice?.number||''} создан`)}catch(error){setMessage(error?.message||'Не удалось создать счёт')}};
 const update=(invoice,changes)=>{if(readOnly)return;try{setData(current=>updateInvoice(current,invoice.id,changes,currentUser));setMessage('Счёт обновлён')}catch(error){setMessage(error?.message||'Не удалось обновить счёт')}};
 const pay=invoice=>{if(readOnly)return;const draft=paymentDrafts[invoice.id]||{},outstanding=Math.max(0,Number(invoice.amount||0)-totals.paidFor(invoice)),value=draft.amount||outstanding;if(!Number(value))return;try{setData(current=>recordInvoicePayment(current,invoice.id,{amount:value,date:draft.date||new Date().toISOString().slice(0,10),note:draft.note||''},currentUser).state);setPaymentDrafts(current=>({...current,[invoice.id]:{}}));setMessage(`Платёж по счёту №${invoice.number} сохранён`)}catch(error){setMessage(error?.message||'Не удалось сохранить платёж')}};
 const remove=invoice=>{if(readOnly||!window.confirm(`Удалить счёт №${invoice.number}?`))return;try{setData(current=>deleteInvoice(current,invoice.id,currentUser));setMessage('Счёт удалён')}catch(error){setMessage(error?.message||'Не удалось удалить счёт')}};
 return <section className="payment-view">
  {readOnly&&<div className="readonly-note">Режим директора: счета и платежи доступны для контроля. Изменения вносит менеджер.</div>}
  {message&&<div className="payment-message">{message}</div>}
  <section className="payment-summary"><article><FileText/><div><span>Сумма сделки</span><b>{money(saleTotal,currency)}</b></div></article><article><WalletCards/><div><span>Выставлено</span><b>{money(totals.billed,currency)}</b></div></article><article><CheckCircle2/><div><span>Получено</span><b>{money(totals.paid,currency)}</b></div></article><article className={totals.debt?'warn':''}><Banknote/><div><span>Долг</span><b>{money(totals.debt,currency)}</b></div></article><article className={totals.overdue?'danger':''}><AlertTriangle/><div><span>Просрочено счетов</span><b>{totals.overdue}</b></div></article></section>
  {!readOnly&&<section className="invoice-create"><header><div><span>Новый счёт</span><h2>Выставить счёт заказчику</h2><p>Осталось выставить по сделке: {money(remainingToBill,currency)}</p></div><FileText/></header><div className="invoice-form"><label><span>Номер</span><input value={number} onChange={event=>setNumber(event.target.value)}/></label><label><span>Сумма</span><input type="number" min="0.01" value={amount} onChange={event=>setAmount(event.target.value)}/></label><label><span>Дата счёта</span><input type="date" value={issueDate} onChange={event=>setIssueDate(event.target.value)}/></label><label><span>Оплатить до</span><input type="date" value={dueDate} onChange={event=>setDueDate(event.target.value)}/></label><label className="invoice-note"><span>Комментарий</span><input value={note} onChange={event=>setNote(event.target.value)} placeholder="Аванс, этап, номер договора"/></label><button className="primary" disabled={!number.trim()||!Number(amount)} onClick={create}><Plus/>Создать счёт</button></div></section>}
  <section className="invoice-register"><header><div><span>Расчёты с заказчиком</span><h2>Счета и поступления</h2></div><b>{sorted.length}</b></header>{sorted.length?<div className="invoice-list">{sorted.map(invoice=>{const paid=totals.paidFor(invoice),outstanding=Math.max(0,Number(invoice.amount||0)-paid),status=totals.statusFor(invoice),draft=paymentDrafts[invoice.id]||{};return <article key={invoice.id} className={status==='Оплачен'?'paid':status==='Просрочен'?'overdue':''}><div className="invoice-head"><div><span>{status}</span><h3>Счёт №{invoice.number}</h3><p>от {invoice.issueDate} · оплатить до {invoice.dueDate}</p></div><div><b>{money(invoice.amount,currency)}</b><small>остаток {money(outstanding,currency)}</small></div></div><div className="invoice-progress"><i style={{width:`${Math.min(100,Number(invoice.amount)?paid/Number(invoice.amount)*100:0)}%`}}/></div><div className="invoice-meta"><span>Получено: <b>{money(paid,currency)}</b></span><span>Платежей: <b>{(invoice.payments||[]).length}</b></span>{readOnly?<span>Срок: <b>{invoice.dueDate}</b></span>:<label>Срок<input type="date" value={invoice.dueDate} onChange={event=>update(invoice,{dueDate:event.target.value})}/></label>}</div>{!readOnly&&outstanding>0&&<div className="payment-entry"><label><span>Сумма платежа</span><input type="number" min="0.01" max={outstanding} value={draft.amount??outstanding} onChange={event=>setPaymentDrafts(current=>({...current,[invoice.id]:{...draft,amount:event.target.value}}))}/></label><label><span>Дата</span><input type="date" value={draft.date||new Date().toISOString().slice(0,10)} onChange={event=>setPaymentDrafts(current=>({...current,[invoice.id]:{...draft,date:event.target.value}}))}/></label><label className="payment-note"><span>Комментарий</span><input value={draft.note||''} onChange={event=>setPaymentDrafts(current=>({...current,[invoice.id]:{...draft,note:event.target.value}}))} placeholder="Платёжное поручение"/></label><button onClick={()=>pay(invoice)}><Banknote/>Зафиксировать платёж</button></div>}<div className="invoice-actions"><button title="Печать или сохранить в PDF" onClick={()=>printInvoice(invoice,work,currency)}><Printer/></button>{!readOnly&&!(invoice.payments||[]).length&&<button title="Удалить счёт" onClick={()=>remove(invoice)}><Trash2/></button>}</div>{(invoice.payments||[]).length>0&&<details className="payment-history"><summary>История платежей</summary>{invoice.payments.map(payment=><div key={payment.id}><span>{payment.date}</span><b>{money(payment.amount,currency)}</b><small>{payment.note}</small></div>)}</details>}</article>})}</div>:<div className="payment-empty"><Clock3/><b>Счета ещё не выставлены</b><span>Создайте первый счёт после доставки или согласно условиям договора.</span></div>}</section>
 </section>;
}
