import React,{useEffect,useState}from'react';
import{Phone,Plus,Trash2,X}from'lucide-react';
import{pct}from'../domain/workspace.js';
import{addBatchCommand,addOfferCommand,deleteBatchCommand,deleteOfferCommand,selectOfferCommand,updateBatchCommand,updateOfferCommand,updatePositionCommand}from'../domain/commands.js';
import{useUnsavedWarning}from'../hooks/useUnsavedWarning.js';

const different=(left,right)=>String(left??'')!==String(right??'');

export function PositionPanel({position,data,setData,onClose,currentUser}){
 const[error,setError]=useState(''),[positionDraft,setPositionDraft]=useState({}),[offerDrafts,setOfferDrafts]=useState({}),[batchDrafts,setBatchDrafts]=useState({});
 const raw=position?data.positions.find(item=>item.id===position.id):null;
 useEffect(()=>{if(raw)setPositionDraft({salePrice:raw.salePrice??'',logisticsCost:raw.logisticsCost??0,otherCosts:raw.otherCosts??0,vatRate:raw.vatRate??20})},[position?.id]);
 useEffect(()=>{if(raw)setOfferDrafts(Object.fromEntries((raw.offers||[]).map(offer=>[offer.id,{...offer}])))} ,[position?.id,(raw?.offers||[]).map(offer=>offer.id).join(',')]);
 useEffect(()=>{if(raw)setBatchDrafts(Object.fromEntries((raw.batches||[]).map(batch=>[batch.id,{...batch}])))} ,[position?.id,(raw?.batches||[]).map(batch=>batch.id).join(',')]);
 const dirty=!!raw&&(['salePrice','logisticsCost','otherCosts','vatRate'].some(field=>different(positionDraft[field],raw[field]))||(raw.offers||[]).some(offer=>['price','productionDays','deliveryDays','shipmentPlace','paymentTerms'].some(field=>different(offerDrafts[offer.id]?.[field],offer[field])))||(raw.batches||[]).some(batch=>['qty','readyDate','shipDate','place'].some(field=>different(batchDrafts[batch.id]?.[field],batch[field]))));
 useUnsavedWarning(dirty);
 if(!position||!raw)return <aside className="assistant"><section><h3>Выберите позицию</h3><p>Справа появятся предложения поставщиков и партии отгрузки.</p></section></aside>;
 const run=operation=>{try{setData(current=>operation(current));setError('')}catch(exception){setError(exception?.message||'Не удалось выполнить действие')}};
 const commitPosition=field=>run(current=>updatePositionCommand(current,raw.id,{[field]:positionDraft[field]},currentUser));
 const setOfferDraft=(id,change)=>setOfferDrafts(current=>({...current,[id]:{...current[id],...change}}));
 const commitOffer=(id,field)=>run(current=>updateOfferCommand(current,raw.id,id,{[field]:offerDrafts[id]?.[field]},currentUser));
 const setBatchDraft=(id,change)=>setBatchDrafts(current=>({...current,[id]:{...current[id],...change}}));
 const commitBatch=(id,field)=>run(current=>updateBatchCommand(current,raw.id,id,{[field]:batchDrafts[id]?.[field]},currentUser));
 const addOffer=()=>run(current=>addOfferCommand(current,raw.id,currentUser));
 const removeOffer=offer=>{if(window.confirm('Удалить предложение поставщика?'))run(current=>deleteOfferCommand(current,raw.id,offer.id,currentUser))};
 const addBatch=()=>run(current=>addBatchCommand(current,raw.id,currentUser));
 const removeBatch=batch=>{if(window.confirm('Удалить партию?'))run(current=>deleteBatchCommand(current,raw.id,batch.id,currentUser))};
 const close=()=>{if(dirty&&!window.confirm('Есть несохраненные изменения. Закрыть карточку?'))return;onClose()};
 return <aside className="assistant position-drawer">
  <div className="panel-head"><div><span>Позиция №{position.rowNo}</span><h2>{position.name}</h2></div><button onClick={close}><X/></button></div>
  {error&&<div className="inline-error">{error}</div>}
  <div className="scoreline"><div><b>{position.progress}%</b><span>готовность</span></div><div><b>{pct(position.grossMargin)}</b><span>маржа</span></div><div><b>{pct(position.markup)}</b><span>наценка</span></div></div>
  <section><div className="section-head"><h3>Предложения поставщиков</h3><button onClick={addOffer}><Plus/>Добавить</button></div>{(raw.offers||[]).map((offer,index)=>{const draft=offerDrafts[offer.id]||offer,supplier=data.suppliers.find(item=>item.id===offer.supplierId);return <div className={`offer-card ${offer.selected?'chosen':''}`} key={offer.id}>
   <div className="offer-top"><b>Вариант {index+1}</b><label><input type="radio" checked={!!offer.selected} onChange={()=>run(current=>selectOfferCommand(current,raw.id,offer.id,currentUser))}/> выбрать</label><button onClick={()=>removeOffer(offer)}><Trash2/></button></div>
   <select value={offer.supplierId||''} onChange={event=>run(current=>updateOfferCommand(current,raw.id,offer.id,{supplierId:event.target.value},currentUser))}><option value="">Поставщик</option>{data.suppliers.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>
   <div className="grid3"><label>Цена<input type="number" min="0" value={draft.price??''} onChange={event=>setOfferDraft(offer.id,{price:event.target.value})} onBlur={()=>commitOffer(offer.id,'price')}/></label><label>Изг., дн.<input type="number" min="0" value={draft.productionDays??''} onChange={event=>setOfferDraft(offer.id,{productionDays:event.target.value})} onBlur={()=>commitOffer(offer.id,'productionDays')}/></label><label>Доставка<input type="number" min="0" value={draft.deliveryDays??''} onChange={event=>setOfferDraft(offer.id,{deliveryDays:event.target.value})} onBlur={()=>commitOffer(offer.id,'deliveryDays')}/></label></div>
   <input placeholder="Место отгрузки" value={draft.shipmentPlace||''} onChange={event=>setOfferDraft(offer.id,{shipmentPlace:event.target.value})} onBlur={()=>commitOffer(offer.id,'shipmentPlace')}/><input placeholder="Условия оплаты" value={draft.paymentTerms||''} onChange={event=>setOfferDraft(offer.id,{paymentTerms:event.target.value})} onBlur={()=>commitOffer(offer.id,'paymentTerms')}/><label className="check"><input type="checkbox" checked={!!offer.hasTkp} onChange={event=>run(current=>updateOfferCommand(current,raw.id,offer.id,{hasTkp:event.target.checked},currentUser))}/> ТКП получено</label>{supplier&&<small><Phone/> {supplier.contact} · {supplier.phone}</small>}
  </div>})}</section>
  <section><div className="grid2"><label className="sale-label">Цена продажи<input type="number" min="0" value={positionDraft.salePrice??''} onChange={event=>setPositionDraft({...positionDraft,salePrice:event.target.value})} onBlur={()=>commitPosition('salePrice')}/></label><label className="sale-label">Логистика / ед.<input type="number" min="0" value={positionDraft.logisticsCost??0} onChange={event=>setPositionDraft({...positionDraft,logisticsCost:event.target.value})} onBlur={()=>commitPosition('logisticsCost')}/></label><label className="sale-label">Прочие / ед.<input type="number" min="0" value={positionDraft.otherCosts??0} onChange={event=>setPositionDraft({...positionDraft,otherCosts:event.target.value})} onBlur={()=>commitPosition('otherCosts')}/></label><label className="sale-label">НДС, %<input type="number" min="0" value={positionDraft.vatRate??20} onChange={event=>setPositionDraft({...positionDraft,vatRate:event.target.value})} onBlur={()=>commitPosition('vatRate')}/></label></div></section>
  <section><div className="section-head"><h3>Готовность и отгрузки</h3><button onClick={addBatch}><Plus/>Партия</button></div>{(raw.batches||[]).map((batch,index)=>{const draft=batchDrafts[batch.id]||batch;return <div className="batch-card" key={batch.id}><div className="batch-top"><b>Партия {index+1}</b><button onClick={()=>removeBatch(batch)}><Trash2/></button></div><div className="grid2"><label>Количество<input type="number" min="0" value={draft.qty??''} onChange={event=>setBatchDraft(batch.id,{qty:event.target.value})} onBlur={()=>commitBatch(batch.id,'qty')}/></label><label>Статус<select value={batch.status} onChange={event=>run(current=>updateBatchCommand(current,raw.id,batch.id,{status:event.target.value},currentUser))}><option>Запланировано</option><option>В производстве</option><option>Готово</option><option>Отгружено</option></select></label><label>Готовность<input type="date" value={draft.readyDate||''} onChange={event=>setBatchDraft(batch.id,{readyDate:event.target.value})} onBlur={()=>commitBatch(batch.id,'readyDate')}/></label><label>Отгрузка<input type="date" value={draft.shipDate||''} onChange={event=>setBatchDraft(batch.id,{shipDate:event.target.value})} onBlur={()=>commitBatch(batch.id,'shipDate')}/></label></div><input placeholder="Место отгрузки" value={draft.place||''} onChange={event=>setBatchDraft(batch.id,{place:event.target.value})} onBlur={()=>commitBatch(batch.id,'place')}/></div>})}</section>
 </aside>;
}
