import React,{useMemo,useState}from'react';
import{AlertTriangle,ArrowRight,Boxes,CheckCircle2,Clock3,Plus,Trash2}from'lucide-react';
import{daysLeft,todayPlus}from'../domain/workspace.js';
import{createProductionBatch,deleteProductionBatch,PRODUCTION_STATUSES,updateProductionBatch}from'../domain/production.js';
import'./production.css';

const dueText=value=>{const days=daysLeft(value);if(days===999)return'Срок не указан';if(days<0)return`Просрочено ${Math.abs(days)} дн.`;if(days===0)return'Сегодня';if(days===1)return'Завтра';return`Через ${days} дн.`};
const statusClass=status=>status==='Отгружено'?'shipped':status==='Готово'?'ready':status==='В производстве'?'active':'planned';

export function ProductionView({work,data,setData,currentUser,onSelectPosition}){
 const readOnly=currentUser?.role==='director',entries=useMemo(()=>work.positions.flatMap(position=>(position.batches||[]).map(batch=>({position,batch}))),[work.positions]);
 const[positionId,setPositionId]=useState(''),[qty,setQty]=useState(''),[readyDate,setReadyDate]=useState(todayPlus(14)),[place,setPlace]=useState(''),[status,setStatus]=useState('В производстве'),[message,setMessage]=useState('');
 const inProduction=entries.filter(item=>item.batch.status==='В производстве').length,ready=entries.filter(item=>item.batch.status==='Готово').length,shipped=entries.filter(item=>item.batch.status==='Отгружено').length,overdue=entries.filter(item=>['Запланировано','В производстве'].includes(item.batch.status)&&daysLeft(item.batch.readyDate)<0).length;
 const selectedPosition=work.positions.find(item=>item.id===positionId),remaining=selectedPosition?Math.max(0,Number(selectedPosition.qty||0)-(selectedPosition.batches||[]).reduce((sum,batch)=>sum+Number(batch.qty||0),0)):0;
 const selectPosition=value=>{setPositionId(value);const position=work.positions.find(item=>item.id===value),left=position?Math.max(0,Number(position.qty||0)-(position.batches||[]).reduce((sum,batch)=>sum+Number(batch.qty||0),0)):0;setQty(left||'')};
 const create=()=>{if(readOnly)return;try{let batch;setData(current=>{const result=createProductionBatch(current,{positionId,qty,readyDate,place,status},currentUser);batch=result.batch;return result.state});setPositionId('');setQty('');setReadyDate(todayPlus(14));setPlace('');setStatus('В производстве');setMessage(`Партия создана: ${batch?.qty||0}`)}catch(error){setMessage(error?.message||'Не удалось создать партию')}};
 const update=(entry,changes)=>{if(readOnly)return;try{setData(current=>updateProductionBatch(current,entry.position.id,entry.batch.id,changes,currentUser));setMessage('Партия обновлена')}catch(error){setMessage(error?.message||'Не удалось обновить партию')}};
 const remove=entry=>{if(readOnly||!window.confirm(`Удалить партию ${entry.batch.qty} ${entry.position.unit}?`))return;try{setData(current=>deleteProductionBatch(current,entry.position.id,entry.batch.id,currentUser));setMessage('Партия удалена')}catch(error){setMessage(error?.message||'Не удалось удалить партию')}};
 return <section className="production-view">
  {readOnly&&<div className="readonly-note">Режим директора: производство доступно для контроля. Партии и статусы изменяет менеджер.</div>}
  {message&&<div className="production-message">{message}</div>}
  <section className="production-summary"><article><Boxes/><div><span>В производстве</span><b>{inProduction}</b></div></article><article><CheckCircle2/><div><span>Готово</span><b>{ready}</b></div></article><article><ArrowRight/><div><span>Отгружено</span><b>{shipped}</b></div></article><article className={overdue?'danger':''}><AlertTriangle/><div><span>Просрочено</span><b>{overdue}</b></div></article></section>
  {!readOnly&&<section className="production-create"><header><div><span>Планирование</span><h2>Создать производственную партию</h2><p>Количество всех партий не может превышать количество позиции.</p></div><Boxes/></header><div className="production-form"><label><span>Позиция</span><select value={positionId} onChange={event=>selectPosition(event.target.value)}><option value="">Выберите позицию</option>{work.positions.map(position=>{const left=Math.max(0,Number(position.qty||0)-(position.batches||[]).reduce((sum,batch)=>sum+Number(batch.qty||0),0));return <option key={position.id} value={position.id} disabled={!left}>№{position.rowNo} · {position.name} · доступно {left}</option>})}</select></label><label><span>Количество</span><input type="number" min="0.0001" max={remaining||undefined} value={qty} onChange={event=>setQty(event.target.value)}/></label><label><span>Готовность</span><input type="date" value={readyDate} onChange={event=>setReadyDate(event.target.value)}/></label><label><span>Статус</span><select value={status} onChange={event=>setStatus(event.target.value)}>{PRODUCTION_STATUSES.filter(item=>item!=='Отгружено').map(item=><option key={item}>{item}</option>)}</select></label><label className="production-place"><span>Завод / место готовности</span><input value={place} onChange={event=>setPlace(event.target.value)} placeholder="Например: Челябинск, склад завода"/></label><button className="primary" disabled={!positionId||!Number(qty)} onClick={create}><Plus/>Создать партию</button></div></section>}
  <section className="production-register"><header><div><span>Контроль исполнения</span><h2>Все производственные партии</h2></div><b>{entries.length}</b></header>{entries.length?<div className="production-table-wrap"><table><thead><tr><th>Позиция</th><th>Количество</th><th>Готовность</th><th>Место</th><th>Статус</th><th>Контроль</th><th></th></tr></thead><tbody>{entries.map(entry=>{const overdueRow=['Запланировано','В производстве'].includes(entry.batch.status)&&daysLeft(entry.batch.readyDate)<0;return <tr key={entry.batch.id} className={overdueRow?'overdue':''}><td><b>№{entry.position.rowNo} · {entry.position.name}</b><small>{entry.position.qty} {entry.position.unit} всего</small></td><td>{readOnly?<span>{entry.batch.qty} {entry.position.unit}</span>:<input type="number" min="0.0001" defaultValue={entry.batch.qty} onBlur={event=>update(entry,{qty:event.target.value})}/>}</td><td>{readOnly?<span>{entry.batch.readyDate||'—'}</span>:<input type="date" value={entry.batch.readyDate||''} onChange={event=>update(entry,{readyDate:event.target.value})}/>}</td><td>{readOnly?<span>{entry.batch.place||'—'}</span>:<input defaultValue={entry.batch.place||''} onBlur={event=>update(entry,{place:event.target.value})}/>}</td><td>{readOnly?<span className={`production-status ${statusClass(entry.batch.status)}`}>{entry.batch.status}</span>:<select className={`production-status ${statusClass(entry.batch.status)}`} value={entry.batch.status} onChange={event=>update(entry,{status:event.target.value,...(event.target.value==='Отгружено'&&!entry.batch.shipDate?{shipDate:new Date().toISOString().slice(0,10)}:{})})}>{PRODUCTION_STATUSES.map(item=><option key={item}>{item}</option>)}</select>}</td><td className={overdueRow?'bad':''}><Clock3/>{dueText(entry.batch.readyDate)}</td><td className="production-actions"><button title="Открыть позицию" onClick={()=>onSelectPosition?.(entry.position.id)}><ArrowRight/></button>{!readOnly&&entry.batch.status!=='Отгружено'&&<button title="Удалить партию" onClick={()=>remove(entry)}><Trash2/></button>}</td></tr>})}</tbody></table></div>:<div className="production-empty"><Boxes/><b>Партии ещё не созданы</b><span>Создайте первую партию после выбора поставщика и согласования заказа.</span></div>}</section>
 </section>;
}
