import React,{useMemo,useState}from'react';
import{AlertTriangle,Calculator,CheckCircle2,FileText,Printer,Save,Send}from'lucide-react';
import{money,pct}from'../domain/workspace.js';
import{updatePositionCommand}from'../domain/commands.js';
import{applyTargetMarginPrices,markQuoteSent,quoteReadiness,recommendedSalePrice,saveQuote}from'../domain/quotes.js';
import'./quote.css';

const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const printQuote=quote=>{if(!quote)return;const rows=quote.positions.map(item=>`<tr><td>${item.rowNo}</td><td>${escapeHtml(item.name)}</td><td>${item.qty} ${escapeHtml(item.unit)}</td><td>${money(item.salePrice,quote.currency)}</td><td>${money(item.total,quote.currency)}</td></tr>`).join(''),windowRef=window.open('','_blank','width=1100,height=800');if(!windowRef)return;windowRef.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>КП №${quote.version} — ${escapeHtml(quote.customer)}</title><style>body{font:14px/1.45 Segoe UI,Arial,sans-serif;color:#172b3d;margin:38px}header{display:flex;justify-content:space-between;gap:30px;border-bottom:2px solid #1b6fae;padding-bottom:18px;margin-bottom:24px}.brand{font-size:24px;font-weight:900;color:#145f98}h1{font-size:22px;margin:0 0 5px}p{margin:3px 0;color:#607386}table{width:100%;border-collapse:collapse;margin-top:22px}th,td{border:1px solid #cfd9e2;padding:9px;text-align:left}th{background:#eef4f8}.total{margin-top:18px;text-align:right;font-size:20px;font-weight:900}.terms{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:22px}.terms div{border:1px solid #d7e0e8;padding:12px}.note{margin-top:18px;white-space:pre-wrap}.foot{margin-top:40px;padding-top:12px;border-top:1px solid #d7e0e8;color:#708194;font-size:11px}@media print{body{margin:18mm}.no-print{display:none}}</style></head><body><header><div><div class="brand">ПРОМАППАРАТ</div><p>Промышленная арматура, КИПиА и инженерное оборудование</p></div><div><h1>Коммерческое предложение №${quote.version}</h1><p>Для: <b>${escapeHtml(quote.customer)}</b></p><p>${new Date(quote.createdAt).toLocaleDateString('ru-RU')}</p></div></header><h2>${escapeHtml(quote.title)}</h2><table><thead><tr><th>№</th><th>Наименование</th><th>Количество</th><th>Цена за ед.</th><th>Сумма</th></tr></thead><tbody>${rows}</tbody></table><div class="total">Итого: ${money(quote.total,quote.currency)}${quote.vatIncluded?' с НДС':''}</div><section class="terms"><div><b>Срок действия</b><p>${quote.validityDays} дней</p></div><div><b>Условия оплаты</b><p>${escapeHtml(quote.paymentTerms||'По согласованию')}</p></div><div><b>Условия поставки</b><p>${escapeHtml(quote.deliveryTerms||'По согласованию')}</p></div><div><b>НДС</b><p>${quote.vatIncluded?'Включён':'Не включён'}</p></div></section>${quote.note?`<div class="note"><b>Примечание</b><p>${escapeHtml(quote.note)}</p></div>`:''}<div class="foot">ПО «Промаппарат» · предложение сформировано в PromApparat Workspace</div><script>window.onload=()=>window.print()</script></body></html>`);windowRef.document.close()};

export function QuoteView({work,data,setData,currentUser}){
 const readOnly=currentUser?.role==='director',quotes=useMemo(()=>(data.quotes||[]).filter(item=>item.workId===work.id).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))),[data.quotes,work.id]),latest=quotes[0]||null,readiness=quoteReadiness(data,work.id);
 const[targetMargin,setTargetMargin]=useState(Number(data.settings?.targetMargin??15)),[draft,setDraft]=useState({validityDays:10,deliveryTerms:'Срок поставки — согласно согласованному графику',paymentTerms:'50% предоплата, 50% перед отгрузкой',note:'',vatIncluded:true}),[message,setMessage]=useState('');
 const readyPositions=work.positions.filter(position=>position.selected&&Number(position.salePrice||0)),missing=work.positions.length-readyPositions.length,total=work.positions.reduce((sum,position)=>sum+Number(position.saleTotal||0),0);
 const updateSale=(position,value)=>{if(readOnly||String(position.salePrice??'')===String(value??''))return;try{setData(current=>updatePositionCommand(current,position.id,{salePrice:value},currentUser));setMessage('Цена продажи сохранена')}catch(error){setMessage(error?.message||'Не удалось сохранить цену')}};
 const calculate=()=>{if(readOnly)return;try{const result=applyTargetMarginPrices(data,work.id,targetMargin,currentUser);setData(result.state);setMessage(`Рассчитано цен: ${result.positionIds.length}`)}catch(error){setMessage(error?.message||'Не удалось рассчитать цены')}};
 const save=()=>{if(readOnly)return;try{const result=saveQuote(data,work.id,draft,currentUser);setData(result.state);setMessage(`КП №${result.quote.version} сохранено`)}catch(error){setMessage(error?.message||'Не удалось сохранить КП')}};
 const send=()=>{if(readOnly||!latest)return;try{setData(current=>markQuoteSent(current,latest.id,currentUser));setMessage(`КП №${latest.version} отмечено как отправленное`)}catch(error){setMessage(error?.message||'Не удалось изменить статус КП')}};
 return <section className="quote-view">
  {readOnly&&<div className="readonly-note">Режим директора: доступна проверка и печать сохранённых КП. Цены и условия изменяет менеджер.</div>}
  {message&&<div className="quote-message">{message}</div>}
  <section className="quote-summary"><article><FileText/><div><span>Позиций</span><b>{work.positions.length}</b></div></article><article className={missing?'warn':''}><AlertTriangle/><div><span>Не готовы к КП</span><b>{missing}</b></div></article><article><CheckCircle2/><div><span>Готовы</span><b>{readyPositions.length}</b></div></article><article><Calculator/><div><span>Сумма КП</span><b>{money(total,data.settings?.currency||'RUB')}</b></div></article></section>
  {!readOnly&&<section className="quote-calculator"><div><span>Расчёт цен</span><h2>Целевая маржа</h2><p>Заполняются только позиции с выбранным ТКП и пустой ценой продажи.</p></div><label><input type="number" min="0" max="95" step="0.1" value={targetMargin} onChange={event=>setTargetMargin(event.target.value)}/><em>%</em></label><button onClick={calculate}><Calculator/>Заполнить пустые цены</button></section>}
  <section className="quote-position-table"><header><div><span>Состав предложения</span><h2>Позиции и цены</h2></div><b>{readyPositions.length}/{work.positions.length}</b></header><div className="quote-table-wrap"><table><thead><tr><th>№</th><th>Наименование</th><th>Кол-во</th><th>Закупка</th><th>Рекомендация</th><th>Цена продажи</th><th>Маржа</th><th>Сумма</th></tr></thead><tbody>{work.positions.map(position=>{const recommended=recommendedSalePrice(position,targetMargin);return <tr key={position.id} className={!position.selected||!Number(position.salePrice||0)?'incomplete':''}><td>{position.rowNo}</td><td><b>{position.name}</b><small>{position.selected?.supplier?.name||'Предложение не выбрано'}</small></td><td>{position.qty} {position.unit}</td><td>{position.unitCost==null?'—':money(position.unitCost,position.currency)}</td><td>{recommended==null?'—':money(recommended,position.currency)}</td><td>{readOnly?<b>{money(position.salePrice,position.currency)}</b>:<input type="number" min="0" defaultValue={position.salePrice||''} onBlur={event=>updateSale(position,event.target.value)} placeholder="Введите цену"/>}</td><td>{pct(position.grossMargin)}</td><td><b>{money(position.saleTotal,position.currency)}</b></td></tr>})}</tbody></table></div>{!work.positions.length&&<div className="quote-empty">В сделке пока нет позиций.</div>}</section>
  <section className="quote-layout"><div className="quote-terms"><header><div><span>Условия</span><h2>Параметры коммерческого предложения</h2></div></header><div className="quote-term-grid"><label>Срок действия, дней<input disabled={readOnly} type="number" min="1" value={draft.validityDays} onChange={event=>setDraft({...draft,validityDays:event.target.value})}/></label><label className="wide">Условия оплаты<input disabled={readOnly} value={draft.paymentTerms} onChange={event=>setDraft({...draft,paymentTerms:event.target.value})}/></label><label className="wide">Условия поставки<input disabled={readOnly} value={draft.deliveryTerms} onChange={event=>setDraft({...draft,deliveryTerms:event.target.value})}/></label><label className="wide">Примечание<textarea disabled={readOnly} value={draft.note} onChange={event=>setDraft({...draft,note:event.target.value})}/></label><label className="quote-check"><input disabled={readOnly} type="checkbox" checked={draft.vatIncluded} onChange={event=>setDraft({...draft,vatIncluded:event.target.checked})}/>НДС включён в цены</label></div>{!readOnly&&<button className="primary quote-save" disabled={!readiness.ready} onClick={save}><Save/>Сохранить новую версию КП</button>}{!readiness.ready&&<div className="quote-warning"><AlertTriangle/><span>{readiness.issues.slice(0,4).join(' · ')||'КП пока не готово'}</span></div>}</div><aside className="quote-versions"><header><div><span>Версии</span><h2>Сохранённые КП</h2></div><b>{quotes.length}</b></header>{quotes.length?quotes.map(quote=><article key={quote.id} className={quote.id===latest?.id?'latest':''}><div><b>КП №{quote.version}</b><span>{new Date(quote.createdAt).toLocaleString('ru-RU')} · {quote.status}</span><small>{money(quote.total,quote.currency)} · {quote.positions.length} поз.</small></div><div><button title="Печать или сохранить в PDF" onClick={()=>printQuote(quote)}><Printer/></button>{!readOnly&&quote.status!=='Отправлено'&&<button className="send" title="Отметить отправленным" onClick={()=>{if(quote.id===latest.id)send();else setData(current=>markQuoteSent(current,quote.id,currentUser))}}><Send/></button>}</div></article>):<div className="quote-empty">Сохранённых версий пока нет.</div>}</aside></section>
 </section>;
}
