import React,{useEffect,useRef,useState}from'react';
import{AlertTriangle,CheckCircle2,Database,FileUp,History,RefreshCw,ShieldCheck}from'lucide-react';
import{bootstrapWorkspace,getAuditLog}from'../api/client.js';
import'./server-operations.css';

const actionLabel=value=>({
 'workspace.sync':'Сохранено рабочее пространство',
 'workspace.bootstrap':'Выполнен первоначальный перенос данных',
 'user.create':'Создан пользователь',
 'user.update':'Изменён доступ пользователя'
}[value]||value||'Системное действие');
const dateText=value=>value?new Intl.DateTimeFormat('ru-RU',{dateStyle:'short',timeStyle:'medium'}).format(new Date(value)):'—';
const importedData=parsed=>parsed?.format==='promapparat-workspace'?parsed.data:parsed;
const workspaceEmpty=data=>['works','positions','opportunities','documents','supplierRequests','quotes','shipments','invoices'].every(key=>!(data?.[key]||[]).length);

export function ServerOperations({data,onServerChanged}){
 const inputRef=useRef(null),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),revision=Number(data.meta?.serverRevision||0),canBootstrap=revision===0&&workspaceEmpty(data);
 const loadAudit=async()=>{setLoading(true);try{const result=await getAuditLog(80);setItems(result.items||[])}catch(error){setMessage(error?.message||'Не удалось загрузить журнал')}finally{setLoading(false)}};
 useEffect(()=>{loadAudit()},[]);
 const bootstrap=async file=>{if(!file||busy)return;setBusy(true);setMessage('');try{const parsed=JSON.parse(await file.text()),source=importedData(parsed);if(!source||typeof source!=='object'||Array.isArray(source))throw new Error('В файле нет рабочего пространства');const counts={works:source.works?.length||0,positions:source.positions?.length||0,opportunities:source.opportunities?.length||0};if(!window.confirm(`Перенести данные на сервер?\n\nСделок: ${counts.works}\nПозиций: ${counts.positions}\nТендеров: ${counts.opportunities}\n\nОперация доступна только один раз для пустой базы.`))return;await bootstrapWorkspace(source);setMessage('Данные перенесены в PostgreSQL. Загружаю серверную версию…');await onServerChanged?.();await loadAudit()}catch(error){setMessage(error?.message||'Не удалось перенести данные')}finally{setBusy(false);if(inputRef.current)inputRef.current.value=''}};
 return<section className="server-operations"><header><div><Database/><div><span>Серверное рабочее пространство</span><h2>Перенос и журнал изменений</h2><p>Первоначальный импорт разрешён только в пустую базу. После начала работы перезапись блокируется сервером.</p></div></div><div className={`server-revision ${revision?'ready':'empty'}`}><b>R{revision}</b><span>{revision?'База активна':'База пустая'}</span></div></header>{message&&<div className="server-operation-message">{message}</div>}<div className="server-operation-grid"><article className={!canBootstrap?'locked':''}>{canBootstrap?<FileUp/>:<ShieldCheck/>}<div><h3>{canBootstrap?'Перенести текущий прототип':'Первоначальный перенос закрыт'}</h3><p>{canBootstrap?'Выберите JSON-экспорт PromApparat. Пользователи и текущая роль из файла переноситься не будут.':'Сервер уже содержит рабочие данные. Импорт не может заменить действующую базу.'}</p></div><input ref={inputRef} hidden type="file" accept="application/json,.json" onChange={event=>bootstrap(event.target.files?.[0])}/><button disabled={!canBootstrap||busy} onClick={()=>inputRef.current?.click()}>{busy?'Перенос…':'Выбрать JSON'}</button></article><article><CheckCircle2/><div><h3>Защита от перезаписи</h3><p>Каждое сохранение сверяет ревизию. Конфликт другого сотрудника показывается до потери данных.</p></div><em>Включено</em></article></div><section className="server-audit"><div className="server-audit-head"><div><History/><div><span>Аудит сервера</span><h3>Последние изменения</h3></div></div><button onClick={loadAudit} disabled={loading}><RefreshCw/>{loading?'Загрузка…':'Обновить'}</button></div>{items.length?<div className="server-audit-list">{items.map(item=><article key={item.id}><div className="server-audit-mark"><i/></div><div><b>{actionLabel(item.action)}</b><span>{item.user_name||'Система'} · {item.user_role==='director'?'директор':item.user_role==='manager'?'менеджер':'система'}</span>{item.changed_sections?.length>0&&<small>{item.changed_sections.join(', ')}</small>}</div><time>{dateText(item.created_at)}</time><em>{item.new_revision!=null?`R${item.old_revision??0} → R${item.new_revision}`:''}</em></article>)}</div>:<div className="server-audit-empty">{loading?'Загружаю журнал…':'Изменений пока нет'}</div>}</section>{!canBootstrap&&revision===0&&!workspaceEmpty(data)&&<div className="server-operation-warning"><AlertTriangle/>В интерфейсе есть данные при нулевой серверной ревизии. Обновите рабочее пространство перед импортом.</div>}</section>;
}
