import React,{useMemo,useRef,useState}from'react';
import*as XLSX from'xlsx';
import{AlertTriangle,CheckCircle2,FileSpreadsheet,RotateCcw,Upload,XCircle}from'lucide-react';
import{IMPORT_FIELDS,analyzeImportRows,guessColumnMapping,importSpecificationCommand,rollbackSpecificationImportCommand}from'../domain/specificationImport.js';
import'./specification-import.css';

export function SpecificationImport({work,data,setData,currentUser}){
 const inputRef=useRef(null),[fileName,setFileName]=useState(''),[sheetNames,setSheetNames]=useState([]),[sheetName,setSheetName]=useState(''),[sheetRows,setSheetRows]=useState({}),[headers,setHeaders]=useState([]),[rows,setRows]=useState([]),[mapping,setMapping]=useState({}),[message,setMessage]=useState('');
 const analysis=useMemo(()=>analyzeImportRows(rows,mapping,data.positions.filter(position=>position.workId===work.id)),[rows,mapping,data.positions,work.id]);
 const validCount=analysis.filter(item=>item.valid).length,duplicateCount=analysis.filter(item=>item.duplicate).length,errorCount=analysis.filter(item=>item.errors.length).length;
 const imports=(data.specificationImports||[]).filter(item=>item.workId===work.id),hasName=Object.values(mapping).includes('name'),hasQty=Object.values(mapping).includes('qty'),mappingReady=hasName&&hasQty;
 const loadSheet=(name,all=sheetRows)=>{const matrix=all[name]||[];setSheetName(name);setHeaders(matrix[0]||[]);setRows((matrix.slice(1)||[]).filter(row=>row.some(cell=>String(cell??'').trim())));setMapping(guessColumnMapping(matrix[0]||[]));setMessage('')};
 const clearFile=()=>{setFileName('');setSheetNames([]);setSheetName('');setSheetRows({});setHeaders([]);setRows([]);setMapping({});setMessage('')};
 const readFile=async file=>{if(!file)return;setMessage('');try{const workbook=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:false}),all={};for(const name of workbook.SheetNames)all[name]=XLSX.utils.sheet_to_json(workbook.Sheets[name],{header:1,defval:'',raw:false});if(!workbook.SheetNames.length)throw new Error('В книге нет листов');setFileName(file.name);setSheetNames(workbook.SheetNames);setSheetRows(all);loadSheet(workbook.SheetNames[0],all)}catch(error){clearFile();setMessage(error?.message||'Не удалось прочитать Excel-файл')}finally{if(inputRef.current)inputRef.current.value=''}};
 const runImport=()=>{if(!mappingReady)return;try{const result=importSpecificationCommand(data,work.id,analysis,{fileName,sheetName},currentUser);setData(result.state);setMessage(`Готово: добавлено ${result.record.added}, пропущено ${result.record.skipped}. Позиции появились во вкладке «Позиции».`)}catch(error){setMessage(error?.message||'Импорт не выполнен')}};
 const rollback=id=>{if(!window.confirm('Отменить импорт и удалить добавленные им позиции? Позиции с предложениями или партиями удалить нельзя.'))return;try{setData(current=>rollbackSpecificationImportCommand(current,id,currentUser));setMessage('Импорт отменен, свободные позиции удалены')}catch(error){setMessage(error?.message||'Не удалось отменить импорт')}};
 return<section className="spec-import">
  <header className="spec-import-head"><div><span>Excel-спецификация</span><h2>Импорт позиций в сделку</h2><p>Загрузите книгу, проверьте лист и сопоставление колонок. Ошибки и дубли будут пропущены.</p></div><div><input ref={inputRef} hidden type="file" accept=".xlsx,.xls" onChange={event=>readFile(event.target.files?.[0])}/><button className="primary" onClick={()=>inputRef.current?.click()}><Upload/>{fileName?'Выбрать другой файл':'Загрузить Excel'}</button></div></header>
  {message&&<div className="spec-message">{message}</div>}
  {!fileName?<div className="spec-empty"><FileSpreadsheet/><b>Файл ещё не выбран</b><span>Поддерживаются .xlsx и .xls. Первая строка должна содержать заголовки колонок.</span></div>:<>
   <div className="spec-toolbar"><div><b>{fileName}</b><button className="spec-clear" onClick={clearFile}>Убрать файл</button></div><label>Лист<select value={sheetName} onChange={event=>loadSheet(event.target.value)}>{sheetNames.map(name=><option key={name}>{name}</option>)}</select></label><div className="spec-counters"><span className="ok"><CheckCircle2/>{validCount} готово</span><span><AlertTriangle/>{duplicateCount} дублей</span><span className="bad"><XCircle/>{errorCount} ошибок</span></div><button className="primary" disabled={!mappingReady||!validCount} onClick={runImport}>Импортировать {validCount}</button></div>
   {!mappingReady&&<div className="inline-error">Укажите колонки «Наименование» и «Количество».</div>}
   <div className="mapping-grid">{headers.map((header,index)=><label key={`${header}-${index}`}><span>{header||`Колонка ${index+1}`}</span><select value={mapping[index]||''} onChange={event=>setMapping(current=>({...current,[index]:event.target.value}))}>{IMPORT_FIELDS.map(field=><option key={field.value} value={field.value}>{field.label}</option>)}</select></label>)}</div>
   <div className="spec-preview"><table><thead><tr><th>Строка</th><th>Результат</th><th>Наименование</th><th>Количество</th><th>Ед.</th><th>Группа</th><th>Модель</th><th>Примечание</th></tr></thead><tbody>{analysis.slice(0,100).map(item=><tr key={item.sourceRow} className={!item.valid?'invalid':''}><td>{item.sourceRow}</td><td>{item.valid?<span className="row-ok">будет добавлена</span>:item.duplicate?<span className="row-warn">дубль — пропущена</span>:<span className="row-bad">{item.errors.join(', ')}</span>}</td><td>{item.name||'—'}</td><td>{Number.isFinite(item.qty)?item.qty:'—'}</td><td>{item.unit}</td><td>{item.group||'—'}</td><td>{item.model||'—'}</td><td>{item.note||'—'}</td></tr>)}</tbody></table>{analysis.length>100&&<small>Показаны первые 100 строк из {analysis.length}.</small>}</div>
  </>}
  <div className="import-history"><h3>История импортов</h3>{imports.length?imports.map(item=><article key={item.id}><div><b>{item.fileName}</b><span>{item.sheetName} · добавлено {item.added} · пропущено {item.skipped}</span><small>{new Date(item.createdAt).toLocaleString('ru-RU')}</small></div>{item.rolledBackAt?<em>отменен</em>:<button onClick={()=>rollback(item.id)}><RotateCcw/>Отменить импорт</button>}</article>):<p>Импортов в этой сделке пока нет.</p>}</div>
 </section>;
}
