import React,{useEffect,useMemo,useState}from'react';
import{Building2,Mail,MapPin,Phone,Plus,Search,Star,Trash2}from'lucide-react';
import{money}from'../domain/workspace.js';
import{deleteSupplierCommand,updateSupplierCommand}from'../domain/commands.js';
import{createSupplierCommand,updateSupplierNameCommand}from'../domain/supplierCommands.js';
import'../suppliers.css';

export function SuppliersView({data,setData,currentUser}){
 const readOnly=currentUser?.role==='director';
 const[query,setQuery]=useState(''),[selectedId,setSelectedId]=useState(data.suppliers[0]?.id||null),[draft,setDraft]=useState({}),[error,setError]=useState(''),[newName,setNewName]=useState(''),[adding,setAdding]=useState(false),currency=data.settings?.currency||'RUB';
 const suppliers=useMemo(()=>data.suppliers.map(s=>{const offers=data.positions.flatMap(p=>(p.offers||[]).filter(o=>o.supplierId===s.id).map(o=>({...o,position:p})));return{...s,offers,selectedOffers:offers.filter(o=>o.selected),averagePrice:offers.length?offers.reduce((sum,o)=>sum+Number(o.price||0),0)/offers.length:0}}),[data]);
 const filtered=suppliers.filter(s=>`${s.name} ${s.city} ${s.contact} ${s.specialization||''} ${s.brands||''}`.toLowerCase().includes(query.toLowerCase())),selected=suppliers.find(s=>s.id===selectedId)||filtered[0]||null;
 useEffect(()=>{if(selected)setDraft({...selected})},[selected?.id]);
 const run=operation=>{if(readOnly)return null;try{let result;setData(current=>{result=operation(current);return result?.state||result});setError('');return result}catch(exception){setError(exception?.message||'Не удалось выполнить действие');return null}};
 const add=()=>{if(readOnly||!newName.trim())return;let created;try{setData(current=>{const result=createSupplierCommand(current,newName,currentUser);created=result.supplier;return result.state});if(created)setSelectedId(created.id);setNewName('');setAdding(false);setError('')}catch(exception){setError(exception?.message||'Не удалось создать поставщика')}};
 const remove=()=>{if(readOnly||!selected||!window.confirm(`Удалить поставщика «${selected.name}»?`))return;try{setData(current=>deleteSupplierCommand(current,selected.id,currentUser));setSelectedId(null);setError('')}catch(exception){setError(exception?.message||'Не удалось удалить поставщика')}};
 const change=(field,value)=>!readOnly&&setDraft(current=>({...current,[field]:value})),commit=field=>!readOnly&&selected&&run(current=>field==='name'?updateSupplierNameCommand(current,selected.id,draft.name,currentUser):updateSupplierCommand(current,selected.id,{[field]:draft[field]},currentUser));
 const field=(label,key,props={})=><label className={props.wide?'wide-field':''}>{label}<input {...props} value={draft[key]??''} readOnly={readOnly} onChange={event=>change(key,event.target.value)} onBlur={()=>commit(key)}/></label>;
 return <main className="suppliers-page"><div className="suppliers-head"><div><span>{readOnly?'Контроль директора':'Справочник менеджера'}</span><h1>Поставщики</h1><p>{readOnly?'Просмотр контактов, надежности и истории предложений.':'Контакты, специализация, надежность и история предложений.'}</p></div>{!readOnly&&<button className="primary" onClick={()=>setAdding(true)}><Plus/> Новый поставщик</button>}</div>
 {readOnly&&<div className="readonly-note">Режим директора: карточки доступны для просмотра. Изменения вносит менеджер.</div>}
 {error&&<div className="inline-error">{error}</div>}
 {adding&&<div className="supplier-addbar"><input autoFocus value={newName} onChange={event=>setNewName(event.target.value)} placeholder="Название поставщика" onKeyDown={event=>{if(event.key==='Enter')add();if(event.key==='Escape')setAdding(false)}}/><button onClick={()=>setAdding(false)}>Отмена</button><button className="primary" disabled={!newName.trim()} onClick={add}>Создать</button></div>}
 <div className="suppliers-layout"><section className="supplier-list-panel"><label className="supplier-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Название, город, специализация"/></label><div className="supplier-list">{filtered.map(s=><button key={s.id} className={`supplier-row ${selected?.id===s.id?'active':''}`} onClick={()=>setSelectedId(s.id)}><div className="supplier-avatar"><Building2/></div><div><b>{s.name}</b><span>{s.city||'Город не указан'} · {s.offers.length} предлож.</span><small>{s.specialization||'Специализация не указана'}</small></div><em>{s.reliability??80}%</em></button>)}{!filtered.length&&<div className="supplier-empty">Ничего не найдено</div>}</div></section>
 {selected?<section className="supplier-card"><div className="supplier-card-head"><div><span>Карточка поставщика</span><h2>{selected.name}</h2></div>{!readOnly&&<button className="supplier-delete" aria-label="Удалить поставщика" onClick={remove}><Trash2/></button>}</div><div className="supplier-score"><div><Star/><b>{selected.rating??4}/5</b><span>оценка</span></div><div><b>{selected.reliability??80}%</b><span>надежность</span></div><div><b>{selected.offers.length}</b><span>ТКП / предложений</span></div><div><b>{selected.selectedOffers.length}</b><span>выбрано</span></div></div><div className={`supplier-form ${readOnly?'readonly':''}`}>{field('Название','name',{wide:true})}{field('ИНН','inn')}{field('Город','city')}{field('Контакт','contact')}{field('Телефон','phone')}{field('Email','email')}{field('Сайт','website')}<label>Рейтинг<input type="number" min="1" max="5" value={draft.rating??4} readOnly={readOnly} onChange={e=>change('rating',Math.max(1,Math.min(5,Number(e.target.value))))} onBlur={()=>commit('rating')}/></label><label>Надежность, %<input type="number" min="0" max="100" value={draft.reliability??80} readOnly={readOnly} onChange={e=>change('reliability',Math.max(0,Math.min(100,Number(e.target.value))))} onBlur={()=>commit('reliability')}/></label>{field('Специализация','specialization',{wide:true,placeholder:'Клапаны, КИПиА, расходомеры'})}{field('Бренды','brands',{wide:true,placeholder:'Бренды через запятую'})}<label className="wide-field">Комментарий<textarea value={draft.comment||''} readOnly={readOnly} onChange={e=>change('comment',e.target.value)} onBlur={()=>commit('comment')}/></label></div><div className="supplier-actions">{selected.phone&&<button><Phone/>Позвонить</button>}{selected.email&&<button><Mail/>Написать</button>}{selected.city&&<button><MapPin/>{selected.city}</button>}</div><div className="supplier-history"><div className="section-head"><h3>История предложений</h3><span>{selected.offers.length}</span></div>{selected.offers.length?selected.offers.map(o=><article key={o.id}><div><b>{o.position.name}</b><span>{o.position.qty} {o.position.unit} · {o.hasTkp?'ТКП получено':'ожидаем ТКП'}</span></div><strong>{money(o.price,currency)}</strong><small>{o.productionDays||0}+{o.deliveryDays||0} дней · {o.shipmentPlace||'место не указано'}</small></article>):<div className="supplier-empty">Предложений пока нет</div>}</div></section>:<section className="supplier-card supplier-empty">{readOnly?'Поставщики пока не добавлены':'Создайте или выберите поставщика'}</section>}</div></main>;
}
