import React,{useMemo,useState}from'react';
import{AlertTriangle,ArrowRight,Building2,CheckCircle2,CheckSquare,Clock3,Send,Square}from'lucide-react';
import{daysLeft,todayPlus}from'../domain/workspace.js';
import{createSupplierRequest,SUPPLIER_REQUEST_STATUSES,updateSupplierRequestStatus}from'../domain/supplierRequests.js';
import'./supplier-requests.css';

const dueText=value=>{const days=daysLeft(value);if(days<0)return`Просрочено ${Math.abs(days)} дн.`;if(days===0)return'Ответ сегодня';if(days===1)return'Ответ завтра';return value?`Через ${days} дн.`:'Срок не указан'};
const requestClass=status=>status==='ТКП получено'?'received':status==='Отказ поставщика'?'refused':status==='Отменён'?'cancelled':'sent';

export function SupplierRequestsView({work,data,setData,currentUser,onSelectPosition}){
 const readOnly=currentUser?.role==='director',positions=work.positions||[],requests=(data.supplierRequests||[]).filter(item=>item.workId===work.id),supplierMap=useMemo(()=>new Map((data.suppliers||[]).map(item=>[item.id,item])),[data.suppliers]);
 const[selection,setSelection]=useState([]),[supplierId,setSupplierId]=useState(''),[responseDueDate,setResponseDueDate]=useState(todayPlus(3)),[note,setNote]=useState(''),[message,setMessage]=useState('');
 const waiting=positions.filter(position=>(position.offers||[]).length&&!position.offers.some(offer=>offer.hasTkp)),withoutSupplier=positions.filter(position=>!(position.offers||[]).some(offer=>offer.supplierId)),received=positions.filter(position=>(position.offers||[]).some(offer=>offer.hasTkp));
 const candidates=positions.filter(position=>!['Отгружено','Закрыто'].includes(position.status)),allSelected=candidates.length>0&&candidates.every(position=>selection.includes(position.id));
 const toggle=id=>!readOnly&&setSelection(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
 const toggleAll=()=>!readOnly&&setSelection(allSelected?[]:candidates.map(position=>position.id));
 const create=()=>{if(readOnly)return;try{let created;setData(current=>{const result=createSupplierRequest(current,{workId:work.id,supplierId,positionIds:selection,responseDueDate,note},currentUser);created=result.request;return result.state});setSelection([]);setSupplierId('');setResponseDueDate(todayPlus(3));setNote('');setMessage(`Запрос отправлен: ${created?.positionIds.length||0} позиций`)}catch(error){setMessage(error?.message||'Не удалось создать запрос')}};
 const updateStatus=(request,status)=>{if(readOnly)return;try{setData(current=>updateSupplierRequestStatus(current,request.id,status,currentUser));setMessage(`Статус изменён: ${status}`)}catch(error){setMessage(error?.message||'Не удалось изменить статус')}};
 return <section className="supplier-requests-view">
  {readOnly&&<div className="readonly-note">Режим директора: запросы ТКП доступны для контроля. Создание запросов и фиксацию ответов выполняет менеджер.</div>}
  {message&&<div className="supplier-request-message">{message}</div>}
  <section className="supplier-request-summary"><article><Building2/><div><span>Без поставщика</span><b>{withoutSupplier.length}</b></div></article><article><Clock3/><div><span>Ожидаем ТКП</span><b>{waiting.length}</b></div></article><article><CheckCircle2/><div><span>ТКП получено</span><b>{received.length}</b></div></article><article className={requests.some(item=>item.status==='Отправлен'&&daysLeft(item.responseDueDate)<0)?'danger':''}><AlertTriangle/><div><span>Просрочено запросов</span><b>{requests.filter(item=>item.status==='Отправлен'&&daysLeft(item.responseDueDate)<0).length}</b></div></article></section>
  {!readOnly&&<section className="supplier-request-create"><header><div><span>Следующий этап</span><h2>Запросить ТКП у поставщика</h2><p>Отметьте позиции, выберите поставщика и зафиксируйте срок ответа.</p></div><Send/></header><div className="supplier-request-form"><label><span>Поставщик</span><select value={supplierId} onChange={event=>setSupplierId(event.target.value)}><option value="">Выберите поставщика</option>{(data.suppliers||[]).map(item=><option value={item.id} key={item.id}>{item.name}{item.city?` · ${item.city}`:''}</option>)}</select></label><label><span>Ответ до</span><input type="date" value={responseDueDate} onChange={event=>setResponseDueDate(event.target.value)}/></label><label className="request-note"><span>Комментарий</span><input value={note} onChange={event=>setNote(event.target.value)} placeholder="Условия, контакт или что запросить дополнительно"/></label><button className="primary" disabled={!supplierId||!selection.length} onClick={create}><Send/>Зафиксировать отправку</button></div></section>}
  <section className="request-position-picker"><div className="request-picker-head"><button disabled={readOnly} onClick={toggleAll}>{allSelected?<CheckSquare/>:<Square/>}</button><div><b>Позиции сделки</b><span>{selection.length} выбрано из {candidates.length}</span></div></div><div className="request-position-list">{positions.map(position=>{const hasTkp=(position.offers||[]).some(offer=>offer.hasTkp),suppliers=new Set((position.offers||[]).map(offer=>offer.supplierId).filter(Boolean)).size;return <button key={position.id} disabled={readOnly||['Отгружено','Закрыто'].includes(position.status)} className={`${selection.includes(position.id)?'selected':''} ${hasTkp?'has-tkp':''}`} onClick={()=>toggle(position.id)}><i>{selection.includes(position.id)?<CheckSquare/>:<Square/>}</i><span><b>№{position.rowNo} · {position.name}</b><small>{position.qty} {position.unit} · поставщиков {suppliers}</small></span><em>{hasTkp?'ТКП есть':suppliers?'Ожидаем':'Нужен поставщик'}</em></button>})}{!positions.length&&<div className="request-empty">Сначала импортируйте или добавьте позиции.</div>}</div></section>
  <section className="supplier-request-register"><header><div><span>Журнал запросов</span><h2>Отправленные запросы ТКП</h2></div><b>{requests.length}</b></header>{requests.length?<div className="supplier-request-list">{requests.map(request=>{const supplier=supplierMap.get(request.supplierId),overdue=request.status==='Отправлен'&&daysLeft(request.responseDueDate)<0;return <article key={request.id} className={`${requestClass(request.status)} ${overdue?'overdue':''}`}><div className="request-main"><div><span>{request.status}</span><h3>{supplier?.name||'Поставщик'}</h3><p>{request.positionIds.length} позиций · {dueText(request.responseDueDate)}</p></div>{request.note&&<small>{request.note}</small>}</div><div className="request-status">{readOnly?<b>{request.status}</b>:<select value={request.status} onChange={event=>updateStatus(request,event.target.value)}>{SUPPLIER_REQUEST_STATUSES.map(item=><option key={item}>{item}</option>)}</select>}<button onClick={()=>onSelectPosition?.(request.positionIds[0])}>Открыть позицию <ArrowRight/></button></div></article>})}</div>:<div className="request-empty"><Send/><b>Запросов ещё нет</b><span>Выберите позиции и зафиксируйте отправку первого запроса ТКП.</span></div>}</section>
 </section>;
}
