import React,{useRef,useState}from'react';
import{AlertTriangle,Cloud,Database,Download,FileUp,HardDriveDownload,RefreshCcw,Save,Settings2,ShieldCheck}from'lucide-react';
import{updateFinancialSettingsCommand}from'../domain/settingsCommands.js';
import{ServerOperations}from'./ServerOperations.jsx';
import{UserManagement}from'./UserManagement.jsx';
import'./system.css';

export function SystemSettings({data,setData,currentUser,serverManaged=false,onServerChanged,storageError,exportBackup,importBackup,restoreBackup,createSnapshot,reset}){
 const inputRef=useRef(null),[message,setMessage]=useState('');
 const download=()=>{const blob=new Blob([exportBackup()],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`promapparat-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);setMessage('Экспорт рабочей области скачан')};
 const upload=async file=>{if(!file||serverManaged)return;try{if(!window.confirm('Импорт заменит текущие локальные данные. Продолжить?'))return;importBackup(await file.text());setMessage('Данные восстановлены из файла')}catch(error){setMessage(error?.message||'Ошибка импорта')}finally{if(inputRef.current)inputRef.current.value=''}};
 const restore=()=>{try{if(!window.confirm('Восстановить последнюю локальную резервную копию?'))return;restoreBackup();setMessage('Локальная копия восстановлена')}catch(error){setMessage(error?.message||'Копия не найдена')}};
 const clear=()=>{try{if(!window.confirm('Сбросить локальные демонстрационные данные?'))return;reset();setMessage('Данные сброшены')}catch(error){setMessage(error?.message||'Сброс недоступен')}};
 const patchSettings=change=>{try{setData(current=>updateFinancialSettingsCommand(current,change,currentUser));setMessage(serverManaged?'Изменение отправлено на сервер':'Настройки сохранены в журнале изменений')}catch(error){setMessage(error?.message||'Не удалось изменить настройки')}};
 return<main className="system-page"><header className="system-head"><div><span>Доступ директора</span><h1>Система и данные</h1><p>{serverManaged?'Общее рабочее пространство PostgreSQL, пользователи и серверная синхронизация.':'Локальное хранение, восстановление и параметры демонстрационного режима.'}</p></div>{serverManaged?<Cloud/>:<ShieldCheck/>}</header>
 {storageError&&<div className="system-alert"><AlertTriangle/><div><b>{serverManaged?'Ошибка синхронизации':'Ошибка сохранения'}</b><span>{storageError}</span></div></div>}{message&&<div className="system-message">{message}</div>}
 <section className="system-stats"><article><Database/><div><span>Версия схемы</span><b>{data.schemaVersion}</b></div></article><article><Save/><div><span>Режим данных</span><b>{serverManaged?'Сервер':'Локально'}</b></div></article><article><HardDriveDownload/><div><span>Сделки / позиции</span><b>{data.works?.length||0} / {data.positions?.length||0}</b></div></article><article><ShieldCheck/><div><span>Пользователи</span><b>{data.users?.length||0}</b></div></article></section>
 <section className="system-finance"><div className="mini-title"><Settings2/>Базовые параметры</div><div className="system-form"><label>Валюта<select value={data.settings?.currency||'RUB'} onChange={event=>patchSettings({currency:event.target.value})}><option value="RUB">RUB — ₽</option><option value="USD">USD — $</option><option value="EUR">EUR — €</option><option value="ILS">ILS — ₪</option></select></label><label>НДС, %<input type="number" min="0" max="100" value={data.settings?.vatRate??20} onChange={event=>patchSettings({vatRate:event.target.value})}/></label><label>Целевая маржа, %<input type="number" min="0" max="100" value={data.settings?.targetMargin??15} onChange={event=>patchSettings({targetMargin:event.target.value})}/></label></div><p>Финансовые правила сделки настраиваются в разделе «Финансовый центр».</p></section>
 {serverManaged&&<><UserManagement currentUser={currentUser} onChanged={onServerChanged}/><ServerOperations data={data} onServerChanged={onServerChanged}/></>}
 <section className="system-grid"><article><Download/><div><h2>Скачать экспорт</h2><p>JSON-копия текущего состояния для контроля и переноса.</p></div><button className="primary" onClick={download}>Скачать</button></article>{serverManaged?<><article><Cloud/><div><h2>Серверное хранение</h2><p>Рабочие данные сохраняются в PostgreSQL с ревизиями и журналом изменений.</p></div><button disabled>Подключено</button></article><article><ShieldCheck/><div><h2>Восстановление базы</h2><p>Полное восстановление выполняется из серверной резервной копии, а не из браузера.</p></div><button disabled>Через администратора</button></article></>:<><article><FileUp/><div><h2>Восстановить из файла</h2><p>Структура данных проверяется, старые версии обновляются автоматически.</p></div><input ref={inputRef} type="file" accept="application/json,.json" hidden onChange={event=>upload(event.target.files?.[0])}/><button onClick={()=>inputRef.current?.click()}>Выбрать файл</button></article><article><HardDriveDownload/><div><h2>Локальная точка восстановления</h2><p>Создайте контрольную копию перед крупным изменением данных.</p></div><button onClick={()=>{createSnapshot();setMessage('Локальная точка восстановления создана')}}>Создать</button></article><article><RefreshCcw/><div><h2>Вернуться к копии</h2><p>Восстановить последнюю локальную контрольную точку.</p></div><button onClick={restore}>Восстановить</button></article></>}</section>
 {!serverManaged&&<section className="system-danger"><AlertTriangle/><div><h2>Сброс демонстрационных данных</h2><p>Текущие локальные данные заменятся исходным демо-набором.</p></div><button onClick={clear}>Сбросить</button></section>}</main>;
}
