import React,{useEffect,useState}from'react';
import{Plus,ShieldCheck,UserRound,Users}from'lucide-react';
import{createUser,listUsers,updateUser}from'../api/client.js';
import'./user-management.css';

const blank=()=>({name:'',email:'',role:'manager',password:''});

export function UserManagement({currentUser,onChanged}){
 const[users,setUsers]=useState([]),[form,setForm]=useState(blank),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=async()=>{setLoading(true);try{const result=await listUsers();setUsers(result.users||[]);setMessage('')}catch(error){setMessage(error?.message||'Не удалось загрузить пользователей')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const add=async event=>{event.preventDefault();if(busy)return;setBusy(true);try{await createUser(form);setForm(blank());setMessage('Пользователь создан');await load();onChanged?.()}catch(error){setMessage(error?.message||'Не удалось создать пользователя')}finally{setBusy(false)}};
 const patch=async(id,change)=>{try{await updateUser(id,change);setMessage('Доступ обновлён');await load();onChanged?.()}catch(error){setMessage(error?.message||'Не удалось изменить пользователя')}};
 return<section className="user-management"><header><div><Users/><div><span>Доступ к системе</span><h2>Пользователи</h2><p>Директор создаёт учётные записи и назначает рабочую роль. Переключение роли внутри приложения отключено.</p></div></div><b>{users.length}</b></header>{message&&<div className="user-message">{message}</div>}<form onSubmit={add}><label>Имя<input value={form.name} onChange={event=>setForm({...form,name:event.target.value})} placeholder="Иван Иванов" required/></label><label>Email<input type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})} placeholder="manager@company.ru" required/></label><label>Роль<select value={form.role} onChange={event=>setForm({...form,role:event.target.value})}><option value="manager">Менеджер</option><option value="director">Директор</option></select></label><label>Первичный пароль<input type="password" minLength="10" value={form.password} onChange={event=>setForm({...form,password:event.target.value})} placeholder="Не менее 10 символов" required/></label><button className="primary" disabled={busy}><Plus/>{busy?'Создание…':'Создать пользователя'}</button></form><div className="user-list">{loading?<div className="user-empty">Загрузка пользователей…</div>:users.map(user=><article key={user.id} className={!user.active?'disabled':''}><div className="user-avatar">{user.role==='director'?<ShieldCheck/>:<UserRound/>}</div><div className="user-main"><b>{user.name}</b><span>{user.email}</span></div><label>Роль<select value={user.role} disabled={user.id===currentUser?.id} onChange={event=>patch(user.id,{role:event.target.value})}><option value="manager">Менеджер</option><option value="director">Директор</option></select></label><label className="user-active"><input type="checkbox" checked={user.active} disabled={user.id===currentUser?.id} onChange={event=>patch(user.id,{active:event.target.checked})}/><span>{user.active?'Активен':'Отключён'}</span></label></article>)}{!loading&&!users.length&&<div className="user-empty">Пользователи не найдены</div>}</div></section>;
}
