import React,{useEffect,useMemo,useState}from'react';
import{AlertTriangle,BarChart3,Boxes,CheckCircle2,CircleDollarSign,Clock3,FileText,FileUp,Files,History,Plus,Search,ShieldAlert,ShieldCheck,Table2,Truck,UserRound,UsersRound}from'lucide-react';
import{daysLeft,money,pct}from'../domain/workspace.js';
import{addPositionCommand}from'../domain/commands.js';
import{DocumentsView}from'./DocumentsView.jsx';
import{TimelineView}from'./TimelineView.jsx';
import{SpecificationImport}from'./SpecificationImport.jsx';
import{SupplierRequestsView}from'./SupplierRequestsView.jsx';
import{QuoteView}from'./QuoteView.jsx';

const stages=['Новая','Анализ','Поиск поставщиков','Ожидаем ТКП','Расчет','КП готовится','КП отправлено','Переговоры','Договор','Производство','Отгрузка','Закрыто успешно'];
const navItems=[{id:'overview',label:'Обзор',Icon:BarChart3,ready:true},{id:'positions',label:'Позиции',Icon:Table2,ready:true},{id:'suppliers',label:'Запросы ТКП',Icon:UsersRound,ready:true},{id:'quote',label:'КП',Icon:FileText,ready:true},{id:'documents',label:'Документы',Icon:Files,ready:true},{id:'import',label:'Импорт Excel',Icon:FileUp,ready:true},{id:'production',label:'Производство',Icon:Boxes,ready:false},{id:'logistics',label:'Логистика',Icon:Truck,ready:false},{id:'history',label:'История',Icon:History,ready:true}];
const deadlineLabel=value=>{const days=daysLeft(value);if(days===999)return'срок не указан';if(days<0)return`просрочен на ${Math.abs(days)} дн.`;if(days===0)return'сегодня';if(days===1)return'завтра';return`через ${days} дн.`};

export function WorkspaceView({work,data,setData,selectedId,setSelectedId,currentUser,initialTab=''}){
 const isDirector=currentUser?.role==='director';
 const[draft,setDraft]=useState({group:'',name:'',qty:1,unit:'шт'}),[tab,setTab]=useState(isDirector?'overview':'positions'),[error,setError]=useState(''),[query,setQuery]=useState(''),currency=data.settings?.currency||'RUB';
 useEffect(()=>{const requested=navItems.some(item=>item.ready&&item.id===initialTab)?initialTab:(isDirector?'overview':'positions');setTab(isDirector&&requested==='import'?'overview':requested);setSelectedId(null)},[work.id,initialTab,isDirector]);
 const docs=(data.documents||[]).filter(item=>item.workId===work.id),events=(data.events||[]).filter(item=>item.workId===work.id),imports=(data.specificationImports||[]).filter(item=>item.workId===work.id&&!item.rolledBackAt),supplierRequests=(data.supplierRequests||[]).filter(item=>item.workId===work.id),quotes=(data.quotes||[]).filter(item=>item.workId===work.id);
 const supplierCount=new Set(work.positions.flatMap(position=>position.offers.map(offer=>offer.supplierId).filter(Boolean))).size;
 const stageIndex=Math.max(0,stages.findIndex(stage=>stage===work.state)),riskPositions=work.positions.filter(position=>position.warnings.length);
 const filtered=useMemo(()=>work.positions.filter(position=>`${position.name} ${position.group} ${position.model||''}`.toLowerCase().includes(query.toLowerCase())),[work.positions,query]);
 const addPosition=()=>{if(isDirector)return;try{setData(current=>addPositionCommand(current,work.id,draft,currentUser).state);setDraft({group:'',name:'',qty:1,unit:'шт'});setError('')}catch(exception){setError(exception?.message||'Не удалось добавить позицию')}};
 const selectTab=item=>{if(!item.ready)return;setSelectedId(null);setTab(item.id)};
 const openPosition=positionId=>{setTab('positions');setSelectedId(positionId||null)};
 const counts={positions:work.positions.length,suppliers:supplierRequests.length,quote:quotes.length,documents:docs.length,import:imports.length,production:work.positions.filter(p=>['Заказано','В производстве','Готово','Частично отгружено','Отгружено'].includes(p.status)).length,logistics:work.positions.filter(p=>(p.batches||[]).length).length,history:events.length};
 return <main className="tender-v2">
  <div className={`role-mode-banner ${isDirector?'director':'manager'}`}>{isDirector?<ShieldCheck/>:<UserRound/>}<div><b>{isDirector?'Режим директора: контроль сделки':'Режим менеджера: ведение сделки'}</b> · {isDirector?'операционный ввод заблокирован, доступны показатели, риски и история':'доступен ввод позиций, поставщиков, сроков и фактических данных'}</div></div>
  <header className="tender-v2-head"><div><div className="tender-kicker">{isDirector?'Контроль директора':'Рабочая карточка менеджера'} · {work.code} · {work.source}</div><h1>{work.customer} · {work.title}</h1><p>{work.objectName||'Объект не указан'} · менеджер {work.manager||'не назначен'} · дедлайн {deadlineLabel(work.deadline)}</p></div>{!isDirector&&<div className="tender-head-actions"><button disabled title="Появится после подключения сценариев">Быстрые действия</button><button className="primary" onClick={()=>setTab('positions')}><Plus/>Добавить позицию</button></div>}</header>
  <section className="tender-kpis"><article><span>Прогресс работы</span><b>{work.progress}%</b><div className="mini-progress"><i style={{width:`${work.progress}%`}}/></div><small>готовность сделки</small></article><article><span>Чистая прибыль</span><b>{money(work.totals.netProfit,currency)}</b><small>ожидаемый результат</small></article><article><span>Валовая прибыль</span><b>{money(work.totals.grossProfit,currency)}</b><small>до налогов и премий</small></article><article><span>Маржа</span><b>{pct(work.positions.length?work.positions.reduce((sum,p)=>sum+Number(p.grossMargin||0),0)/work.positions.length:0)}</b><small>средняя по позициям</small></article><article><span>Риск</span><b className={riskPositions.length?'warn-text':'good'}>{riskPositions.length?'Требует внимания':'Низкий'}</b><small>{riskPositions.length} проблемных позиций</small></article><article><span>Следующее действие</span><b className="next-action">{work.nextAction}</b><small>{work.blockers} блокеров</small></article></section>
  <section className="tender-stages">{stages.map((stage,index)=><div key={stage} className={index<stageIndex?'done':index===stageIndex?'active':''}><span>{index<stageIndex?<CheckCircle2/>:index+1}</span><small>{stage}</small></div>)}</section>
  <div className="tender-body">
   <aside className="tender-local-nav">{navItems.map(item=><button key={item.id} disabled={!item.ready} title={item.ready?'':`${item.label}: модуль ещё не подключён`} className={`${tab===item.id?'active':''} ${!item.ready?'coming-soon':''}`} onClick={()=>selectTab(item)}><item.Icon/><span>{item.label}</span><em>{item.ready?(counts[item.id]??''):'скоро'}</em></button>)}</aside>
   <section className="tender-workarea">
    {error&&<div className="inline-error">{error}</div>}
    {isDirector&&<div className="director-readonly-note">Директор просматривает сделку в режиме контроля. Изменения вносит ответственный менеджер.</div>}
    {tab==='overview'&&<div className="overview-grid"><article className="overview-card"><h3>Что осталось сделать</h3>{work.positions.length?work.positions.slice(0,6).map(position=><div className="todo-line" key={position.id}><span>{position.nextStep}</span><b>{position.name}</b></div>):<div className="empty-note">Позиции ещё не добавлены. Менеджеру нужно импортировать спецификацию или создать первую позицию.</div>}</article><article className="overview-card"><h3>Ключевые показатели</h3><div className="overview-metric"><span>Позиции</span><b>{work.positions.length}</b></div><div className="overview-metric"><span>Поставщики</span><b>{supplierCount}</b></div><div className="overview-metric"><span>Документы</span><b>{docs.length}</b></div><div className="overview-metric"><span>События</span><b>{events.length}</b></div></article></div>}
    {tab==='positions'&&<><div className="positions-toolbar"><label><Search/><input placeholder="Поиск по позициям" value={query} onChange={event=>setQuery(event.target.value)}/></label><select disabled><option>Все группы</option></select><select disabled><option>Все статусы</option></select><button disabled>Фильтры</button>{!isDirector&&<button disabled>Массовые действия</button>}</div>{!isDirector&&<div className="quick-add"><input placeholder="Группа" value={draft.group} onChange={e=>setDraft({...draft,group:e.target.value})}/><input className="grow" placeholder="Наименование позиции" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><input aria-label="Количество" type="number" min="0.0001" value={draft.qty} onChange={e=>setDraft({...draft,qty:e.target.value})}/><input aria-label="Единица измерения" value={draft.unit} onChange={e=>setDraft({...draft,unit:e.target.value})}/><button className="primary" disabled={!String(draft.name).trim()} onClick={addPosition}><Plus/>Добавить</button></div>}<div className="tender-table"><table><thead><tr><th>№</th><th>Наименование</th><th>Кол-во</th><th>Лучшая цена</th><th>Поставщик</th><th>Следующий шаг</th><th>Маржа</th><th></th></tr></thead><tbody>{filtered.map(position=><tr key={position.id} className={`${selectedId===position.id?'selected':''} ${position.warnings.length?'risk':''} ${isDirector?'readonly':''}`} onClick={()=>!isDirector&&setSelectedId(position.id)}><td>{position.rowNo}</td><td><b>{position.name}</b><small>{position.group}{position.model?` · ${position.model}`:''}</small></td><td>{position.qty} {position.unit}</td><td>{position.selected?money(position.selected.price,currency):'—'}</td><td>{position.selected?.supplier?.name||'—'}</td><td><span className={`status-pill ${position.warnings.length?'warning':'ok'}`}>{position.nextStep}</span></td><td className={position.grossMargin!=null&&position.grossMargin<Number(data.settings?.targetMargin??15)?'warn-text':'good'}>{pct(position.grossMargin)}</td><td>{isDirector?'':'›'}</td></tr>)}</tbody></table>{!filtered.length&&<div className="empty-note">{work.positions.length?'По запросу ничего не найдено.':'Добавьте первую позицию или импортируйте Excel-спецификацию.'}</div>}</div></>}
    {tab==='suppliers'&&<SupplierRequestsView work={work} data={data} setData={setData} currentUser={currentUser} onSelectPosition={openPosition}/>}
    {tab==='quote'&&<QuoteView work={work} data={data} setData={setData} currentUser={currentUser}/>} 
    {tab==='import'&&(isDirector?<div className="module-placeholder"><ShieldCheck/><h2>Импорт доступен менеджеру</h2><p>Директор контролирует результат и историю изменений, но не изменяет спецификацию сделки.</p></div>:<SpecificationImport work={work} data={data} setData={setData} currentUser={currentUser} onImported={openPosition}/>)}
    {tab==='documents'&&<DocumentsView work={work} data={data} setData={setData} currentUser={currentUser}/>} 
    {tab==='history'&&<TimelineView work={work} data={data} setData={setData} currentUser={currentUser}/>} 
    {['production','logistics'].includes(tab)&&<div className="module-placeholder"><CircleDollarSign/><h2>Модуль готовится</h2><p>Раздел пока не подключён и не должен использоваться в рабочем сценарии.</p></div>}
    {tab==='positions'&&<div className="tender-bottom-grid"><article><h3><ShieldAlert/>Риски по сделке</h3>{riskPositions.slice(0,3).map(position=><button key={position.id} onClick={()=>!isDirector&&setSelectedId(position.id)}><AlertTriangle/><div><b>{position.name}</b><span>{position.warnings.join(', ')}</span></div></button>)}{!riskPositions.length&&<div className="all-good"><CheckCircle2/>Критических рисков нет</div>}</article><article><h3><Files/>Ключевые документы</h3>{docs.slice(0,3).map(doc=><div className="doc-line" key={doc.id}><FileText/><div><b>{doc.title||doc.name}</b><span>{doc.type}</span></div></div>)}{!docs.length&&<div className="empty-note">Документы не загружены</div>}</article><article><h3><History/>Последние события</h3>{events.slice(0,3).map(event=><div className="event-line" key={event.id}><Clock3/><div><b>{event.title}</b><span>{event.author||''}</span></div></div>)}{!events.length&&<div className="empty-note">История пока пуста</div>}</article></div>}
   </section>
  </div>
 </main>;
}
