import React from'react';
import{BriefcaseBusiness,Building2,Calculator,Compass,LayoutDashboard,Landmark,Plus,Search,Settings,ShieldCheck,TrendingUp,Zap}from'lucide-react';
import{daysLeft}from'../domain/workspace.js';

const deadlineLabel=value=>{const days=daysLeft(value);if(days<0)return`проср. ${Math.abs(days)} дн.`;if(days===0)return'сегодня';if(days===1)return'завтра';return days===999?'без срока':`${days} дн.`};

export function WorkRail({works,activeId,onSelect,onNew,query,setQuery,section,setSection,currentUser,isAdmin}){
 const isDirector=isAdmin||['director','admin','head'].includes(currentUser?.role),roleLabel=isDirector?'Директор':'Менеджер';
 return <aside className="rail">
  <div className="brand"><div className="logo">PA</div><div><b>PromApparat</b><span>Opportunity OS</span></div></div>
  <div className="rail-nav"><button className={section==='opportunities'?'active':''} onClick={()=>setSection('opportunities')}><Compass/>Поиск и возможности</button><button className={section==='dashboard'?'active':''} onClick={()=>setSection('dashboard')}><LayoutDashboard/>Рабочий день</button><button className={section==='works'?'active':''} onClick={()=>setSection('works')}><BriefcaseBusiness/>{isDirector?'Все проекты':'Мои проекты'}</button><button className={section==='suppliers'?'active':''} onClick={()=>setSection('suppliers')}><Building2/>Поставщики</button>{isDirector&&<><div className="rail-divider"><span>Управление директора</span></div><button className={section==='director'?'active':''} onClick={()=>setSection('director')}><TrendingUp/>Бизнес-аналитика <ShieldCheck size={13}/></button><button className={section==='finance'?'active':''} onClick={()=>setSection('finance')}><Landmark/>Финансовый центр <ShieldCheck size={13}/></button><button className={section==='formulas'?'active':''} onClick={()=>setSection('formulas')}><Calculator/>Конструктор формул <ShieldCheck size={13}/></button><button className={section==='system'?'active':''} onClick={()=>setSection('system')}><Settings/>Система <ShieldCheck size={13}/></button></>}</div>
  {section==='works'&&<><button className="primary full" onClick={onNew}><Plus size={16}/> Новый проект</button><label className="search"><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Поиск проектов"/></label><div className="work-list">{works.map(work=><button key={work.id} className={`work-card ${activeId===work.id?'active':''}`} onClick={()=>onSelect(work.id)}><div className="work-top"><span>{work.code}</span><em>{deadlineLabel(work.deadline)}</em></div><strong>{work.customer}</strong><small>{work.title}</small><div className="progress"><i style={{width:`${work.progress}%`}}/></div><div className="work-meta"><span>{work.positions.length} поз.</span><span>{work.progress}%</span></div><p><Zap size={13}/>{work.nextAction}</p></button>)}</div></>}
  {section==='opportunities'&&<div className="rail-section-note"><Compass/><b>Поиск тендеров</b><span>Площадки, найденные закупки, оценка и перевод в проект.</span></div>}
  {section==='dashboard'&&<div className="rail-section-note"><LayoutDashboard/><b>Рабочий день</b><span>Текущие действия, сроки и риски.</span></div>}
  {section==='director'&&isDirector&&<div className="rail-section-note"><TrendingUp/><b>Бизнес директора</b><span>Все этапы, деньги, эффективность и риски.</span></div>}
  {section==='finance'&&isDirector&&<div className="rail-section-note"><Landmark/><b>Финансовая модель</b><span>Премии, налоги, кредиты, гарантии, дивиденды и маржинальность.</span></div>}
  {section==='formulas'&&isDirector&&<div className="rail-section-note"><ShieldCheck/><b>Только директор</b><span>Формулы и версии расчетных правил.</span></div>}
  <div className="rail-user"><div className="rail-user-avatar">{String(currentUser?.name||'П').slice(0,1).toUpperCase()}</div><div><b>{currentUser?.name||'Пользователь'}</b><span>{roleLabel}</span></div></div>
 </aside>;
}