import React,{useMemo,useState}from'react';
import{AlertTriangle,BarChart3,Boxes,CheckCircle2,CircleDollarSign,Clock3,FileText,FileUp,Files,History,Plus,Search,ShieldAlert,ShieldCheck,Table2,Truck,UserRound,UsersRound}from'lucide-react';
import{daysLeft,money,pct}from'../domain/workspace.js';
import{addPositionCommand}from'../domain/commands.js';
import{DocumentsView}from'./DocumentsView.jsx';
import{TimelineView}from'./TimelineView.jsx';
import{SpecificationImport}from'./SpecificationImport.jsx';

const stages=['Новая','Анализ','Поиск поставщиков','Ожидаем ТКП','Расчет','КП готовится','КП отправлено','Переговоры','Договор','Производство','Отгрузка','Закрыто успешно'];
const navItems=[['overview','Обзор',BarChart3],['positions','Позиции',Table2],['suppliers','Поставщики',UsersRound],['quote','КП',FileText],['documents','Документы',Files],['import','Импорт Excel',FileUp],['production','Производство',Boxes],['logistics','Логистика',Truck],['history','История',History]];

export function WorkspaceView({work,data,setData,selectedId,setSelectedId,currentUser}){
 const isDirector=currentUser?.role==='director';
 const[draft,setDraft]=useState({group:'',name:'',qty:1,unit:'шт'}),[tab,setTab]=useState(isDirector?'overview':'positions'),[error,setError]=useState(''),[query,setQuery]=useState(''),currency=data.settings?.currency||'RUB';
 const docs=(data.documents||[]).filter(item=>item.workId===work.id),events=(data.events||[]).filter(item=>item.workId===work.id),imports=(data.specificationImports||[]).filter(item=>item.workId===work.id&&!item.rolledBackAt);
 const supplierCount=new Set(work.positions.flatMap(position=>position.offers.map(offer=>offer.supplierId).filter(Boolean))).size;
 const stageIndex=Math.max(0,stages.findIndex(stage=>stage===work.state));
 const remaining=Math.max(0,daysLeft(work.deadline));
 const riskPositions=work.positions.filter(position=>position.warnings.length);
 const filtered=useMemo(()=>work.positions.filter(position=>`${position.name} ${position.group} ${position.model||''}`.toLowerCase().includes(query.toLowerCase())),[work.positions,query]);
 const addPosition=()=>{if(isDirector)return;try{setData(current=>addPositionCommand(current,work.id,draft,currentUser).state);setDraft({group:'',name:'',qty:1,unit:'шт'});setError('')}catch(exception){setError(exception?.message||'Не удалось добавить позицию')}};
 const selectTab=value=>{setSelectedId(null);setTab(value)};
 const counts={positions:work.positions.length,suppliers:supplierCount,quote:0,documents:docs.length,import:imports.length,production:work.positions.filter(p=>['Заказано','В производстве','Готово','Частично отгружено','Отгружено'].includes(p.status)).length,logistics:work.positions.filter(p=>(p.batches||[]).length).length,history:events.length};
 return <main className="tender-v2">
  <div className={`role-mode-banner ${isDirector?'director':'manager'}`}>{isDirector?<ShieldCheck/>:<UserRound/>}<div><b>{isDirector?'Режим директора: контроль сделки':'Режим менеджера: ведение сделки'}</b> · {isDirector?'операционный ввод заблокирован, доступны показатели, риски и история':'доступен ввод позиций, поставщиков, сроков и фактических данных'}</div></div>
  <header className="tender-v2-head"><div><div className="tender-kicker">{isDirector?'Контроль директора':'Рабочая карточка менеджера'} · {work.code} · {work.source}</div><h1>{work.customer} · {work.title}</h1><p>{work.objectName||'Объект не указан'} · менеджер {work.manager||'не назначен'} · дедлайн через {remaining} дн.</p></div>{!isDirector&&<div className="tender-head-actions"><button>Быстрые действия</button><button className="primary"><Plus/>Создать</button></div>}</header>
  <section className="tender-kpis"><article><span>Прогресс работы</span><b>{work.progress}%</b><div className="mini-progress"><i style={{width:`${work.progress}%`}}/></div><small>готовность к дедлайну</small></article><article><span>Чистая прибыль</span><b>{money(work.totals.netProfit,currency)}</b><small>ожидаемый результат</small></article><article><span>Валовая прибыль</span><b>{money(work.totals.grossProfit,currency)}</b><small>до налогов и премий</small></article><article><span>Маржа</span><b>{pct(work.positions.length?work.positions.reduce((sum,p)=>sum+Number(p.grossMargin||0),0)/work.positions.length:0)}</b><small>средняя по позициям</small></article><article><span>Риск</span><b className={riskPositions.length?'warn-text':'good'}>{riskPositions.length?'Средний':'Низкий'}</b><small>{riskPositions.length} проблемных позиций</small></article><article><span>Следующее действие</span><b className="next-action">{work.nextAction}</b><small>{work.blockers} блокеров</small></article></section>
  <section className="tender-stages">{stages.map((stage,index)=><div key={stage} className={index<stageIndex?'done':index===stageIndex?'active':''}><span>{index<stageIndex?<CheckCircle2/>:index+1}</span><small>{stage}</small></div>)}</section>
  <div className="tender-body">
   <aside className="tender-local-nav">{navItems.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>selectTab(id)}><Icon/><span>{label}</span>{counts[id]!=null&&<em>{counts[id]}</em>}</button>)}</aside>
   <section className="tender-workarea">
    {error&&<div className="inline-error">{error}</div>}
    {isDirector&&<div className="director-readonly-note">Директор просматривает сделку в режиме контроля. Изменения вносит ответственный менеджер.</div>}
    {tab==='overview'&&<div className="overview-grid"><article className="overview-card"><h3>Что осталось сделать</h3>{work.positions.slice(0,6).map(position=><div className="todo-line" key={position.id}><span>{position.nextStep}</span><b>{position.name}</b></div>)}</article><article className="overview-card"><h3>Ключевые показатели</h3><div className="overview-metric"><span>Позиции</span><b>{work.positions.length}</b></div><div className="overview-metric"><span>Поставщики</span><b>{supplierCount}</b></div><div className="overview-metric"><span>Документы</span><b>{docs.length}</b></div><div className="overview-metric"><span>События</span><b>{events.length}</b></div></article></div>}
    {tab==='positions'&&<><div className="positions-toolbar"><label><Search/><input placeholder="Поиск по позициям" value={query} onChange={event=>setQuery(event.target.value)}/></label><select><option>Все группы</option></select><select><option>Все статусы</option></select><button>Фильтры</button>{!isDirector&&<button>Массовые действия</button>}</div>{!isDirector&&<div className="quick-add"><input placeholder="Группа" value={draft.group} onChange={e=>setDraft({...draft,group:e.target.value})}/><input className="grow" placeholder="Новая позиция" value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><input type="number" min="0.0001" value={draft.qty} onChange={e=>setDraft({...draft,qty:e.target.value})}/><input value={draft.unit} onChange={e=>setDraft({...draft,unit:e.target.value})}/><button className="primary" onClick={addPosition}><Plus/>Добавить</button></div>}<div className="tender-table"><table><thead><tr><th>№</th><th>Наименование</th><th>Кол-во</th><th>Лучшая цена</th><th>Поставщик</th><th>Статус</th><th>Маржа</th><th></th></tr></thead><tbody>{filtered.map(position=><tr key={position.id} className={`${selectedId===position.id?'selected':''} ${position.warnings.length?'risk':''} ${isDirector?'readonly':''}`} onClick={()=>!isDirector&&setSelectedId(position.id)}><td>{position.rowNo}</td><td><b>{position.name}</b><small>{position.group}{position.model?` · ${position.model}`:''}</small></td><td>{position.qty} {position.unit}</td><td>{position.selected?money(position.selected.price,currency):'—'}</td><td>{position.selected?.supplier?.name||'—'}</td><td><span className={`status-pill ${position.warnings.length?'warning':'ok'}`}>{position.nextStep}</span></td><td className={position.grossMargin!=null&&position.grossMargin<Number(data.settings?.targetMargin??15)?'warn-text':'good'}>{pct(position.grossMargin)}</td><td>{isDirector?'':'›'}</td></tr>)}</tbody></table></div></>}
    {tab==='import'&&(isDirector?<div className="module-placeholder"><ShieldCheck/><h2>Импорт доступен менеджеру</h2><p>Директор контролирует результат и историю изменений, но не изменяет спецификацию сделки.</p></div>:<SpecificationImport work={work} data={data} setData={setData} currentUser={currentUser}/>)}
    {tab==='documents'&&<DocumentsView work={work} data={data} setData={setData} currentUser={currentUser}/>} 
    {tab==='history'&&<TimelineView work={work} data={data} setData={setData} currentUser={currentUser}/>} 
    {['suppliers','quote','production','logistics'].includes(tab)&&<div className="module-placeholder"><CircleDollarSign/><h2>{navItems.find(item=>item[0]===tab)?.[1]}</h2><p>{isDirector?'Контроль данных, сроков и отклонений по выбранному разделу сделки.':'Раздел подключается к существующим данным сделки. Каркас и навигация уже работают.'}</p></div>}
    {tab==='positions'&&<div className="tender-bottom-grid"><article><h3><ShieldAlert/>Риски по сделке</h3>{riskPositions.slice(0,3).map(position=><button key={position.id} onClick={()=>!isDirector&&setSelectedId(position.id)}><AlertTriangle/><div><b>{position.name}</b><span>{position.warnings.join(', ')}</span></div></button>)}{!riskPositions.length&&<div className="all-good"><CheckCircle2/>Критических рисков нет</div>}</article><article><h3><Files/>Ключевые документы</h3>{docs.slice(0,3).map(doc=><div className="doc-line" key={doc.id}><FileText/><div><b>{doc.title||doc.name}</b><span>{doc.type}</span></div></div>)}{!docs.length&&<div className="empty-note">Документы не загружены</div>}</article><article><h3><History/>Последние события</h3>{events.slice(0,3).map(event=><div className="event-line" key={event.id}><Clock3/><div><b>{event.title}</b><span>{event.author||''}</span></div></div>)}</article></div>}
   </section>
  </div>
 </main>;
}