import{describe,expect,it}from'vitest';
import{createDemoWorkspace}from'./workspace.js';
import{acceptOpportunity,beginPlatformCheck,bulkUpdateOpportunities,completePlatformCheck,createOpportunity,rejectOpportunity,updateOpportunityFields,updateOpportunityQualification}from'./opportunities.js';

describe('Opportunity Engine',()=>{
 it('records a complete platform check session',()=>{const state=createDemoWorkspace(),platform=state.platforms.find(item=>!item.checkedToday),started=beginPlatformCheck(state,platform.id,state.currentUser),next=completePlatformCheck(started,platform.id,{reviewedCount:37,foundCount:4,notes:'Проверено'},state.currentUser),updated=next.platforms.find(item=>item.id===platform.id);expect(updated.checkedToday).toBe(true);expect(next.platformChecks[0].reviewedCount).toBe(37);expect(next.platformChecks[0].foundCount).toBe(4);expect(next.events[0].entityType).toBe('platform')});
 it('creates and qualifies an opportunity',()=>{const state=createDemoWorkspace(),result=createOpportunity(state,{platformId:state.platforms[0].id,customer:'Заказчик',title:'Клапаны',estimatedAmount:5000000},state.currentUser),qualified=updateOpportunityQualification(result.state,result.opportunity.id,{profileFit:true,manufacturerAvailable:true},state.currentUser),item=qualified.opportunities.find(entry=>entry.id===result.opportunity.id);expect(item.status).toBe('На оценке');expect(item.profileFit).toBe(true);expect(item.manufacturerAvailable).toBe(true)});
 it('rejects duplicate platform numbers',()=>{const state=createDemoWorkspace(),source=state.opportunities[0];expect(()=>createOpportunity(state,{platformId:source.platformId,externalId:source.externalId,customer:'Другой',title:'Дубль'},state.currentUser)).toThrow('уже добавлена')});
 it('updates an opportunity from the spreadsheet',()=>{const state=createDemoWorkspace(),id=state.opportunities[0].id,next=updateOpportunityFields(state,id,{estimatedAmount:17000000,owner:'Петров'},state.currentUser),item=next.opportunities.find(entry=>entry.id===id);expect(item.estimatedAmount).toBe(17000000);expect(item.owner).toBe('Петров');expect(next.events[0].title).toBe('Изменена возможность')});
 it('bulk assigns selected opportunities',()=>{const state=createDemoWorkspace(),ids=state.opportunities.slice(0,2).map(item=>item.id),next=bulkUpdateOpportunities(state,ids,{owner:'Иванов'},state.currentUser);expect(next.opportunities.filter(item=>ids.includes(item.id)).every(item=>item.owner==='Иванов')).toBe(true);expect(next.events[0].title).toBe('Массовое изменение возможностей')});
 it('requires a refusal reason',()=>{const state=createDemoWorkspace();expect(()=>rejectOpportunity(state,state.opportunities[0].id,'','',state.currentUser)).toThrow('Укажите причину отказа')});
 it('converts an opportunity into a linked work',()=>{const state=createDemoWorkspace(),id=state.opportunities[0].id,result=acceptOpportunity(state,id,state.currentUser),opportunity=result.state.opportunities.find(item=>item.id===id),work=result.state.works.find(item=>item.id===opportunity.workId);expect(opportunity.status).toBe('Взята в работу');expect(work.opportunityId).toBe(id);expect(work.customer).toBe(opportunity.customer)});
});
