import{describe,expect,it}from'vitest';
import{migrateWorkspace,validateWorkspace}from'./schema.js';
import{createDemoWorkspace,normalizeWorkspace}from'./workspace.js';

describe('workspace schema',()=>{
 it('migrates old data to v10 with formulas and full workflow collections',()=>{const migrated=migrateWorkspace({works:[],suppliers:[],positions:[]});expect(migrated.schemaVersion).toBe(10);expect(migrated.formulas).toEqual([]);expect(migrated.specificationImports).toEqual([]);expect(migrated.supplierRequests).toEqual([]);expect(migrated.quotes).toEqual([]);expect(migrated.shipments).toEqual([]);expect(migrated.invoices).toEqual([]);expect(migrated.users.length).toBeGreaterThan(0)});
 it('preserves complete manager workflow data during normalization',()=>{const base=normalizeWorkspace(createDemoWorkspace()),payload={...base,supplierRequests:[{id:'r1',workId:'w3',supplierId:'s1',positionIds:['p5']}],quotes:[{id:'q1',workId:'w3'}],shipments:[{id:'sh1',workId:'w3',positionId:'p5'}],invoices:[{id:'i1',workId:'w3',amount:100,payments:[]}]},normalized=normalizeWorkspace(payload);expect(normalized.supplierRequests).toHaveLength(1);expect(normalized.quotes).toHaveLength(1);expect(normalized.shipments).toHaveLength(1);expect(normalized.invoices).toHaveLength(1);expect(validateWorkspace(normalized).ok).toBe(true)});
 it('rejects duplicate published formulas for one role',()=>{const data=normalizeWorkspace(createDemoWorkspace());data.formulas=[{id:'f1',name:'Первая',role:'tax',status:'published',active:true,expression:'grossProfit * 0.2'},{id:'f2',name:'Вторая',role:'tax',status:'published',active:true,expression:'grossProfit * 0.1'}];expect(validateWorkspace(data).errors.some(error=>error.includes('несколько опубликованных'))).toBe(true)});
 it('rejects published formulas that the engine cannot execute',()=>{const data=normalizeWorkspace(createDemoWorkspace());data.formulas=[{id:'f1',name:'Несвязанная',role:'custom',status:'published',active:true,expression:'grossProfit * 0.1'}];expect(validateWorkspace(data).errors.some(error=>error.includes('не подключено к расчетному движку'))).toBe(true)});
 it('rejects invalid published formulas',()=>{const data=normalizeWorkspace(createDemoWorkspace());data.formulas=[{id:'f1',name:'Плохая',role:'tax',status:'published',active:true,expression:'grossProfit + неизвестно'}];expect(validateWorkspace(data).errors.some(error=>error.includes('опубликована с ошибкой'))).toBe(true)});
});
