import{ENGINE_FORMULA_ROLES,normalizeFormula,validateFormula}from'./formulas.js';

export const CURRENT_SCHEMA_VERSION=8;
const arrays=['works','suppliers','positions','documents','tasks','customers','events','formulas','formulaImports','specificationImports','platforms','opportunities','platformChecks','users'];
const ensureArrays=data=>{const next={...data};arrays.forEach(key=>{if(!Array.isArray(next[key]))next[key]=[]});return next};
const migrateV1=data=>ensureArrays({...data,schemaVersion:1});
const migrateV2=data=>ensureArrays({...data,schemaVersion:2,formulas:data.formulas||[],formulaImports:data.formulaImports||[]});
const migrateV3=data=>{const users=data.users?.length?data.users:[{id:'u-admin',name:'Администратор',role:'admin',active:true}];return ensureArrays({...data,schemaVersion:3,users,currentUser:data.currentUser||users[0]})};
const migrateV4=data=>{const now=new Date().toISOString(),sequence=Math.max(0,...(data.works||[]).map(work=>Number(String(work.code||'').match(/(\d+)$/)?.[1]||0))),events=(data.events||[]).map(event=>({entityType:event.entityType||event.type||'work',entityId:event.entityId||event.positionId||event.workId||null,field:event.field||null,oldValue:event.oldValue??null,newValue:event.newValue??null,source:event.source||'ui',actorId:event.actorId||null,...event}));return ensureArrays({...data,schemaVersion:4,events,settings:{currency:'RUB',vatRate:20,targetMargin:15,...data.settings},counters:{workSequence:sequence,...data.counters},meta:{revision:Number(data.meta?.revision||0),updatedAt:data.meta?.updatedAt||now,...data.meta}})};
const migrateV5=data=>ensureArrays({...data,schemaVersion:5,formulas:(data.formulas||[]).map(normalizeFormula),settings:{currency:'RUB',vatRate:20,targetMargin:15,...data.settings}});
const migrateV6=data=>ensureArrays({...data,schemaVersion:6,specificationImports:data.specificationImports||[]});
const migrateV7=data=>ensureArrays({...data,schemaVersion:7,platforms:data.platforms||[],opportunities:data.opportunities||[]});
const migrateV8=data=>ensureArrays({...data,schemaVersion:8,platformChecks:data.platformChecks||[]});
export function migrateWorkspace(raw){let data=raw&&typeof raw==='object'?{...raw}:{},version=Number(data.schemaVersion||0);if(version<1){data=migrateV1(data);version=1}if(version<2){data=migrateV2(data);version=2}if(version<3){data=migrateV3(data);version=3}if(version<4){data=migrateV4(data);version=4}if(version<5){data=migrateV5(data);version=5}if(version<6){data=migrateV6(data);version=6}if(version<7){data=migrateV7(data);version=7}if(version<8){data=migrateV8(data);version=8}return ensureArrays({...data,schemaVersion:CURRENT_SCHEMA_VERSION})}
export function validateWorkspace(data){
 const errors=[];if(!data||typeof data!=='object')errors.push('Корневой объект данных отсутствует');arrays.forEach(key=>{if(!Array.isArray(data?.[key]))errors.push(`${key}: ожидается массив`)});
 const ids=new Set();for(const collection of ['works','suppliers','positions','documents','events','formulas','specificationImports','platforms','opportunities','platformChecks','users'])for(const item of data?.[collection]||[]){if(!item?.id)errors.push(`${collection}: запись без id`);else if(ids.has(`${collection}:${item.id}`))errors.push(`${collection}: повтор id ${item.id}`);else ids.add(`${collection}:${item.id}`)}
 const works=new Map((data?.works||[]).map(item=>[item.id,item])),positions=new Map((data?.positions||[]).map(item=>[item.id,item])),supplierIds=new Set((data?.suppliers||[]).map(item=>item.id)),userIds=new Set((data?.users||[]).map(item=>item.id)),platformIds=new Set((data?.platforms||[]).map(item=>item.id));
 for(const position of data?.positions||[]){if(!position.workId)errors.push(`Позиция ${position.id}: нет workId`);else if(!works.has(position.workId))errors.push(`Позиция ${position.id}: работа ${position.workId} не найдена`);if(Number(position.qty||0)<0)errors.push(`Позиция ${position.id}: отрицательное количество`);const selected=(position.offers||[]).filter(offer=>offer.selected);if(selected.length>1)errors.push(`Позиция ${position.id}: выбрано несколько предложений`);for(const offer of position.offers||[]){if(offer.supplierId&&!supplierIds.has(offer.supplierId))errors.push(`Предложение ${offer.id}: поставщик ${offer.supplierId} не найден`);for(const field of ['price','productionDays','deliveryDays'])if(offer[field]!==''&&Number(offer[field]||0)<0)errors.push(`Предложение ${offer.id}: отрицательное значение ${field}`)}let batchTotal=0;for(const batch of position.batches||[]){const qty=Number(batch.qty||0);batchTotal+=qty;if(qty<0)errors.push(`Партия ${batch.id}: отрицательное количество`)}if(batchTotal>Number(position.qty||0))errors.push(`Позиция ${position.id}: сумма партий превышает количество`)}
 for(const document of data?.documents||[]){if(!works.has(document.workId))errors.push(`Документ ${document.id}: работа ${document.workId} не найдена`);if(document.positionId){const position=positions.get(document.positionId);if(!position)errors.push(`Документ ${document.id}: позиция ${document.positionId} не найдена`);else if(position.workId!==document.workId)errors.push(`Документ ${document.id}: позиция относится к другой работе`)}}
 for(const activity of data?.events||[]){if(activity.workId&&!works.has(activity.workId))errors.push(`Событие ${activity.id}: работа ${activity.workId} не найдена`);if(activity.positionId){const position=positions.get(activity.positionId);if(!position)errors.push(`Событие ${activity.id}: позиция ${activity.positionId} не найдена`);else if(activity.workId&&position.workId!==activity.workId)errors.push(`Событие ${activity.id}: позиция относится к другой работе`)}}
 for(const item of data?.specificationImports||[]){if(!works.has(item.workId))errors.push(`Импорт ${item.id}: работа ${item.workId} не найдена`);if(!Array.isArray(item.positionIds))errors.push(`Импорт ${item.id}: positionIds должен быть массивом`);for(const id of item.positionIds||[])if(!item.rolledBackAt&&!positions.has(id))errors.push(`Импорт ${item.id}: позиция ${id} не найдена`)}
 for(const opportunity of data?.opportunities||[]){if(opportunity.platformId&&!platformIds.has(opportunity.platformId))errors.push(`Возможность ${opportunity.id}: площадка ${opportunity.platformId} не найдена`);if(opportunity.workId&&!works.has(opportunity.workId))errors.push(`Возможность ${opportunity.id}: проект ${opportunity.workId} не найден`);if(opportunity.status==='Отказ'&&!opportunity.rejectionReason)errors.push(`Возможность ${opportunity.id}: отсутствует причина отказа`)}
 for(const check of data?.platformChecks||[]){if(!platformIds.has(check.platformId))errors.push(`Проверка ${check.id}: площадка ${check.platformId} не найдена`);if(Number(check.reviewedCount||0)<0||Number(check.foundCount||0)<0)errors.push(`Проверка ${check.id}: отрицательная статистика`)}
 if(data?.currentUser?.id&&!userIds.has(data.currentUser.id))errors.push(`Текущий пользователь ${data.currentUser.id} отсутствует в users`);if(!['RUB','USD','EUR','ILS'].includes(data?.settings?.currency||'RUB'))errors.push('Настройки: неподдерживаемая валюта');for(const field of ['vatRate','targetMargin']){const value=Number(data?.settings?.[field]);if(!Number.isFinite(value)||value<0||value>100)errors.push(`Настройки: неверное значение ${field}`)}
 const activeRoles=new Map();for(const raw of data?.formulas||[]){const formula=normalizeFormula(raw);if(formula.status==='published'&&formula.active){if(!ENGINE_FORMULA_ROLES.has(formula.role))errors.push(`Формула ${formula.name}: назначение ${formula.role} не подключено к расчетному движку`);const check=validateFormula(formula);if(!check.ok)errors.push(`Формула ${formula.name}: опубликована с ошибкой — ${check.error}`);if(activeRoles.has(formula.role))errors.push(`Формулы: несколько опубликованных формул для роли ${formula.role}`);activeRoles.set(formula.role,formula.id)}}
 return{ok:errors.length===0,errors};
}
