import{describe,expect,it}from'vitest';
import{calculatePosition,createDemoWorkspace,deadlineBucket,isPositionClosed,todayPlus}from'./workspace.js';
import{createWorkCommand,nextWorkCode}from'./commands.js';
import{migrateWorkspace,validateWorkspace}from'./schema.js';
import{publishFormula,createManualFormula}from'./formulas.js';
import{calculateCompanyFinance}from'./directorFinance.js';

describe('workspace calculations',()=>{
 it('does not silently choose the first supplier offer',()=>{const position={id:'p',workId:'w',name:'Test',qty:2,salePrice:150,status:'Не начато',offers:[{id:'o',supplierId:'s',price:100,selected:false,hasTkp:true}],batches:[]},result=calculatePosition(position,[{id:'s',name:'Supplier'}],{targetMargin:15,vatRate:20});expect(result.selected).toBeNull();expect(result.purchase).toBeNull();expect(result.profit).toBeNull();expect(result.warnings).toContain('не выбрано предложение')});
 it('calculates gross margin and markup separately',()=>{const position={id:'p',workId:'w',name:'Test',qty:2,salePrice:150,status:'Цена рассчитана',logisticsCost:10,otherCosts:0,offers:[{id:'o',supplierId:'s',price:90,selected:true,hasTkp:true}],batches:[]},result=calculatePosition(position,[{id:'s',name:'Supplier'}],{targetMargin:15,vatRate:20});expect(result.unitCost).toBe(100);expect(result.grossProfit).toBe(100);expect(result.grossMargin).toBeCloseTo(33.333,2);expect(result.markup).toBeCloseTo(50,2)});
 it('applies a published tax formula to net profit',()=>{const formula={...createManualFormula(),role:'tax',expression:'=A2*10%',inputs:[{ref:'A2',label:'Валовая прибыль',value:0}]},published=publishFormula(formula,{id:'director'}),position={id:'p',workId:'w',name:'Test',qty:2,salePrice:150,status:'Цена рассчитана',offers:[{id:'o',supplierId:'s',price:100,selected:true,hasTkp:true}],batches:[]},result=calculatePosition(position,[{id:'s',name:'Supplier'}],{targetMargin:15,vatRate:20},[published]);expect(result.grossProfit).toBe(100);expect(result.taxAmount).toBe(10);expect(result.netProfit).toBe(90);expect(result.appliedFormulaCount).toBe(1)});
 it('marks closed positions as complete',()=>{const position={id:'p',workId:'w',name:'Test',qty:1,salePrice:0,status:'Закрыто',offers:[],batches:[]},result=calculatePosition(position,[],{});expect(isPositionClosed(position)).toBe(true);expect(result.progress).toBe(100);expect(result.nextStep).toBe('Готово')});
 it('separates overdue, today and tomorrow deadlines',()=>{expect(deadlineBucket(todayPlus(-1))).toBe('overdue');expect(deadlineBucket(todayPlus(0))).toBe('today');expect(deadlineBucket(todayPlus(1))).toBe('tomorrow')});
 it('calculates company dividends after deal costs',()=>{const works=[{id:'w',totals:{saleTotal:1000,purchaseTotal:600,grossProfit:400}}],result=calculateCompanyFinance(works,{creditRate:0,bankFeeRate:0,guaranteeRate:0,riskReserveRate:0,fixedOverheadRate:0,taxRate:20,managerBonusRate:5,dividendRate:30});expect(result.netBeforeDividends).toBe(304);expect(result.dividends).toBeCloseTo(91.2);expect(result.retainedProfit).toBeCloseTo(212.8)});
});

describe('schema and commands',()=>{
 it('migrates old data to two roles and validates the result',()=>{const migrated=migrateWorkspace({works:[],positions:[],suppliers:[],users:[{id:'a',name:'Администратор',role:'admin'}],currentUser:{id:'a',name:'Администратор',role:'admin'}});expect(migrated.schemaVersion).toBe(10);expect(migrated.users[0].role).toBe('director');expect(Array.isArray(migrated.platformChecks)).toBe(true);expect(Array.isArray(migrated.supplierRequests)).toBe(true);expect(Array.isArray(migrated.quotes)).toBe(true);expect(Array.isArray(migrated.shipments)).toBe(true);expect(Array.isArray(migrated.invoices)).toBe(true);expect(validateWorkspace(migrated).ok).toBe(true)});
 it('generates a monotonic work number independent of deletion',()=>{const state=createDemoWorkspace();state.counters.workSequence=11;state.works=state.works.slice(0,1);const result=nextWorkCode(state,new Date('2027-01-05T00:00:00Z'));expect(result.code).toBe('PA-2027-0012')});
 it('creates a work and a structured audit event together',()=>{const state=createDemoWorkspace(),actor=state.currentUser,result=createWorkCommand(state,{customer:'Заказчик',title:'Новый тендер',source:'Тендер'},actor);expect(result.state.works[0].id).toBe(result.work.id);expect(result.state.events[0].entityType).toBe('work');expect(result.state.events[0].actorId).toBe(actor.id)});
});