import{CURRENT_SCHEMA_VERSION,migrateWorkspace}from'./schema.js';
import{applyFinancialFormulas}from'./financialEngine.js';

export const STORAGE_KEY='promapparat_workspace';
export const LEGACY_STORAGE_KEYS=['promapparat_workspace_sprint65'];
export const SOURCES=['Тендер','Сайт','Холодный звонок','Повторный клиент','Email','Другое'];
export const WORK_STATES=['Новая','Анализ','Решение участвовать','Расчет','Ожидаем ТКП','КП готовится','КП отправлено','Переговоры','Договор','Производство','Отгрузка','Закрыто успешно','Закрыто проиграно','Архив'];
export const POSITION_STATES=['Не начато','Нужен поставщик','Запрос отправлен','Ожидаем ТКП','ТКП получено','Цена рассчитана','В КП','Заказано','В производстве','Готово досрочно','Готово','Частично отгружено','Отгружено','Закрыто'];
export const CLOSED_WORK_STATES=new Set(['Закрыто успешно','Закрыто проиграно','Архив']);
export const CLOSED_POSITION_STATES=new Set(['Отгружено','Закрыто']);
export const USER_ROLES={ADMIN:'admin',MANAGER:'manager',HEAD:'head'};
export const uid=()=>globalThis.crypto?.randomUUID?.()||String(Date.now()+Math.random());
export const money=(value,currency='RUB')=>new Intl.NumberFormat('ru-RU',{style:'currency',currency:currency||'RUB',maximumFractionDigits:0}).format(Number(value||0));
export const pct=value=>value==null||Number.isNaN(Number(value))?'—':`${Number(value).toFixed(1)}%`;
export const todayPlus=days=>new Date(Date.now()+days*86400000).toISOString().slice(0,10);
export const dateOnly=value=>value?new Date(`${String(value).slice(0,10)}T00:00:00`):null;
export const daysLeft=value=>{const target=dateOnly(value);if(!target)return999;const today=dateOnly(new Date().toISOString());return Math.round((target-today)/86400000)};
export const deadlineBucket=value=>{const days=daysLeft(value);if(days<0)return'overdue';if(days===0)return'today';if(days===1)return'tomorrow';if(days<=7)return'week';return'later'};
export const isWorkClosed=work=>CLOSED_WORK_STATES.has(work?.state);
export const isPositionClosed=position=>CLOSED_POSITION_STATES.has(position?.status);
const minutesAgo=value=>new Date(Date.now()-value*60000).toISOString();

export const createDemoWorkspace=()=>({
 schemaVersion:CURRENT_SCHEMA_VERSION,currentUser:{id:'u-admin',name:'Администратор',role:USER_ROLES.ADMIN},
 users:[{id:'u-admin',name:'Администратор',role:USER_ROLES.ADMIN,active:true},{id:'u-manager-1',name:'Иванов',role:USER_ROLES.MANAGER,active:true},{id:'u-manager-2',name:'Петров',role:USER_ROLES.MANAGER,active:true}],
 settings:{currency:'RUB',vatRate:20,targetMargin:15},counters:{workSequence:3},meta:{revision:0,updatedAt:new Date().toISOString()},
 works:[{id:'w1',code:'PA-2026-0001',title:'Клапаны 46 шт',source:'Тендер',customer:'НкНПЗ',objectName:'Клапаны и запорная арматура',manager:'Иванов',deadline:todayPlus(1),state:'Расчет'},{id:'w2',code:'PA-2026-0002',title:'Расходомеры и КИП',source:'Тендер',customer:'СИБУР',objectName:'Модернизация линии учета',manager:'Петров',deadline:todayPlus(3),state:'Ожидаем ТКП'},{id:'w3',code:'PA-2026-0003',title:'Регулирующая арматура',source:'Сайт',customer:'ООО СеверХим',objectName:'Производственный участок',manager:'Иванов',deadline:todayPlus(7),state:'Новая'}],
 suppliers:[{id:'s1',name:'ООО Арматура-Сервис',city:'Москва',contact:'Алексей',phone:'+7 900 111-22-33'},{id:'s2',name:'Завод ПромКлапан',city:'Санкт-Петербург',contact:'Ирина',phone:'+7 900 222-33-44'},{id:'s3',name:'ТД КИП Комплект',city:'Екатеринбург',contact:'Олег',phone:'+7 900 333-44-55'}],
 positions:[{id:'p1',workId:'w1',rowNo:1,group:'Клапаны',name:'Клапан запорный DN50 PN40',qty:8,unit:'шт',salePrice:24800,status:'Цена рассчитана',vatRate:20,logisticsCost:0,otherCosts:0,offers:[{id:'o1',supplierId:'s1',price:18500,productionDays:15,deliveryDays:3,shipmentPlace:'Москва',paymentTerms:'50% предоплата',hasTkp:true,selected:true},{id:'o2',supplierId:'s2',price:17900,productionDays:25,deliveryDays:5,shipmentPlace:'Санкт-Петербург',paymentTerms:'100% предоплата',hasTkp:true,selected:false}],batches:[{id:'b1',qty:3,readyDate:todayPlus(8),shipDate:'',place:'Москва',status:'В производстве'}]},{id:'p2',workId:'w1',rowNo:2,group:'Клапаны',name:'Клапан обратный DN100 PN16',qty:12,unit:'шт',salePrice:36000,status:'ТКП получено',vatRate:20,logisticsCost:0,otherCosts:0,offers:[{id:'o4',supplierId:'s2',price:31200,productionDays:25,deliveryDays:5,shipmentPlace:'Санкт-Петербург',paymentTerms:'70% предоплата',hasTkp:true,selected:true}],batches:[]},{id:'p3',workId:'w1',rowNo:3,group:'Арматура',name:'Задвижка клиновая DN150 PN16',qty:6,unit:'шт',salePrice:'',status:'Нужен поставщик',vatRate:20,logisticsCost:0,otherCosts:0,offers:[],batches:[]},{id:'p4',workId:'w2',rowNo:1,group:'КИП',name:'Расходомер электромагнитный DN80',qty:4,unit:'шт',salePrice:'',status:'Ожидаем ТКП',vatRate:20,logisticsCost:0,otherCosts:0,offers:[{id:'o5',supplierId:'s3',price:94000,productionDays:20,deliveryDays:4,shipmentPlace:'Екатеринбург',paymentTerms:'50/50',hasTkp:false,selected:true}],batches:[]},{id:'p5',workId:'w3',rowNo:1,group:'Регулирующая арматура',name:'Клапан регулирующий DN25',qty:2,unit:'шт',salePrice:'',status:'Не начато',vatRate:20,logisticsCost:0,otherCosts:0,offers:[],batches:[]}],
 documents:[],tasks:[],customers:[],formulas:[],formulaImports:[],
 events:[{id:'e1',workId:'w1',positionId:'p1',type:'price',title:'Рассчитана цена продажи',detail:'24 800 ₽ за единицу',author:'Иванов',createdAt:minutesAgo(35)},{id:'e2',workId:'w1',positionId:'p1',supplierId:'s1',type:'offer',title:'Выбрано предложение поставщика',detail:'ООО Арматура-Сервис',author:'Иванов',createdAt:minutesAgo(70)}]
});

const collection=(data,key,fallback)=>Array.isArray(data?.[key])?data[key]:fallback;
export function normalizeWorkspace(raw){const base=createDemoWorkspace(),data=migrateWorkspace(raw);return{...base,...data,schemaVersion:CURRENT_SCHEMA_VERSION,currentUser:data.currentUser||base.currentUser,users:collection(data,'users',base.users),works:collection(data,'works',base.works),suppliers:collection(data,'suppliers',base.suppliers),positions:collection(data,'positions',base.positions).map(position=>({...position,qty:Math.max(0,Number(position.qty||0)),vatRate:Number(position.vatRate??data.settings?.vatRate??20),logisticsCost:Math.max(0,Number(position.logisticsCost||0)),otherCosts:Math.max(0,Number(position.otherCosts||0)),offers:position.offers||[],batches:position.batches||[]})),documents:collection(data,'documents',[]),tasks:collection(data,'tasks',[]),customers:collection(data,'customers',[]),events:collection(data,'events',base.events),formulas:collection(data,'formulas',[]),formulaImports:collection(data,'formulaImports',[]),settings:{...base.settings,...data.settings},counters:{...base.counters,...data.counters},meta:{...base.meta,...data.meta}}}

export function calculatePosition(position,suppliers,settings={},formulas=[],work=null){
 const offers=(position.offers||[]).map(offer=>({...offer,supplier:suppliers.find(supplier=>supplier.id===offer.supplierId)||null})),selected=offers.find(offer=>offer.selected===true)||null;
 const qty=Math.max(0,Number(position.qty||0)),purchase=selected?Math.max(0,Number(selected.price||0)):null,sale=Math.max(0,Number(position.salePrice||0)),logistics=Math.max(0,Number(position.logisticsCost||0)),otherCosts=Math.max(0,Number(position.otherCosts||0)),unitCost=purchase==null?null:purchase+logistics+otherCosts;
 const grossProfit=unitCost==null||!sale?null:(sale-unitCost)*qty,baseGrossMargin=unitCost==null||!sale?null:((sale-unitCost)/sale)*100,baseMarkup=unitCost==null||!unitCost||!sale?null:((sale-unitCost)/unitCost)*100,vatRate=Number(position.vatRate??settings.vatRate??20),saleTotal=sale*qty,purchaseTotal=unitCost==null?null:unitCost*qty,vatAmount=saleTotal?Math.max(0,saleTotal*vatRate/(100+vatRate)):0;
 const financial=grossProfit==null?{creditCost:0,taxAmount:0,bonusAmount:0,netProfit:null,grossMargin:baseGrossMargin,markup:baseMarkup,formulaResults:[],appliedFormulaCount:0}:applyFinancialFormulas({purchasePrice:purchase,salePrice:sale,quantity:qty,logisticsCost:logistics,otherCosts,unitCost,saleTotal,purchaseTotal,grossProfit,grossMargin:baseGrossMargin,markup:baseMarkup,vatAmount,vatRate},formulas,{position,work,settings});
 const grossMargin=financial.grossMargin,markup=financial.markup,readyQty=(position.batches||[]).filter(batch=>['Готово','Отгружено'].includes(batch.status)).reduce((sum,batch)=>sum+Number(batch.qty||0),0),shippedQty=(position.batches||[]).filter(batch=>batch.status==='Отгружено').reduce((sum,batch)=>sum+Number(batch.qty||0),0),hasTkp=offers.some(offer=>offer.hasTkp),hasSupplier=offers.some(offer=>offer.supplierId&&offer.supplier),closed=isPositionClosed(position),warnings=[];
 if(!closed&&!offers.length)warnings.push('нет предложений');if(!closed&&offers.length&&!hasSupplier)warnings.push('не указан поставщик');if(!closed&&offers.length&&!hasTkp)warnings.push('нет ТКП');if(!closed&&hasTkp&&!selected)warnings.push('не выбрано предложение');if(!closed&&!sale)warnings.push('нет цены продажи');if(grossMargin!==null&&grossMargin<Number(settings.targetMargin??15))warnings.push('низкая маржа');if(shippedQty>qty)warnings.push('отгружено больше количества');
 const milestones=[Boolean(position.name&&qty),offers.length>0,hasSupplier,hasTkp,Boolean(selected),Boolean(sale),grossMargin!==null,closed||shippedQty>=qty],progress=closed?100:Math.round(milestones.filter(Boolean).length/milestones.length*100),nextStep=closed?'Готово':!offers.length?'Добавить предложение':!hasSupplier?'Указать поставщика':!hasTkp?'Получить ТКП':!selected?'Выбрать предложение':!sale?'Рассчитать продажу':grossMargin!==null&&grossMargin<Number(settings.targetMargin??15)?'Согласовать цену':'Готово к КП';
 return{...position,offers,selected,purchase,sale,unitCost,grossProfit,profit:grossProfit,netProfit:financial.netProfit,creditCost:financial.creditCost,taxAmount:financial.taxAmount,bonusAmount:financial.bonusAmount,formulaResults:financial.formulaResults,appliedFormulaCount:financial.appliedFormulaCount,margin:grossMargin,grossMargin,markup,progress,warnings,nextStep,readyQty,shippedQty,saleTotal,purchaseTotal,vatRate,vatAmount,closed,currency:settings.currency||'RUB'};
}

export function calculateWork(work,positions,suppliers,settings={},formulas=[]){const list=positions.filter(position=>position.workId===work.id).map(position=>calculatePosition(position,suppliers,settings,formulas,work)),active=list.filter(position=>!position.closed),closed=isWorkClosed(work),progress=closed?100:list.length?Math.round(list.reduce((sum,position)=>sum+position.progress,0)/list.length):0,blockers=active.filter(position=>position.warnings.length).length,waiting=active.filter(position=>position.offers.length&&!position.offers.some(offer=>offer.hasTkp)).length,noOffers=active.filter(position=>!position.offers.length).length,saleTotal=list.reduce((sum,position)=>sum+position.saleTotal,0),purchaseTotal=list.reduce((sum,position)=>sum+Number(position.purchaseTotal||0),0),grossProfit=list.reduce((sum,position)=>sum+Number(position.grossProfit||0),0),netProfit=list.reduce((sum,position)=>sum+Number(position.netProfit??position.grossProfit??0),0),nextAction=closed?'Работа закрыта':noOffers?`Найти поставщиков для ${noOffers} поз.`:waiting?`Получить ${waiting} ТКП`:active.some(position=>!position.selected)?'Выбрать предложения':active.some(position=>!position.sale)?'Рассчитать цены продажи':active.length?'Сформировать КП':'Нет активных позиций';return{...work,positions:list,activePositions:active,progress,blockers,waiting,noOffers,nextAction,closed,deadlineBucket:deadlineBucket(work.deadline),currency:settings.currency||'RUB',totals:{saleTotal,purchaseTotal,grossProfit,profit:grossProfit,netProfit}}}
