import React,{useEffect,useMemo,useState}from'react';
import{Bookmark,Check,ClipboardPaste,LoaderCircle,Plus,Search,Sparkles,Trash2}from'lucide-react';
import{logout}from'./api/client.js';
import{useWorkspace}from'./store/useWorkspace.js';

const emptyForm=()=>({id:'',number:'',date:new Date().toISOString().slice(0,10),customer:'',title:'',sourceUrl:'',deadline:'',processBy:'',requestType:'Тендер',status:'Новая',notes:''});
const makeId=()=>globalThis.crypto?.randomUUID?.()||`req-${Date.now()}-${Math.random().toString(16).slice(2)}`;
const isoDate=value=>{const text=String(value||'');const ru=text.match(/(\d{1,2})[.\/-](\d{1,2})[.\/-](20\d{2})/);if(ru)return`${ru[3]}-${ru[2].padStart(2,'0')}-${ru[1].padStart(2,'0')}`;const direct=text.match(/(20\d{2})[-.\/](\d{1,2})[-.\/](\d{1,2})/);return direct?`${direct[1]}-${direct[2].padStart(2,'0')}-${direct[3].padStart(2,'0')}`:''};
const take=(source,labels)=>{const text=String(source||'').replace(/\r/g,'').replace(/[ \t]+/g,' ');for(const label of labels){const escaped=label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const line=text.match(new RegExp(`(?:^|\\n)\\s*${escaped}\\s*[:№]?\\s*([^\\n]{2,500})`,'im'));if(line?.[1])return line[1].trim();const inline=text.match(new RegExp(`${escaped}\\s*[:№]?\\s*(.{2,220}?)(?=\\s{2,}|(?:Заказчик|Организатор|Предмет|Наименование|Дата|Срок|Номер|Статус)\\s*[:№]|$)`,'i'));if(inline?.[1])return inline[1].trim()}return''};
const cleanTitle=value=>String(value||'').replace(/\s*[|—-]\s*(?:ТЭК|TEK)[-‑ ]?Торг.*$/i,'').replace(/^Тендер\s*[:№-]?\s*/i,'').trim();
const parseText=(text,url='',pageTitle='')=>{const number=take(text,['Номер процедуры','Номер закупки','Номер извещения','Реестровый номер','Номер лота'])||(String(url).match(/\/procedures\/(\d+)/i)?.[1]||'');const customer=take(text,['Наименование заказчика','Заказчик','Организатор закупки','Организатор']);const title=take(text,['Наименование процедуры','Наименование закупки','Предмет закупки','Объект закупки','Наименование лота'])||cleanTitle(pageTitle);const deadlineRaw=take(text,['Дата и время окончания подачи заявок','Окончание подачи заявок','Срок подачи заявок','Прием заявок до','Подача заявок до']);const publishRaw=take(text,['Дата публикации','Дата размещения','Опубликовано','Размещено']);return{number,customer,title,date:isoDate(publishRaw),deadline:isoDate(deadlineRaw),sourceUrl:url,notes:''}};
const parseCaptured=payload=>{const direct={number:payload.number||'',customer:payload.customer||'',title:payload.title||'',date:isoDate(payload.date),deadline:isoDate(payload.deadline),sourceUrl:payload.url||'',notes:payload.notes||''};if(direct.number||direct.customer||direct.title||direct.deadline)return direct;return parseText(payload.text,payload.url,payload.pageTitle||payload.title)};
const meaningfulKeys=['number','date','customer','title','deadline','sourceUrl','notes'];
const mergeEmpty=(current,incoming)=>{const next={...current};let added=0,kept=0;for(const key of meaningfulKeys){const value=String(incoming?.[key]||'').trim();if(!value)continue;if(String(current[key]||'').trim())kept++;else{next[key]=value;added++}}return{next,added,kept}};
const helperCode=`javascript:(()=>{try{const norm=s=>String(s||'').replace(/\\s+/g,' ').trim();const body=document.body?.innerText||'';const lines=body.split(/\\n+/).map(norm).filter(Boolean);const find=names=>{for(const name of names){const low=name.toLowerCase();for(let i=0;i<lines.length;i++){const line=lines[i],ll=line.toLowerCase();if(ll===low||ll===low+':'||ll.startsWith(low+':')){const own=norm(line.slice(name.length).replace(/^[:№\\s-]+/,''));if(own)return own;for(let j=i+1;j<Math.min(lines.length,i+4);j++){if(lines[j]&&!/:$/.test(lines[j]))return lines[j]}}}}return''};const h1=norm(document.querySelector('h1')?.innerText);const url=location.href;const p={url,number:(url.match(/\\/procedures\\/(\\d+)/i)||[])[1]||find(['Номер процедуры','Номер закупки','Реестровый номер']),customer:find(['Наименование заказчика','Заказчик','Организатор закупки','Организатор']),title:find(['Наименование процедуры','Наименование закупки','Предмет закупки','Объект закупки'])||h1||document.title,date:find(['Дата публикации','Дата размещения','Опубликовано','Размещено']),deadline:find(['Дата и время окончания подачи заявок','Окончание подачи заявок','Срок подачи заявок','Подача заявок до'])};const b=btoa(unescape(encodeURIComponent(JSON.stringify(p))));location.href='https://promapparat-workspace.pages.dev/#capture='+encodeURIComponent(b)}catch(e){alert('Не удалось передать страницу: '+e.message)}})()`;

export default function App({serverSession=null}){
 const workspace=useWorkspace({serverSession}),{data,setData}=workspace;
 const[form,setForm]=useState(emptyForm),[query,setQuery]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[parsing,setParsing]=useState(false),[helperCopied,setHelperCopied]=useState(false),[pasteOpen,setPasteOpen]=useState(false),[pastedText,setPastedText]=useState('');
 const rows=useMemo(()=>Array.isArray(data.requestsV1)?data.requestsV1:[],[data.requestsV1]);
 const filtered=rows.filter(item=>`${item.number} ${item.customer} ${item.title} ${item.sourceUrl}`.toLowerCase().includes(query.toLowerCase()));
 const change=(field,value)=>setForm(current=>({...current,[field]:value}));
 const clear=()=>{setForm(emptyForm());setError('');setNotice('');setPastedText('');setPasteOpen(false)};
 const edit=item=>{setForm({...emptyForm(),...item});setError('');setNotice('');window.scrollTo({top:0,behavior:'smooth'})};
 const applyIncoming=incoming=>setForm(current=>{const merged=mergeEmpty(current,incoming);setNotice(merged.added?`Заполнено полей: ${merged.added}.${merged.kept?` Уже введённые данные сохранены: ${merged.kept}.`:''} Проверьте форму перед сохранением.`:'Новые данные не найдены или соответствующие поля уже заполнены.');return{...merged.next,requestType:current.requestType||'Тендер',status:current.status||'Новая'}});
 useEffect(()=>{const hash=window.location.hash;if(!hash.startsWith('#capture='))return;try{const encoded=decodeURIComponent(hash.slice(9));const payload=JSON.parse(decodeURIComponent(escape(atob(encoded))));applyIncoming(parseCaptured(payload));window.history.replaceState({},'',window.location.pathname+window.location.search)}catch{setError('Не удалось прочитать данные из браузерного помощника.')}},[]);
 const copyHelper=async()=>{try{await navigator.clipboard.writeText(helperCode);setHelperCopied(true);setNotice('Код помощника скопирован. Создайте закладку и вставьте код в поле URL.');setTimeout(()=>setHelperCopied(false),2500)}catch{setError('Браузер не разрешил копирование. Перетащите кнопку помощника на панель закладок.')}};
 const parsePasted=()=>{if(!pastedText.trim()){setError('Вставьте текст страницы тендера.');return}setError('');applyIncoming(parseText(pastedText,form.sourceUrl,document.title));setPasteOpen(false)};
 const autofill=async()=>{
  const url=form.sourceUrl.trim();if(!url){setError('Сначала вставьте ссылку на тендер.');return}
  if(/tektorg\.ru/i.test(url)){setError('Tek‑Torg блокирует серверные запросы. Используйте браузерный помощник или вставьте текст страницы ниже.');setPasteOpen(true);return}
  setParsing(true);setError('');setNotice('');
  try{const response=await fetch('/api/tender/parse',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Не удалось получить данные тендера.');applyIncoming({...result.data,sourceUrl:url})}catch(exception){setError(exception?.message||'Не удалось обработать ссылку. Возможно, площадка требует авторизацию.')}finally{setParsing(false)}
 };
 const save=event=>{event.preventDefault();const customer=form.customer.trim(),title=form.title.trim();if(!customer||!title){setError('Заполните заказчика и предмет закупки.');return}const record={...form,id:form.id||makeId(),customer,title,updatedAt:new Date().toISOString()};setData(current=>{const list=Array.isArray(current.requestsV1)?current.requestsV1:[],exists=list.some(item=>item.id===record.id);return{...current,requestsV1:exists?list.map(item=>item.id===record.id?record:item):[record,...list]}});clear()};
 const remove=id=>{if(!window.confirm('Удалить эту заявку?'))return;setData(current=>({...current,requestsV1:(current.requestsV1||[]).filter(item=>item.id!==id)}));if(form.id===id)clear()};
 if(workspace.loading)return <main className="input-loading">Загрузка…</main>;
 return <main className="input-app">
  <header className="input-topbar"><div><b>Промаппарат</b><span>Этап 2 · ввод по ссылке</span></div>{serverSession&&<button onClick={()=>logout()}>Выйти</button>}</header>
  <section className="input-layout">
   <form className="input-form" onSubmit={save}>
    <div className="input-form-head"><div><span>{form.id?'Редактирование':'Новая заявка'}</span><h1>Ввод данных</h1></div>{form.id&&<button type="button" onClick={clear}>Новая</button>}</div>
    {error&&<div className="input-error">{error}</div>}{notice&&<div className="input-notice">{notice}</div>}
    <div className="input-grid">
     <label className="full">Ссылка на тендер<div className="url-autofill"><input type="url" value={form.sourceUrl} onChange={e=>change('sourceUrl',e.target.value)} placeholder="https://"/><button type="button" onClick={autofill} disabled={parsing}>{parsing?<LoaderCircle className="spin"/>:<Sparkles/>}{parsing?'Загружаю…':'Заполнить по ссылке'}</button></div></label>
     {/tektorg\.ru/i.test(form.sourceUrl)&&<div className="tektorg-helper"><div><b>Импорт с Tek‑Torg</b><span>Помощник читает уже открытую страницу в вашем браузере и не обращается к заблокированному серверному API.</span></div><a href={helperCode} title="Перетащите на панель закладок"><Bookmark/>Помощник Tek‑Torg</a><button type="button" onClick={copyHelper}>{helperCopied?<Check/>:<Bookmark/>}{helperCopied?'Скопировано':'Скопировать код'}</button><button type="button" onClick={()=>setPasteOpen(value=>!value)}><ClipboardPaste/>Вставить текст</button></div>}
     {pasteOpen&&<div className="paste-import"><b>Резервный импорт</b><span>На странице тендера нажмите Ctrl+A, затем Ctrl+C и вставьте текст сюда.</span><textarea value={pastedText} onChange={e=>setPastedText(e.target.value)} rows="7" placeholder="Вставьте текст страницы Tek‑Torg"/><div><button type="button" onClick={()=>setPasteOpen(false)}>Отмена</button><button type="button" className="primary" onClick={parsePasted}>Разобрать текст</button></div></div>}
     <label>№ заявки<input value={form.number} onChange={e=>change('number',e.target.value)}/></label>
     <label>Дата<input type="date" value={form.date} onChange={e=>change('date',e.target.value)}/></label>
     <label>Обработать до<input type="date" value={form.processBy} onChange={e=>change('processBy',e.target.value)}/></label>
     <label>Срок подачи<input type="date" value={form.deadline} onChange={e=>change('deadline',e.target.value)}/></label>
     <label className="wide">Заказчик *<input value={form.customer} onChange={e=>change('customer',e.target.value)} placeholder="Название организации"/></label>
     <label className="wide">Предмет закупки *<input value={form.title} onChange={e=>change('title',e.target.value)} placeholder="Что закупают"/></label>
     <label>Характер заявки<select value={form.requestType} onChange={e=>change('requestType',e.target.value)}><option>Тендер</option><option>Запрос цены</option><option>Текущая потребность</option><option>Другое</option></select></label>
     <label>Статус<select value={form.status} onChange={e=>change('status',e.target.value)}><option>Новая</option><option>В работе</option><option>Отложена</option><option>Закрыта</option></select></label>
     <label className="full">Комментарий<textarea value={form.notes} onChange={e=>change('notes',e.target.value)} rows="4"/></label>
    </div>
    <div className="input-actions"><button type="button" onClick={clear}>Очистить</button><button className="primary" type="submit">{form.id?'Сохранить изменения':'Сохранить заявку'}</button></div>
   </form>
   <section className="input-register">
    <div className="input-register-head"><div><h2>Заявки</h2><span>{rows.length}</span></div><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск"/></label></div>
    <div className="input-table-wrap"><table><thead><tr><th>№</th><th>Дата</th><th>Заказчик</th><th>Предмет</th><th>Срок</th><th>Статус</th><th></th></tr></thead><tbody>{filtered.map(item=><tr key={item.id} onDoubleClick={()=>edit(item)}><td>{item.number||'—'}</td><td>{item.date||'—'}</td><td><button className="row-open" onClick={()=>edit(item)}>{item.customer}</button></td><td>{item.title}</td><td>{item.deadline||'—'}</td><td>{item.status}</td><td><button className="row-delete" onClick={()=>remove(item.id)} title="Удалить"><Trash2/></button></td></tr>)}</tbody></table>{!filtered.length&&<div className="input-empty"><Plus/><b>Заявок пока нет</b><span>Вставьте ссылку или заполните форму вручную.</span></div>}</div>
   </section>
  </section>
 </main>;
}