const cleanText=value=>String(value||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\s+/g,' ').trim();
const first=(source,patterns)=>{for(const pattern of patterns){const match=source.match(pattern);if(match?.[1])return cleanText(match[1])}return''};
const isoDate=value=>{if(!value)return'';const normalized=String(value).trim();const direct=normalized.match(/(20\d{2})[-./](\d{1,2})[-./](\d{1,2})/);if(direct)return`${direct[1]}-${direct[2].padStart(2,'0')}-${direct[3].padStart(2,'0')}`;const ru=normalized.match(/(\d{1,2})[.\/-](\d{1,2})[.\/-](20\d{2})/);if(ru)return`${ru[3]}-${ru[2].padStart(2,'0')}-${ru[1].padStart(2,'0')}`;const parsed=new Date(normalized);return Number.isNaN(parsed.getTime())?'':parsed.toISOString().slice(0,10)};
const meta=(html,name)=>first(html,[new RegExp(`<meta[^>]+(?:name|property)=["']${name}["'][^>]+content=["']([^"']+)["']`,'i'),new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:name|property)=["']${name}["']`,'i')]);
const jsonLd=html=>{const blocks=[...html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)];for(const block of blocks){try{const parsed=JSON.parse(block[1]);const list=Array.isArray(parsed)?parsed:[parsed];for(const item of list){if(item&&typeof item==='object')return item}}catch{}}return{}};
const label=(plain,names)=>{for(const name of names){const escaped=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const match=plain.match(new RegExp(`${escaped}\\s*[:№]?\\s*([^|;]{2,180}?)(?=\\s{2,}|(?:Заказчик|Организатор|Предмет|Наименование|Дата|Срок|Номер|Цена|Начальная цена)\\s*[:№]|$)`,'i'));if(match?.[1])return match[1].trim()}return''};
const normalizeUrl=value=>{const url=new URL(value);url.hash='';if(url.hostname==='www.tektorg.ru')url.hostname='tektorg.ru';return url.toString()};
const fetchHtml=async initialUrl=>{let current=normalizeUrl(initialUrl);const visited=new Set();for(let step=0;step<6;step+=1){if(visited.has(current))throw new Error('Площадка зациклила перенаправление. Для этой площадки нужен отдельный адаптер.');visited.add(current);const response=await fetch(current,{redirect:'manual',headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/126 Safari/537.36','accept':'text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8','accept-language':'ru-RU,ru;q=0.9,en;q=0.7','cache-control':'no-cache'}});if([301,302,303,307,308].includes(response.status)){const location=response.headers.get('location');if(!location)throw new Error(`Площадка вернула перенаправление ${response.status} без адреса.`);current=normalizeUrl(new URL(location,current).toString());continue}if(!response.ok)throw new Error(`Площадка вернула ошибку ${response.status}.`);const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))throw new Error('По ссылке открывается не веб-страница.');const html=await response.text();if(html.length>5_000_000)throw new Error('Страница слишком большая для обработки.');return{html,finalUrl:current}}throw new Error('Площадка выполнила слишком много перенаправлений. Для неё нужен отдельный адаптер.')};
export async function onRequestPost({request}){
 try{
  const body=await request.json();const rawUrl=String(body?.url||'').trim();
  if(!/^https?:\/\//i.test(rawUrl))return Response.json({error:'Укажите корректную ссылку.'},{status:400});
  const target=new URL(rawUrl);if(['localhost','127.0.0.1','0.0.0.0'].includes(target.hostname)||target.hostname.endsWith('.local'))return Response.json({error:'Этот адрес недоступен.'},{status:400});
  const{html,finalUrl}=await fetchHtml(rawUrl),plain=cleanText(html),structured=jsonLd(html);
  const title=meta(html,'og:title')||structured.name||structured.headline||first(html,[/<h1[^>]*>([\s\S]*?)<\/h1>/i,/<title[^>]*>([\s\S]*?)<\/title>/i]);
  const description=meta(html,'og:description')||meta(html,'description')||structured.description||'';
  const number=label(plain,['Номер закупки','Номер извещения','Номер тендера','Закупка №','Извещение №','Номер процедуры'])||first(finalUrl,[/[?&](?:noticeId|purchaseNumber|tenderId|id)=([^&]+)/i,/\/(\d{6,})(?:\/|$|\?)/]);
  const customer=label(plain,['Заказчик','Наименование заказчика','Организатор закупки','Организатор']);
  const deadlineRaw=label(plain,['Окончание подачи заявок','Дата окончания подачи заявок','Срок подачи заявок','Прием заявок до','Дата и время окончания подачи']);
  const publishRaw=label(plain,['Дата публикации','Размещено','Дата размещения','Опубликовано']);
  const subject=label(plain,['Предмет закупки','Наименование закупки','Объект закупки'])||title;
  const data={number,customer,title:subject,date:isoDate(publishRaw)||new Date().toISOString().slice(0,10),deadline:isoDate(deadlineRaw),processBy:'',requestType:'Тендер',status:'Новая',sourceUrl:rawUrl,notes:description};
  const filled=Object.entries(data).filter(([,value])=>Boolean(value)).map(([key])=>key);
  return Response.json({data,filled,source:target.hostname,finalUrl});
 }catch(error){const message=String(error?.message||'Не удалось обработать ссылку.').split('\n')[0].slice(0,240);return Response.json({error:message},{status:422})}
}